---
sidebar: sidebar 
permalink: access-data.html 
keywords: access data, mount point, mount volumes, mount clients, on-premises 
summary: Puede acceder a sus sistemas de archivos FSx para ONTAP desde las instalaciones montando volúmenes para clientes NAS y montando LUN iSCSI para clientes SAN. 
---
= Accede a tus datos del sistema de archivos FSx for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puede acceder a sus sistemas de archivos FSx para ONTAP desde las instalaciones montando volúmenes para clientes NAS y montando LUN iSCSI para clientes SAN.

link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/supported-fsx-clients.html["Accediendo a los datos"^] En la documentación de Amazon FSx para NetApp ONTAP encontrarás temas sobre cómo acceder a los datos para tu referencia.

También puede obtener el punto de montaje de los volúmenes en NetApp Workload Factory.



== Obtener el punto de montaje para volúmenes en NetApp Workload Factory

Obtenga el punto de montaje de un volumen para montar un recurso compartido en un recurso compartido CIFS o un cliente NFS.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con el volumen y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña Volúmenes, seleccione el menú de acciones para el volumen, luego *Acciones básicas* y luego *Ver comando de montaje*.
. En el cuadro de diálogo de comandos Mount, seleccione *Copy* para copiar el comando para el punto de montaje NFS o el recurso compartido CIFS. Ingresarás el comando copiado en tu terminal.
. Seleccione *Cerrar*.




== Conéctese a clientes NAS

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-linux-client.html["Montaje de un volumen en clientes Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-windows-client.html["Montar un volumen en clientes Windows"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-mac-client.html["Montar un volumen en clientes macOS"^]




== Conéctese con clientes SAN

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-luns-linux.html["Monte una LUN iSCSI en clientes Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-windows.html["Monte un LUN iSCSI en los clientes Windows"^]

