---
sidebar: sidebar 
permalink: access-data.html 
keywords: access data, mount point, mount volumes, mount clients, on-premises 
summary: Puede acceder a sus sistemas de archivos FSx para ONTAP desde las instalaciones montando volúmenes para clientes NAS y montando LUN iSCSI para clientes SAN. 
---
= Accede a tus datos del sistema de archivos FSx for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puede acceder a sus sistemas de archivos FSx para ONTAP desde las instalaciones montando volúmenes para clientes NAS y montando LUN iSCSI para clientes SAN.

link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/supported-fsx-clients.html["Accediendo a los datos"^] En la documentación de Amazon FSx para NetApp ONTAP encontrarás temas sobre cómo acceder a los datos para tu referencia.

También puede obtener el punto de montaje para volúmenes en la fábrica de cargas de trabajo BlueXP .



== Obtén el punto de montaje para volúmenes en la fábrica de cargas de trabajo BlueXP 

Obtenga el punto de montaje de un volumen para montar un recurso compartido en un recurso compartido CIFS o un cliente NFS.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volúmenes, seleccione el menú de tres puntos para el volumen, luego *Acciones básicas* y luego *Comando de montaje de vista*.
. En el cuadro de diálogo de comandos Mount, seleccione *Copy* para copiar el comando. Ingresarás el comando copiado en tu terminal.
. Seleccione *Cerrar*.




== Conéctese a clientes NAS

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-linux-client.html["Montaje de un volumen en clientes Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-windows-client.html["Montar un volumen en clientes Windows"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-mac-client.html["Montar un volumen en clientes macOS"^]




== Conéctese con clientes SAN

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-luns-linux.html["Monte una LUN iSCSI en clientes Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-windows.html["Monte un LUN iSCSI en los clientes Windows"^]

