---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: Replique volúmenes de protección de datos o agrupe en cascada la replicación de datos de volúmenes para ampliar la protección de datos a sistemas terciarios o migrar los datos. 
---
= Replique los volúmenes de protección de datos en fábrica de cargas de trabajo BlueXP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Replique volúmenes de protección de datos o agrupe en cascada la replicación de datos de volúmenes para ampliar la protección de datos a sistemas terciarios o migrar los datos.

.Acerca de esta tarea
La fábrica de cargas de trabajo de BlueXP  admite la replicación de volúmenes de protección de datos, también denominados _implementaciones en cascada_. Un _despliegue en cascada_ consiste en una cadena de relaciones en la que un volumen de origen se refleja en un volumen secundario (primer salto), y el volumen secundario se refleja en un volumen terciario (segundo salto). Si el volumen secundario deja de estar disponible, puede sincronizar la relación entre los volúmenes primario y terciario sin necesidad de realizar una nueva transferencia de base de referencia.

Esta función es compatible con los sistemas de archivos FSx para ONTAP con ONTAP versión 9,6 y posteriores. Consulte link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["Documentación de ONTAP para versiones de ONTAP compatibles"^].

Más información sobre link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work["funcionamiento de las implementaciones en cascada"^].

.Antes de empezar
Considere lo siguiente antes de comenzar:

* Tenga en cuenta que los volúmenes que forman parte de una configuración en cascada pueden tardar más en resincronizarse.
* Si el volumen de origen de la relación es un volumen de protección de datos y el objetivo de otra relación, no se admite revertir la relación de replicación.
* Se admite una réplica de un volumen de protección de datos (o un segundo salto). No se considera práctica recomendada crear una segunda réplica de un volumen de protección de datos (o un tercer salto).


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, seleccione el menú de tres puntos del sistema de archivos que contiene los volúmenes que desea replicar y, a continuación, seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la tabla Volúmenes, seleccione uno o más volúmenes de protección de datos (DP/volúmenes replicados) y, a continuación, seleccione *Replicar datos*.
. En la página Replicar datos, en Destino de replicación, proporcione lo siguiente:
+
.. *FSX para el sistema de archivos ONTAP*: Seleccione credenciales, región y FSX para el nombre del sistema de archivos ONTAP para el sistema de archivos FSX para ONTAP de destino.
.. *Nombre de VM de almacenamiento*: Seleccione la VM de almacenamiento en el menú desplegable.
.. *Nombre del volumen*: El nombre del volumen de destino se genera automáticamente con el siguiente formato `{OriginalVolumeName}_copy`. Se puede usar el nombre de volumen generado automáticamente o introducir otro nombre de volumen.
.. *Caso de uso*: Seleccione uno de los siguientes casos de uso para la replicación. En función del caso de uso seleccionado, la fábrica de cargas de trabajo rellena el formulario con los valores recomendados de acuerdo con las mejores prácticas. Puede aceptar los valores recomendados o realizar cambios a medida que complete el formulario.
+
*** Migración: Transfiere tus datos al sistema de archivos FSx para ONTAP de destino
*** Recuperación ante desastres en caliente: Garantiza una alta disponibilidad y una recuperación ante desastres rápida para cargas de trabajo críticas
*** Recuperación ante desastres en frío o de archivado:
+
**** Recuperación ante desastres en frío: Utiliza objetivos de tiempo de recuperación (RTO) y objetos de punto de recuperación (RPO) más largos para reducir los costes
**** Archivado: Replica los datos para un almacenamiento a largo plazo y cumplimiento de normativas


*** Otros


.. *Política de niveles*: Seleccione la política de organización en niveles para los datos almacenados en el volumen de destino. La política de organización en niveles se establece de forma predeterminada en la política de organización en niveles recomendada para el caso de uso seleccionado.
+
_Balanced (Auto)_ es la política de organización en niveles predeterminada al crear un volumen con la consola de cargas de trabajo de fábrica. Para obtener más información sobre las políticas de organización en niveles de volúmenes, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento del volumen"^] la documentación de AWS FSx para NetApp ONTAP. Tenga en cuenta que la fábrica de carga de trabajo utiliza nombres basados en casos de uso en la consola de fábrica de cargas de trabajo para las políticas de organización en niveles e incluye los nombres de las políticas de organización en niveles de FSx para ONTAP entre paréntesis.

+
Si seleccionó el caso de uso de migración, la fábrica de carga de trabajo selecciona automáticamente copiar la política de organización en niveles del volumen de origen al volumen objetivo. Puede anular la selección para copiar la política de organización en niveles y seleccionar una política de organización en niveles que se aplique al volumen seleccionado para replicación.

.. *Tasa de transferencia máxima*: Selecciona *Limited* e introduce el límite máximo de transferencia en MB/s.. Alternativamente, selecciona *Ilimitado*.
+
Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir. También recomendamos una tasa de transferencia ilimitada para los sistemas de archivos de FSx for ONTAP para cargas de trabajo cruciales; por ejemplo, aquellas que se usan principalmente para la recuperación ante desastres.



. En Configuración de replicación, proporcione lo siguiente:
+
.. *Intervalo de replicación*: Seleccione la frecuencia con la que se transfieren las instantáneas del volumen de origen al volumen de destino.
.. *Retención a largo plazo*: Opcionalmente, habilita instantáneas para la retención a largo plazo. La retención a largo plazo permite que los servicios empresariales continúen funcionando incluso si se produce un fallo completo del sitio, compatible con la conmutación por error de forma transparente mediante una copia secundaria.
+
Las replicaciones sin retención a largo plazo utilizan la política _MirrorAllSnapshots_. Al habilitar la retención a largo plazo, se asigna la política _MirrorAndVault_ a la replicación.

+
Si habilita la retención a largo plazo, seleccione una política existente o cree una nueva política para definir las snapshots que se replicarán y el número que se retendrá.

+

NOTE: Las etiquetas de origen y destino coincidentes son necesarias para la retención a largo plazo. Si lo desea, la fábrica de carga de trabajo puede crear etiquetas que faltan.

+
*** *Elige una política existente*: Selecciona una política existente en el menú desplegable.
*** *Crear una nueva política*: Proporcionar lo siguiente:
+
**** *Nombre de la política*: Introduzca un nombre de política.
**** Opcional: Habilitar copias de Snapshot inmutables.
+
***** Seleccione *Activar instantáneas inmutables* para evitar que las instantáneas tomadas en esta política se eliminen durante el período de retención.
***** Establezca el *Período de retención* en número de horas, días, meses o años.


**** *Políticas de instantáneas*: En la tabla, seleccione la frecuencia de la política de instantáneas y el número de copias que se deben retener. Puede seleccionar más de una política de Snapshot.






. Seleccione *Crear*.


.Resultado
El volumen o los volúmenes replicados se replican y aparecen en la pestaña *Relaciones de replicación* en el sistema de archivos FSX for ONTAP de destino.
