---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: Replique volúmenes de protección de datos o agrupe en cascada la replicación de datos de volúmenes para ampliar la protección de datos a sistemas terciarios o migrar los datos. 
---
= Replique los volúmenes de protección de datos en fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Replique volúmenes de protección de datos o agrupe en cascada la replicación de datos de volúmenes para ampliar la protección de datos a sistemas terciarios o migrar los datos.

.Acerca de esta tarea
La fábrica de cargas de trabajo de BlueXP  admite la replicación de volúmenes de protección de datos. En ONTAP, la replicación de los volúmenes de protección de datos se considera una implementación en cascada _reflejo-reflejo_. Una puesta en marcha en cascada de reflejos consiste en una cadena de relaciones en las que un volumen de origen se refleja en un volumen secundario, mientras que el volumen secundario se duplica en un volumen terciario. Si el volumen secundario deja de estar disponible, puede sincronizar la relación entre los volúmenes primario y terciario sin necesidad de realizar una nueva transferencia de base de referencia.

Esta función es compatible con los sistemas de archivos FSx para ONTAP con ONTAP versión 9,6 y posteriores. Consulte link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["Documentación de ONTAP para versiones de ONTAP compatibles"^].


NOTE: Si el volumen de origen de la relación es un volumen de protección de datos y el objetivo de otra relación, no se admite revertir la relación de replicación.

.Antes de empezar
Tenga en cuenta que los volúmenes que forman parte de una configuración en cascada pueden tardar más en resincronizarse.

[role="tabbed-block"]
====
.Replicación de un único volumen
--
Puede replicar un volumen de protección de datos (DP).


NOTE: Se admite una réplica de un volumen de protección de datos. No puede crear una segunda réplica de un volumen de DP.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione Ir a inventario de almacenamiento.
. En la pestaña FSx para ONTAP, seleccione el menú de tres puntos del sistema de archivos que desea actualizar y, a continuación, seleccione Gestionar.
. Seleccione la pestaña volúmenes.
. Seleccione el menú de tres puntos del volumen de protección de datos (DP/volumen replicado) y seleccione *Replicar datos de volumen*.
. En la página Create replication, en Replication target, proporcione lo siguiente:
+
.. *FSX para el sistema de archivos ONTAP*: Seleccione credenciales, región y FSX para el nombre del sistema de archivos ONTAP para el sistema de archivos FSX para ONTAP de destino.
.. *Nombre de VM de almacenamiento*: Seleccione la VM de almacenamiento en el menú desplegable.
.. *Nombre del volumen*: El nombre del volumen de destino se genera automáticamente con el siguiente formato `{OriginalVolumeName}_copy`. Se puede usar el nombre de volumen generado automáticamente o introducir otro nombre de volumen.
.. *Caso de uso*: Seleccione uno de los siguientes casos de uso para la replicación.
+
*** Migración: Transfiere tus datos al sistema de archivos FSx para ONTAP de destino
*** Recuperación ante desastres en caliente: Garantiza una alta disponibilidad y una recuperación ante desastres rápida para cargas de trabajo críticas
*** Recuperación ante desastres en frío o de archivado:
+
**** Recuperación ante desastres en frío: Utiliza objetivos de tiempo de recuperación (RTO) y objetos de punto de recuperación (RPO) más largos para reducir los costes
**** Archivado: Replica los datos para un almacenamiento a largo plazo y cumplimiento de normativas


*** Otros


.. *Política de niveles*: Seleccione la política de organización en niveles para los datos almacenados en el volumen de destino. En función del caso de uso que haya seleccionado, la política de organización en niveles se establece de forma predeterminada en la política de organización en niveles recomendada para el caso de uso.
+
_Balanced (Auto)_ es la política de organización en niveles predeterminada al crear un volumen con la interfaz de usuario de FSx para ONTAP de la fábrica de cargas de trabajo. Para obtener más información sobre las políticas de organización en niveles de volúmenes, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento del volumen"^] la documentación de AWS FSx para NetApp ONTAP.

.. *Tasa de transferencia máxima*: Selecciona *Limited* e introduce el límite máximo de transferencia en MB/s.. Alternativamente, selecciona *Ilimitado*.
+
Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir. También recomendamos una tasa de transferencia ilimitada para los sistemas de archivos de FSx for ONTAP para cargas de trabajo cruciales; por ejemplo, aquellas que se usan principalmente para la recuperación ante desastres.



. En Configuración de replicación, proporcione lo siguiente:
+
.. *Intervalo de replicación*: Seleccione la frecuencia con la que se transfieren las instantáneas del volumen de origen al volumen de destino.
.. *Retención a largo plazo*: Opcionalmente, habilita instantáneas para la retención a largo plazo.
+
Si habilita la retención a largo plazo, seleccione una política existente o cree una nueva política para definir las snapshots que se replicarán y el número que se retendrá.

+
*** Para *Elige una política existente*, selecciona una política existente en el menú desplegable.
*** Para *Crear una nueva política*, proporcione lo siguiente:
+
**** *Nombre de la política*: Introduzca un nombre de política.
**** *Políticas de instantáneas*: En la tabla, seleccione la frecuencia de la política de instantáneas y el número de copias que se deben retener. Puede seleccionar más de una política de Snapshot.






. Seleccione *Crear*.


--
.Replicar todos los volúmenes en un sistema de archivos
--
Puede replicar todos los volúmenes de protección de datos (DP) en un sistema de archivos.


NOTE: Se admite una réplica de un volumen de protección de datos. No puede crear una segunda réplica de un volumen de DP.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña FSX para ONTAP, seleccione el menú de tres puntos del sistema de archivos con los volúmenes y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, seleccione *Crear replicación*.
. En la página Create replication, en Replication target, proporcione lo siguiente:
+
.. *FSX para el sistema de archivos ONTAP*: Seleccione credenciales, región y FSX para el nombre del sistema de archivos ONTAP para el sistema de archivos FSX para ONTAP de destino.
.. *Nombre de VM de almacenamiento*: Seleccione la VM de almacenamiento en el menú desplegable.
.. *Nombre del volumen*: El nombre del volumen de destino se genera automáticamente con el siguiente formato `{OriginalVolumeName}_copy`.
.. *Política de niveles*: Seleccione la política de organización en niveles para los datos almacenados en el volumen de destino.
+
_Auto_ es la política de organización en niveles predeterminada al crear un volumen mediante la interfaz de usuario de FSx para ONTAP de la fábrica de cargas de trabajo. Para obtener más información sobre las políticas de organización en niveles de volúmenes, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento del volumen"^]la documentación de AWS FSx para NetApp ONTAP.

.. *Tasa de transferencia máxima*: Seleccione *Limited* e introduzca el límite máximo de transferencia en MIB/s.. Alternativamente, selecciona *Ilimitado*.
+
Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir. También recomendamos una tasa de transferencia ilimitada para los sistemas de archivos de FSx for ONTAP para cargas de trabajo cruciales; por ejemplo, aquellas que se usan principalmente para la recuperación ante desastres.



. En Configuración de replicación, proporcione lo siguiente:
+
.. *Intervalo de replicación*: Seleccione la frecuencia con la que se transfieren las instantáneas del volumen de origen al volumen de destino.
.. *Retención a largo plazo*: Opcionalmente, habilita instantáneas para la retención a largo plazo.
+
Si habilita la retención a largo plazo, seleccione una política existente o cree una nueva política para definir las snapshots que se replicarán y el número que se retendrá.

+
*** Para *Elige una política existente*, selecciona una política existente en el menú desplegable.
*** Para *Crear una nueva política*, proporcione lo siguiente:
+
**** *Nombre de la política*: Introduzca un nombre de política.
**** *Políticas de instantáneas*: En la tabla, seleccione la frecuencia de la política de instantáneas y el número de copias que se deben retener. Puede seleccionar más de una política de Snapshot.






. Seleccione *Crear*.


--
====
.Resultado
El volumen o los volúmenes replicados se replican y aparecen en la pestaña *Relaciones de replicación* en el sistema de archivos FSX for ONTAP de destino.
