---
sidebar: sidebar 
permalink: change-snapshot-policy.html 
keywords: snapshot policy, snapshot schedule, modify snapshot policy, edit snapshot policy, change snapshot policy 
summary: Actualice la política de copias Snapshot de un volumen en la fábrica de cargas de trabajo BlueXP  en cualquier momento. 
---
= Cambie la política de Snapshot de un volumen en la fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Actualice la frecuencia de las instantáneas tomadas para un volumen o desactive las instantáneas automáticas en cualquier momento en la fábrica de cargas de trabajo BlueXP .

.Antes de empezar
Para mostrar las políticas de instantáneas existentes, debe asociar un enlace. Para asociar un enlace, seleccione *Enlace asociado* en *Nombre de cuenta*. A continuación, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos FSX for ONTAP que contiene el volumen con la política de instantáneas que se va a actualizar y luego selecciona *Administrar*.
. En la pestaña Descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Seleccione la pestaña *Volúmenes*.
. En la pestaña *Volúmenes*, seleccione el menú de tres puntos del volumen para cambiar la política de instantáneas.
. Seleccione *Acciones de protección de datos*, *Snapshots* y luego *Administrar políticas de instantáneas*.
. En la página de administración de políticas de Snapshot, seleccione *Cambiar una política de instantáneas existente*.
. En el campo *Nombre de la política de instantáneas*, seleccione una política de instantáneas diferente para este volumen.
+
Para desactivar las instantáneas automáticas, seleccione `none`.

+
Si no existen otras políticas de instantáneas, link:create-snapshot-policy.html["cree una política de snapshots nueva para este volumen"].

. Seleccione *Aplicar* para guardar los cambios.

