---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords: tiering policy, change tier, change tiers, tier policy update 
summary: Cambie la política de organización en niveles en la fábrica de cargas de trabajo BlueXP  para volver a asignar datos del nivel de almacenamiento principal de alto rendimiento al nivel de almacenamiento del pool de capacidad secundario. 
---
= Cambie la política de organización en niveles de un volumen en la fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
En la fábrica de cargas de trabajo BlueXP , se puede cambiar la política de organización en niveles para volver a asignar datos automáticamente desde el nivel de almacenamiento primario de alto rendimiento al nivel de almacenamiento secundario del pool de capacidad.

.Acerca de esta tarea
Puede cambiar la política de organización en niveles de un volumen en cualquier momento. La política de organización en niveles se define por volumen.

Decidir dónde se almacenan los datos tiene implicaciones para ahorrar costes.

FSX para ONTAP tiene dos niveles para almacenar datos de volúmenes:

* *Nivel de almacenamiento SSD*: Este nivel de almacenamiento primario es para los datos a los que accede con más frecuencia, también conocidos como datos _hot_. El almacenamiento de datos en el nivel de almacenamiento primario es más caro que en el nivel de almacenamiento secundario.
* *Nivel de almacenamiento del pool de capacidad*: Este nivel de almacenamiento secundario es para datos archivados o datos a los que se accede con poca frecuencia, también conocidos como datos _cold_.


Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["Gestión de la capacidad de almacenamiento"^] en la documentación de AWS para FSx para NetApp ONTAP para obtener más información sobre los niveles de almacenamiento.

.Antes de empezar
Revise las políticas de organización en niveles disponibles antes de cambiar la política de organización en niveles.

* *Balanced (Auto)*: Política de organización en niveles predeterminada al crear un volumen usando la interfaz de usuario. Mantiene los datos a los que se accede con frecuencia en el nivel de almacenamiento de unidades de estado sólido y organiza en niveles las instantáneas y los datos a los que se accede con poca frecuencia en el nivel de almacenamiento del pool de capacidad una vez que finaliza el período de enfriamiento. Recomendado para cargas de trabajo principales generales.
* *Cost-Optimized (All)*: Organiza en niveles todas las instantáneas y los datos en el nivel de almacenamiento del pool de capacidad. Recomendado para destinos secundarios.
* *Rendimiento optimizado (solo instantáneas)*: Organiza en niveles solo los datos de instantánea en el nivel de almacenamiento de la agrupación de capacidad. Se recomienda para cargas de trabajo de baja latencia, como bases de datos críticas.
* *Ninguno*: Mantiene los datos de volumen en el nivel de almacenamiento SSD, evitando que se muevan al nivel de almacenamiento del pool de capacidad.


Tenga en cuenta que algunas políticas de organización en niveles tienen asociado un período de enfriamiento mínimo que establece el tiempo, o _días de enfriamiento_, los datos de usuario en un volumen deben permanecer inactivos para que los datos se consideren inactivos y se muevan al nivel de almacenamiento del pool de capacidad. El período de enfriamiento comienza cuando los datos se escriben en el disco.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, seleccione el menú de tres puntos del sistema de archivos con el volumen que desea actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volumes, seleccione el menú de tres puntos del volumen para cambiar la política de organización en niveles.
. Selecciona *Acciones avanzadas*, luego *Cambiar política de niveles*.
. En la página Change Tiering policy, seleccione para copiar la política de organización en niveles del volumen de origen o seleccione una de las siguientes políticas de organización en niveles:
+
** *Balanced (Auto)*: Introduce el número de días de enfriamiento.
** *Costo optimizado (todos)*
** *Rendimiento optimizado (solo instantáneas)*: Ingrese el número de días de enfriamiento.
** *Ninguno*


. Seleccione *aplicar*.

