---
sidebar: sidebar 
permalink: clone-volume.html 
keywords: clone volume, clone, clone data 
summary: Clone un volumen en NetApp Workload Factory para crear un volumen de lectura y escritura del volumen original para realizar pruebas. 
---
= Clonar un volumen en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Clone un volumen en NetApp Workload Factory para crear un volumen de lectura y escritura del volumen original para realizar pruebas.

El clon refleja el estado actual de un momento específico de los datos. También puede utilizar clones para proporcionar a los usuarios adicionales acceso a los datos sin tener que darles acceso a los datos de producción.

.Acerca de esta tarea
Solo se admite el clonado de volúmenes para volúmenes FlexClone.

Cuando se clona un volumen, se crea un volumen editable con referencias a las copias Snapshot del volumen principal. La creación de clones se produce en segundos. Los datos clonados no residen en el clon del volumen, sino que residen en el volumen principal. Todos los datos nuevos que se escriben en el volumen después de la creación del clon residen en el clon.

Para que un volumen clonado contenga todos los datos del volumen principal y todos los datos nuevos añadidos al clon después de su creación, deberá hacerlo link:split-cloned-volume.html["divida el clon"] a partir del volumen principal. Además, no se puede eliminar un volumen principal si tiene un clon. Debe dividir un clon para poder eliminar un volumen principal.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos FSx for ONTAP que contiene el volumen a clonar y luego seleccione *Administrar*.
. En la pestaña Descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volúmenes, seleccione el menú de acciones del volumen a clonar.
. Seleccione *Acciones de protección de datos*, luego *Clonar volumen*.
. En el cuadro de diálogo Clone volume, escriba un nombre para el clon del volumen.
. Seleccione *Clonar*.

