---
sidebar: sidebar 
permalink: configure-active-directory.html 
keywords: configure AD, configure active directory, update ad, edit active directory 
summary: Configurar y actualizar Active Directory para una máquina virtual de almacenamiento en un sistema de archivos FSx para ONTAP en NetApp Workload Factory. 
---
= Configure y actualice Active Directory para una máquina virtual de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configurar y actualizar Active Directory para una máquina virtual de almacenamiento en un sistema de archivos FSx para ONTAP en NetApp Workload Factory.

.Acerca de esta tarea
Los mismos pasos se aplican para configurar y actualizar Active Directory para una máquina virtual de almacenamiento.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con la VM de almacenamiento que desea actualizar y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, en Máquinas virtuales de almacenamiento, seleccione *Administrar*.
. Desde la pantalla Administrar máquinas virtuales de almacenamiento, seleccione el menú de acciones de la máquina virtual de almacenamiento para la que desea configurar Active Directory y, luego, seleccione *Acciones básicas* > *Administrar configuración de AD*.
. En la página Gestionar configuración de AD, proporcione lo siguiente:
+
.. *Dominio de Active Directory para unirse*: Introduzca el nombre de dominio completo (FQDN) de su Active Directory.
.. *Direcciones IP DNS*: Introduzca hasta tres direcciones IP separadas por comas.
.. *Servidor SMB Nombre NetBIOS*: Introduzca el nombre NetBIOS del servidor SMB del objeto de equipo de Active Directory para crear para su VM de almacenamiento. Este es el nombre de esta máquina virtual de almacenamiento SVM en Active Directory.
.. *Nombre de usuario*: Introduzca el nombre de usuario de la cuenta de servicio en su Active Directory existente.
+
No incluya un prefijo o sufijo de dominio. Para `EXAMPLE\ADMIN`, utilice `ADMIN`.

.. *Contraseña*: Introduzca la contraseña de la cuenta de servicio.
.. *Unidad de organización (OU)*: Ingrese la unidad de organización.
+
La unidad organizativa es el nombre de ruta de acceso distinguida de la unidad organizativa a la que desea unirse al sistema de archivos.

.. *Grupo de administradores delegados*: Opcionalmente, entra en el grupo de administradores del sistema de archivos delegado.
+
El grupo Delegated administrators es el nombre del grupo de Active Directory que puede administrar el sistema de archivos.

+
Si utiliza AWS Managed Microsoft AD, debe especificar un grupo como AWS Delegated FSx Administrators, AWS Delegated Administrators o un grupo personalizado con permisos delegados a la OU.

+
Si se está conectando a un AD autogestionado, utilice el nombre del grupo en su AD. El grupo por defecto es `Domain Admins`.



. Seleccione *aplicar*.

