---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: La fábrica de cargas de trabajo de BlueXP  analiza regularmente las configuraciones del sistema de archivos de Amazon FSx para NetApp ONTAP para determinar si hay algún problema. 
---
= Análisis de configuración para sistemas de archivos FSx para ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La fábrica de cargas de trabajo de BlueXP  analiza regularmente las configuraciones del sistema de archivos de Amazon FSx para NetApp ONTAP para determinar si hay algún problema. Cuando se encuentran los problemas, la fábrica de cargas de trabajo le muestra cuáles son los problemas y explica qué hay que cambiar para garantizar que el almacenamiento del sistema de archivos alcance el máximo rendimiento, la rentabilidad y el cumplimiento de las prácticas recomendadas.

Estas son algunas funcionalidades clave:

* Análisis diario de la configuración
* Validaciones automáticas de prácticas recomendadas
* Capacidad de observación proactiva
* Información para la acción
* Asesor de buen diseño de marco de trabajo de AWS




== Estado bien diseñado

En la consola de fábrica de cargas de trabajo, a nivel del sistema de archivos, se enumera el estado bien diseñado para todos los sistemas de archivos FSx para ONTAP. Los estados bien diseñados se clasifican como “problemas”, “no analizados” o “bien diseñados”. La selección del estado bien diseñado le redirige a la pestaña de estado bien diseñada dentro del sistema de archivos, donde puede encontrar la puntuación bien diseñada, las categorías de configuración y todas las configuraciones para el sistema de archivos.

Partitura bien diseñada:: La puntuación incluye todas las configuraciones analizadas actualmente y aparece como un porcentaje. Una puntuación del 25 % significa que el 25 % de las configuraciones del sistema de archivos tienen una arquitectura adecuada.
Categorías de configuración:: Las configuraciones del sistema de archivos se organizan en categorías alineadas con los cinco pilares siguientes del marco de AWS Well-Architected Framework.
+
--
* _Reliability_: Garantiza que las cargas de trabajo realicen sus funciones deseadas correctamente y de forma consistente, incluso cuando hay interrupciones. Un ejemplo de configuración es FSx para backups de ONTAP.
* _Seguridad_: Enfatiza la protección de datos, sistemas y activos a través de evaluaciones de riesgos y estrategias de mitigación.
* _Excelencia operativa_: Se centra en ofrecer la arquitectura y el valor empresarial más óptimos.
* _Cost optimization_: Tiene como objetivo ofrecer valor empresarial al tiempo que se minimizan los costos.
* _Performance Efficiency_: Se centra en el uso eficiente de los recursos para cumplir con los requisitos del sistema y para mantener un rendimiento óptimo a medida que cambian las demandas.


--




== Requisitos de análisis

Para un análisis completo del sistema de archivos, debe asociar un enlace. La conectividad de enlace permite a la fábrica de cargas de trabajo analizar todas las configuraciones del sistema de archivos, como la protección de datos y el rendimiento.

link:create-link.html["Aprende a crear un enlace."]

.El futuro
link:improve-configurations.html["Mejore las configuraciones para las puestas en marcha de FSx para ONTAP"]
