---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory analiza periódicamente las configuraciones del sistema de archivos Amazon FSx for NetApp ONTAP para determinar si hay algún problema. 
---
= Análisis de configuración para sistemas de archivos FSx para ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory analiza periódicamente las configuraciones del sistema de archivos Amazon FSx for NetApp ONTAP para determinar si hay algún problema.  Cuando se detectan problemas, Workload Factory le muestra cuáles son y le explica qué debe cambiar para garantizar que el almacenamiento de su sistema de archivos alcance el máximo rendimiento, rentabilidad y cumplimiento de las mejores prácticas.

Estas son algunas funcionalidades clave:

* Análisis diario de la configuración
* Validaciones automáticas de prácticas recomendadas
* Capacidad de observación proactiva
* Información para la acción
* Asesor de buen diseño de marco de trabajo de AWS




== Estado bien diseñado

En la consola de Workload Factory, en el nivel del sistema de archivos, se muestra el estado de buena arquitectura para todos los sistemas de archivos FSx para ONTAP .  Los estados bien diseñados se clasifican como "problemas", "no analizados" o "bien diseñados".  Al seleccionar el estado de buena arquitectura, se le redirige a la pestaña de estado de buena arquitectura dentro del sistema de archivos, donde puede encontrar el puntaje de buena arquitectura, las categorías de configuración y todas las configuraciones para el sistema de archivos.

Partitura bien diseñada:: La puntuación incluye todas las configuraciones analizadas actualmente y aparece como un porcentaje. Una puntuación del 25 % significa que el 25 % de las configuraciones del sistema de archivos tienen una arquitectura adecuada.
Categorías de configuración:: Las configuraciones del sistema de archivos se organizan en categorías alineadas con los cinco pilares siguientes del marco de AWS Well-Architected Framework.
+
--
* _Reliability_: Garantiza que las cargas de trabajo realicen sus funciones deseadas correctamente y de forma consistente, incluso cuando hay interrupciones. Un ejemplo de configuración es FSx para backups de ONTAP.
* _Seguridad_: Enfatiza la protección de datos, sistemas y activos a través de evaluaciones de riesgos y estrategias de mitigación.
* _Excelencia operativa_: Se centra en ofrecer la arquitectura y el valor empresarial más óptimos.
* _Cost optimization_: Tiene como objetivo ofrecer valor empresarial al tiempo que se minimizan los costos.
* _Performance Efficiency_: Se centra en el uso eficiente de los recursos para cumplir con los requisitos del sistema y para mantener un rendimiento óptimo a medida que cambian las demandas.


--




== Requisitos de análisis

Para un análisis completo del sistema de archivos, debe hacer lo siguiente:

* Asociar un enlace.  La conectividad de enlaces permite a Workload Factory analizar todas las configuraciones del sistema de archivos, como la protección de datos y el rendimiento.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"].

* Otorgue permisos de _visualización, planificación y análisis_ en su cuenta de AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Aprende a otorgar permisos a una cuenta de AWS"^]



.El futuro
link:improve-configurations.html["Implemente configuraciones de sistemas de archivos bien diseñadas"]
