---
sidebar: sidebar 
permalink: create-storage-vm.html 
keywords: create storage VM, create svm 
summary: 'Puede crear una máquina virtual de almacenamiento (SVM) FSx para ONTAP para proporcionar servicios de almacenamiento y datos para sus cargas de trabajo en NetApp Workload Factory.' 
---
= Crea una máquina virtual de almacenamiento para un sistema de archivos FSx para ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cree una máquina virtual de almacenamiento (SVM) para un sistema de archivos FSx para ONTAP para acceder virtualmente a servicios de almacenamiento y datos para sus cargas de trabajo en NetApp Workload Factory.

.Acerca de esta tarea
Las máquinas virtuales de almacenamiento son servidores de archivos aislados que puede utilizar para acceder a los datos de cada carga de trabajo en Workload Factory Storage.  Cada SVM tiene sus propias credenciales administrativas y puntos finales para administrar y acceder a los datos.

Con SVM, cuando accedes a los datos en FSx para ONTAP, tus clientes y estaciones de trabajo montan un volumen, un recurso compartido de CIFS/SMB o un LUN iSCSI alojado en una SVM mediante el extremo del SVM (dirección IP).

.Antes de empezar
Comprobar la cantidad de máquinas virtuales de almacenamiento admitida por sistema de archivos. Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gestión de máquinas virtuales de almacenamiento de FSx para ONTAP"^] en la documentación de AWS el número máximo de SVM por sistema de archivos.



== Cree una máquina virtual de almacenamiento

Puede crear una máquina virtual de almacenamiento desde la consola de Workload Factory.  También puede utilizar las siguientes herramientas disponibles en Codebox: API REST, CloudFormation y Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Aprende a usar CodeBox para la automatización"^] .


NOTE: Al usar Terraform de CodeBox, el código que copie o descargue oculta `fsxadmin` y `vsadmin` las contraseñas. Deberá volver a introducir las contraseñas cuando ejecute el código.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, en Máquinas virtuales de almacenamiento, seleccione *Crear máquina virtual de almacenamiento*.
. En la página Crear máquina virtual de almacenamiento, en Configuración de máquina virtual de almacenamiento, proporcione lo siguiente:
+
.. *Nombre*: Introduzca un nombre para la VM de almacenamiento.
.. *Credenciales de VM de almacenamiento*: Proporcione una contraseña para el usuario de esta VM de almacenamiento `vsadmin` o utilice las credenciales de usuario del sistema de archivos `fsxadmin` .
.. * Estilo de seguridad del volumen raíz*: Seleccione el estilo de seguridad del volumen raíz según el tipo de clientes que acceden a sus datos: UNIX (clientes Linux), NTFS (clientes Windows) o Mixto.
.. *Etiquetas*: Opcionalmente, puedes añadir hasta 50 etiquetas.


. Seleccione *Crear*.

