---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: Crear una política de copias Snapshot personalizada para una máquina virtual de almacenamiento en la fábrica de cargas de trabajo de BlueXP . 
---
= Crear una política de copias Snapshot para las máquinas virtuales de almacenamiento en la fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cree una política de snapshots personalizada para máquinas virtuales de almacenamiento en la fábrica de cargas de trabajo de BlueXP . Una política de Snapshot define la forma en que el sistema crea snapshots para una máquina virtual de almacenamiento. Puede crear una política de copias Snapshot para una máquina virtual de almacenamiento en un sistema de archivos FSx para ONTAP. También puede compartir la política en varios equipos virtuales de almacenamiento.

.Acerca de esta tarea
Puede crear una política de Snapshot personalizada que difiera de las tres políticas de Snapshot incorporadas para FSx para ONTAP:

* `default`
* `default-1weekly`
* `none`


De forma predeterminada, cada volumen está asociado con la política de Snapshot del sistema de archivos `default` . Recomendamos usar esta política para la mayoría de las cargas de trabajo.

La personalización de una política le permite especificar cuándo se deben crear snapshots, cuántas copias se deben conservar y cómo asignarles un nombre.

.Antes de empezar
* Una vez creada una política de Snapshot, su asociación con las máquinas virtuales de almacenamiento no puede modificarse, pero siempre puede añadir o eliminar la política de los volúmenes.
* Tenga en cuenta lo siguiente acerca de la capacidad de Snapshot antes de usar Snapshot:
+
** En la mayoría de los conjuntos de datos, una capacidad adicional del 20 % es suficiente para mantener snapshots hasta cuatro semanas. A medida que los datos envejecen, es menos probable que se utilice para restauraciones.
** La sobrescritura de todos los datos de una copia Snapshot consume una capacidad de volumen importante, lo que tiene en cuenta el aprovisionamiento de la capacidad del volumen.


* Para crear una política de instantáneas personalizada, debe asociar un vínculo. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Storage VMs*.
. En la pestaña * Storage VMs*, seleccione el menú de tres puntos para el volumen a proteger con instantáneas programadas, luego *Advanced Actions* y luego *Manage snapshot policies*.
. En la página de administración de políticas de Snapshot, seleccione *Crear política de instantáneas*.
. En el campo *Nombre de la política de instantáneas*, introduzca un nombre para la política de instantáneas.
. De forma opcional, introduzca una descripción para la política de Snapshot.
. En *Programación de políticas y copias*, seleccione cuándo crear instantáneas. Por ejemplo, cada minuto o cada hora.
+
Puede seleccionar más de una frecuencia.

. En *Número de copias*, introduzca el número de copias que desea conservar.
+
El número máximo de copias es 1.023.

. Opcional: En *convención de nomenclatura*, ingrese un *Prefijo* para la política.
. *La etiqueta de retención* se rellena automáticamente.
+
Esta etiqueta hace referencia a la etiqueta SnapMirror, o replicación que se utiliza para seleccionar solo instantáneas especificadas para la replicación del sistema de archivos de origen al de destino.

. Opcional: Habilita *instantáneas inmutables* para cualquier horario que necesites, establece el *Período de retención* para cada horario y acepta la sentencia para continuar.
+
Al habilitar snapshots inmutables, todas las snapshots de esta política de snapshots se bloquean para evitar que se eliminen durante el período de retención.

. *Compartir entre VM de almacenamiento*: Habilitado por defecto. Cuando está habilitada, la política de Snapshot se comparte en todas las máquinas virtuales de almacenamiento del sistema de archivos. Deshabilite para crear una política de snapshots para una sola máquina virtual de almacenamiento.
. Seleccione *Crear*.


.Resultado
Se ha creado la política de Snapshot.
