---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: Después de configurar su sistema de archivos FSx para ONTAP , cree volúmenes FSx para ONTAP en Workload Factory. 
---
= Cree un volumen FSx para ONTAP en Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Después de configurar su sistema de archivos FSx para ONTAP , cree volúmenes FSx para ONTAP en Workload Factory como recursos virtuales para agrupar sus datos.



== Acerca de esta tarea

Los volúmenes de FSx para ONTAP agrupan datos de manera virtual, determinan cómo se almacenan los datos y determinan el tipo de acceso a ellos. Los volúmenes no consumen capacidad de almacenamiento del sistema de archivos. Los datos que se almacenan en un volumen consumen principalmente almacenamiento SSD. Según la política de organización en niveles del volumen, los datos también pueden consumir almacenamiento en el pool de capacidad. Se establece el tamaño de un volumen al crearlo y se puede cambiar su tamaño más adelante.

Los siguientes protocolos pueden usarse para los volúmenes:

* SMB/CIFS: protocolo de almacenamiento de archivos para sistemas operativos Windows
* NFS: Protocolo de almacenamiento de ficheros para sistemas operativos Unix
* ISCSI: Protocolo de almacenamiento basado en bloques




=== Detalles de la configuración del volumen

.Archivos inmutables
Esta función, también conocida como SnapLock, está deshabilitada de forma predeterminada.  Habilitar archivos inmutables evita la eliminación o sobrescritura de datos durante un período determinado.  Habilitar esta función solo es posible durante la creación del volumen.  Una vez habilitada la función, no se puede deshabilitar.  Esta es una función premium de FSx para ONTAP que conlleva un cargo adicional.  Para obtener más información, consultelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["Cómo funciona SnapLock"^] en la documentación de Amazon FSx for NetApp ONTAP .

* *Modos de retención*: Puede seleccionar entre dos modos de retención: _Empresa_ o _Cumplimiento_.
+
** En el modo _Enterprise_, un archivo inmutable o SnapLock, el administrador puede eliminar un archivo durante su período de retención.
** En el modo _Compliance_, no se puede eliminar un archivo WORM antes de que caduque su período de retención. De igual modo, el volumen inmutable no se puede eliminar hasta que caduquen los períodos de retención de todos los archivos en el volumen.


* *Período de retención*: El período de retención tiene dos configuraciones: _política de retención_ y _períodos de retención_.  La _política de retención_ define durante cuánto tiempo se deben conservar los archivos en un estado WORM inmutable.  Puede especificar su propia política de retención o utilizar la política de retención predeterminada (no especificada), que es de 30 años.  Los _períodos de retención_ mínimo y máximo definen el rango de tiempo permitido para bloquear archivos.
+

NOTE: Incluso después de que caduque el período de retención, no es posible modificar un ARCHIVO WORM. Solo puede eliminarlo o establecer un nuevo período de retención para volver a activar la protección WORM.

* *Confirmación automática*: Tendrás la opción de habilitar la función de confirmación automática.  La función de confirmación automática confirma un archivo al estado WORM en un volumen SnapLock si el archivo no cambió durante el período de confirmación automática.  La función de confirmación automática está deshabilitada de forma predeterminada.  Debe asegurarse de que los archivos que desea confirmar automáticamente residan en un volumen SnapLock .
* *Eliminación privilegiada*: un administrador de SnapLock puede activar la eliminación privilegiada en un volumen de SnapLock Enterprise para permitir que se elimine un archivo antes de que expire el período de retención del archivo.  Esta función está deshabilitada de forma predeterminada.
* *Modo de anexión de volumen*: no se pueden modificar datos existentes en un archivo protegido con WORM.  Sin embargo, los archivos inmutables le permiten mantener la protección de los datos existentes utilizando archivos anexables mediante WORM.  Por ejemplo, puede generar archivos de registro o conservar datos de transmisión de audio o video mientras escribe datos en ellos de forma incremental. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["Obtenga más información sobre el modo de adición de volúmenes"^] en la documentación de Amazon FSx for NetApp ONTAP .




== Antes de empezar

Revise los siguientes requisitos previos antes de crear un volumen:

* Debe tener un sistema de archivos FSx para ONTAP en la consola de Workload Factory.
* Debe tener una máquina virtual de almacenamiento.
* Para acceder al protocolo, complete lo siguiente:
+
** Para configurar el acceso al volumen, debe asociar un enlace. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.
** Debe configurar el acceso para el protocolo que seleccione, ya sea SMB/CIFS, NFS o iSCSI.






== Cree un volumen

Puede crear un volumen utilizando las siguientes herramientas disponibles en CodeBox: API REST, CloudFormation y Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Aprende a usar CodeBox para la automatización"^].


NOTE: Al usar Terraform de CodeBox, el código que copie o descargue oculta `fsxadmin` y `vsadmin` las contraseñas. Deberá volver a introducir las contraseñas cuando ejecute el código.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos en el que desea crear un volumen y seleccione *Crear volumen*.
. En la página Create volume, en General details, proporcione los siguientes detalles:
+
.. *Nombre del volumen*: Introduzca un nombre para el volumen.
.. *Nombre de VM de almacenamiento*: Opcionalmente, introduzca un nombre de VM de almacenamiento.
.. *Estilo de volumen*: Selecciona el volumen *FlexVol* o *FlexGroup*.
+
El estilo de volumen FlexVol se selecciona de forma predeterminada.

+
El tamaño del volumen de FlexGroup depende de la cantidad de constituyentes y requiere 100 GiB por constituyente.

.. *Tamaño del volumen*: Introduzca el tamaño del volumen y la unidad.
+
Opcionalmente, habilite el crecimiento automático de volúmenes. Esta opción está disponible cuando selecciona *Acceso a archivos* como el tipo de acceso por volumen.

.. *Aumento automático del volumen*: Opcionalmente, active el aumento automático del volumen para ampliar automáticamente la capacidad del volumen hasta alcanzar el tamaño máximo. Esta función se adapta al aumento del uso de datos, garantizando así operaciones ininterrumpidas.
+
Especifique el tamaño máximo de crecimiento del volumen y la unidad. No se puede establecer un tamaño de crecimiento máximo menor que el tamaño del volumen actual

.. *Etiquetas*: Opcionalmente, puedes añadir hasta 50 etiquetas.


. En Acceso (sólo para sistemas de archivos con enlaces asociados), proporcione los siguientes detalles:
+
.. *Tipo de acceso*: Selecciona *Acceso a archivos* o *Acceso a bloques*. Los campos adicionales para configurar el acceso a volúmenes varían según la selección.
+
*** *Acceso a archivos*: Permite que múltiples usuarios autorizados y dispositivos accedan al volumen mediante protocolos SMB/CIFS, NFS o dual (SMB/NFS).
+
Complete los siguientes campos para configurar el acceso a archivos al volumen.



.. *Política de exportación NFS*: Proporcione los siguientes detalles para proporcionar acceso NFS:
+
... *Control de acceso*: Selecciona una *Política de exportación personalizada*, *Política de exportación existente* o *Sin acceso al volumen* en el menú desplegable.
... *Nombre de la política de exportación*:
+
Si seleccionó una política de exportación personalizada, seleccione un nombre de política existente en el menú desplegable.

+
Si seleccionó una política de exportación existente, escriba un nuevo nombre de política.

... *Agregar regla de política de exportación*: Opcionalmente, para una política de exportación personalizada, puede agregar reglas de política de exportación a la política.


.. *Recurso compartido SMB/CIFS*: proporcione lo siguiente:
+
... *Nombre*: Ingrese el nombre del recurso compartido SMB/CIFS para proporcionar acceso.
... *Permisos*: Seleccione Control total, Acceso de lectura/escritura, Lectura o Sin acceso y, a continuación, introduzca los usuarios o grupos separados por un punto y coma ( ; ). Los usuarios o grupos distinguen entre mayúsculas y minúsculas y el dominio del usuario se debe incluir con el formato “dominio\nombre de usuario”.


.. *Estilo de seguridad*: Para volúmenes de protocolo dual, seleccione el estilo de seguridad UNIX o NTFS. UNIX es el estilo de seguridad predeterminado para volúmenes de protocolo doble. Para obtener una guía detallada sobre la asignación de usuarios en este contexto, consulte el artículo del blog de AWS link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["Habilitar cargas de trabajo multiprotocolo con Amazon FSx para NetApp ONTAP"^].
+
*** *Acceso en bloque*: Permite a los hosts que ejecutan aplicaciones empresariales críticas acceder al volumen utilizando el protocolo iSCSI. El acceso en bloque solo está disponible cuando la implementación de escalado horizontal del sistema de archivos cuenta con seis pares de alta disponibilidad o menos.
+
Complete los siguientes campos para configurar el acceso en bloque al volumen.

+
.... *Configuración iSCSI*: Proporcione los siguientes detalles para configurar iSCSI para el acceso de bloques al volumen.
+
..... Seleccione *Crear un nuevo iGroup* o *Asignar un iGroup existente*.
..... Seleccione el *Sistema operativo Host* en el menú desplegable.
..... Introduzca un *Nombre de iGroup* para un nuevo iGroup.
..... En Host Initiators, añada uno o varios iniciadores de host de nombre completo de iSCSI (IQN).






.. *Punto final S3*: de manera opcional, adjunte un punto final S3 para acceder a los datos del sistema de archivos FSx for ONTAP que residen en volúmenes NFS o SMB/CIFS a través de las API de AWS S3.  Sólo se admite el tipo de acceso a archivos.  Proporcionando los siguientes detalles:
+
*** *Nombre del punto final S3*: Ingrese el nombre del punto final S3.
*** *Usuario*: Seleccione un usuario existente con acceso al volumen o cree un nuevo usuario.
*** *Tipo de usuario*: seleccione *UNIX* o *Windows* como tipo de usuario.




. En Eficiencia y protección, proporcione los siguientes detalles:
+
.. *Eficiencia de almacenamiento*: Activada por defecto. Seleccione para desactivar la función.
+
ONTAP logra eficiencia de almacenamiento utilizando funciones de deduplicación y compresión. La deduplicación elimina los bloques de datos duplicados. La compresión de datos comprime los bloques de datos para reducir la cantidad de almacenamiento físico necesaria.

.. *Política de instantáneas*: Seleccione la política de instantáneas para especificar la frecuencia y retención de instantáneas.
+
Las siguientes son políticas predeterminadas de AWS. Para las políticas de instantáneas personalizadas, debe link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["asocie un enlace"] .

+
`default`:: Esta política crea Snapshot de forma automática según la siguiente programación, siendo las copias Snapshot más antiguas eliminadas para dejar espacio para las copias más recientes:
+
--
*** Un máximo de seis instantáneas cada hora tomadas cinco minutos más allá de la hora.
*** Un máximo de dos instantáneas diarias tomadas de lunes a sábado a las 10 minutos después de la medianoche.
*** Un máximo de dos instantáneas semanales tomadas cada domingo a las 15 minutos después de la medianoche.
+

NOTE: Las horas de las instantáneas se basan en la zona horaria del sistema de archivos, que se establece de forma predeterminada en Hora universal coordinada (UTC). Para obtener información sobre cómo cambiar la zona horaria, consulte link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["Mostrar y configurar la zona horaria del sistema"^] en la documentación de soporte de NetApp.



--
`default-1weekly`:: Esta política funciona del mismo modo que la `default` política, excepto que solo conserva una copia de Snapshot de la programación semanal.
`none`:: Esta política no toma ninguna instantánea. Es posible asignar esta política a los volúmenes para evitar que se tomen Snapshot automáticas.


.. *Política de niveles*: Seleccione la política de organización en niveles para los datos almacenados en el volumen.
+
_Equilibrado (automático)_ es la política de niveles predeterminada al crear un volumen mediante la consola de Workload Factory.  Para obtener más información sobre las políticas de niveles de volumen, consultelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento del volumen"^] en la documentación de AWS FSx para NetApp ONTAP .  Tenga en cuenta que Workload Factory utiliza nombres basados ​​en casos de uso en la consola de Workload Factory para las políticas de niveles e incluye los nombres de políticas de niveles de FSx para ONTAP entre paréntesis.

.. *Archivos inmutables*: al habilitar la función de archivos inmutables, los archivos de este volumen se comprometen de forma permanente a un estado WORM (escritura única, lectura múltiple) inmutable.  Proporcione los siguientes detalles:
+
... Seleccione esta opción para habilitar *archivos inmutables con tecnología SnapLock*.
... Seleccione la casilla para aceptar y continuar.
... Selecciona *Activar*.
... *Modo de retención*: Selecciona el modo *Enterprise* o *Compliance*.
... *Período de retención*:
+
**** Seleccione la política de retención:
+
***** *Sin especificar*: Establece la política de retención a 30 años.
***** *Especifique el período*: Ingrese el número de segundos, minutos, horas, días, meses o años para establecer su propia política de retención.


**** Seleccione los períodos de retención mínimo y máximo:
+
***** *Mínimo*: Introduzca el número de segundos, minutos, horas, días, meses o años para establecer el período de retención mínimo.
***** *Máximo*: Introduzca el número de segundos, minutos, horas, días, meses o años para establecer el período de retención máximo.




... *Autocommit*: Desactiva o activa la autocommit. Si habilita la confirmación automática, establezca el período de compromiso automático.
... *Eliminación privilegiada*: Deshabilitar o habilitar.  Si habilita la eliminación privilegiada, un administrador de SnapLock puede eliminar un archivo antes de que expire su período de retención.
... *Modo de adición de volumen*: Desactivar o activar. Permite agregar nuevo contenido a archivos WORM.


.. *ARP/AI*: La protección autónoma contra ransomware con IA (ARP/AI) de NetApp está habilitada de forma predeterminada cuando un vínculo está asociado con el sistema de archivos. link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Obtenga más información sobre ARP/AI"]. Acepte la sentencia para continuar.
+
Si la función no está disponible, se debe a una de las siguientes razones:

+
*** Un enlace no está asociado con el sistema de archivos. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.
*** Los volúmenes con archivos inmutables y los volúmenes con protocolos iSCSI y NVMe no son compatibles con ARP/AI.
*** El sistema de archivos ya tiene una política ARP/AI.




. En Configuración avanzada, proporcione lo siguiente:
+
.. *Ruta de unión*: Introduzca la ubicación en el espacio de nombres de la VM de almacenamiento donde se monta el volumen. La ruta de unión predeterminada es `/<volume-name>`.
.. *Lista de agregados*: Solo para volúmenes FlexGroup. Añada o quite agregados. El número mínimo de agregados es uno.
.. *Número de constituyentes*: Solo para volúmenes FlexGroup. Introduzca el número de componentes por agregado. Se requiere 100 GiB por componente.


. Seleccione *Crear*.


.Resultado
La fábrica de cargas de trabajo inicia la creación del volumen. Una vez creado, el sistema muestra el nuevo volumen en la pestaña Volúmenes.
