---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: Después de configurar su sistema de archivos FSx para ONTAP, cree volúmenes FSx para ONTAP en la fábrica de carga de trabajo. 
---
= Cree un volumen FSx para ONTAP en la fábrica de carga de trabajo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Después de configurar su sistema de archivos FSx para ONTAP, cree volúmenes FSx para ONTAP en la fábrica de carga de trabajo como recursos virtuales para agrupar sus datos.

.Acerca de esta tarea
Los volúmenes de FSx para ONTAP agrupan datos de manera virtual, determinan cómo se almacenan los datos y determinan el tipo de acceso a ellos. Los volúmenes no consumen capacidad de almacenamiento del sistema de archivos. Los datos que se almacenan en un volumen consumen principalmente almacenamiento SSD. Según la política de organización en niveles del volumen, los datos también pueden consumir almacenamiento en el pool de capacidad. Se establece el tamaño de un volumen al crearlo y se puede cambiar su tamaño más adelante.

Los siguientes protocolos pueden usarse para los volúmenes:

* CIFS: Protocolo de almacenamiento de ficheros para sistemas operativos Windows
* NFS: Protocolo de almacenamiento de ficheros para sistemas operativos Unix
* ISCSI: Protocolo de almacenamiento basado en bloques


.Antes de empezar
Revise los siguientes requisitos previos antes de crear un volumen:

* Debe tener un sistema de archivos FSx for ONTAP en la fábrica de cargas de trabajo.
* Debe tener una máquina virtual de almacenamiento.
* Para acceder al protocolo, complete lo siguiente:
+
** Para configurar el acceso al volumen, debe asociar un enlace. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.
** Tiene que configurar el acceso para el protocolo que seleccione, ya sea CIFS, NFS o iSCSI.






== Cree un volumen

Puede crear un volumen utilizando las siguientes herramientas disponibles en CodeBox: API REST, CloudFormation y Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Aprende a usar CodeBox para la automatización"^].


NOTE: Al usar Terraform de CodeBox, el código que copie o descargue oculta `fsxadmin` y `vsadmin` las contraseñas. Deberá volver a introducir las contraseñas cuando ejecute el código.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos en el que quieres crear un volumen y selecciona *Crear volumen*.
. En la página Create volume, en General details, proporcione los siguientes detalles:
+
.. *Nombre del volumen*: Introduzca un nombre para el volumen.
.. *Nombre de VM de almacenamiento*: Opcionalmente, introduzca un nombre de VM de almacenamiento.
.. *Estilo de volumen*: Selecciona el volumen *FlexVol* o *FlexGroup*.
+
El estilo de volumen FlexVol se selecciona de forma predeterminada.

+
El tamaño del volumen de FlexGroup depende del número de componentes. Se requiere 100 GiB por componente.

.. *Tamaño del volumen*: Introduzca el tamaño del volumen y la unidad.
+
Opcionalmente, habilite el crecimiento automático de volúmenes. Esta opción está disponible cuando selecciona *Acceso a archivos* como el tipo de acceso por volumen.

.. *Aumento automático del volumen*: Opcionalmente, active el aumento automático del volumen para ampliar automáticamente la capacidad del volumen hasta alcanzar el tamaño máximo. Esta función se adapta al aumento del uso de datos, garantizando así operaciones ininterrumpidas.
+
Especifique el tamaño máximo de crecimiento del volumen y la unidad. El tamaño máximo de crecimiento no puede ser menor que el tamaño actual del volumen.

.. *Etiquetas*: Opcionalmente, puedes añadir hasta 50 etiquetas.


. En Acceso (sólo para sistemas de archivos con enlaces asociados), proporcione los siguientes detalles:
+
.. *Tipo de acceso*: Selecciona *Acceso a archivos* o *Acceso a bloques*. Los campos adicionales para configurar el acceso a volúmenes varían según la selección.
+
*** *Acceso a archivos*: Permite que múltiples usuarios autorizados y dispositivos accedan al volumen mediante protocolos SMB/CIFS, NFS o dual (SMB/NFS).
+
Complete los siguientes campos para configurar el acceso a archivos al volumen.

+
.... *Política de exportación NFS*: Proporcione los siguientes detalles para proporcionar acceso NFS:
+
..... *Control de acceso*: Selecciona una *Política de exportación personalizada*, *Política de exportación existente* o *Sin acceso al volumen* en el menú desplegable.
..... *Nombre de la política de exportación*:
+
Si seleccionó una política de exportación personalizada, seleccione un nombre de política existente en el menú desplegable.

+
Si seleccionó una política de exportación existente, escriba un nuevo nombre de política.

..... *Agregar regla de política de exportación*: Opcionalmente, para una política de exportación personalizada, puede agregar reglas de política de exportación a la política.


.... *CIFS Share*: Proporciona lo siguiente:
+
..... *Nombre*: Introduzca el nombre del recurso compartido CIFS para proporcionar acceso SMB.
..... *Permisos*: Seleccione Control total, Acceso de lectura/escritura, Lectura o Sin acceso y, a continuación, introduzca los usuarios o grupos separados por un punto y coma ( ; ). Los usuarios o grupos distinguen entre mayúsculas y minúsculas y el dominio del usuario se debe incluir con el formato “dominio\nombre de usuario”.


.... *Estilo de seguridad*: Para volúmenes de protocolo dual, seleccione el estilo de seguridad UNIX o NTFS. UNIX es el estilo de seguridad predeterminado para volúmenes de protocolo doble. Para obtener una guía detallada sobre la asignación de usuarios en este contexto, consulte el artículo del blog de AWS link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["Habilitar cargas de trabajo multiprotocolo con Amazon FSx para NetApp ONTAP"^].


*** *Acceso en bloque*: Permite a los hosts que ejecutan aplicaciones empresariales críticas acceder al volumen utilizando el protocolo iSCSI. El acceso en bloque solo está disponible cuando la implementación de escalado horizontal del sistema de archivos cuenta con seis pares de alta disponibilidad o menos.
+
Complete los siguientes campos para configurar el acceso en bloque al volumen.

+
.... *Configuración iSCSI*: Proporcione los siguientes detalles para configurar iSCSI para el acceso de bloques al volumen.
+
..... Seleccione *Crear un nuevo iGroup* o *Asignar un iGroup existente*.
..... Seleccione el *Sistema operativo Host* en el menú desplegable.
..... Introduzca un *Nombre de iGroup* para un nuevo iGroup.
..... En Host Initiators, añada uno o varios iniciadores de host de nombre completo de iSCSI (IQN).








. En Eficiencia y protección, proporcione los siguientes detalles:
+
.. *Eficiencia de almacenamiento*: Activada por defecto. Seleccione para desactivar la función.
+
La eficiencia del almacenamiento se logra utilizando las funciones de deduplicación y compresión de ONTAP. La deduplicación elimina los bloques de datos duplicados. La compresión de datos comprime los bloques de datos para reducir la cantidad de almacenamiento físico necesaria.

.. *Archivos inmutables*: Esta función, también conocida como SnapLock, está desactivada por defecto. La habilitación de archivos inmutables impide que se eliminen o sobrescriban los datos durante un periodo de tiempo determinado. Habilitar esta función solo es posible durante la creación del volumen. Una vez habilitada la función, no puede deshabilitarse. Esta es una función premium de FSx para ONTAP que tiene un coste adicional. Para obtener más información, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["Cómo funciona SnapLock"^]en la documentación de Amazon FSx para NetApp ONTAP.
+
Al habilitar la función de archivos inmutables, los archivos de este volumen se confirman de forma permanente en un estado WORM inmutable (escritura única lectura múltiple).

+
Modos de retención:: Puede seleccionar entre dos modos de retención: _Enterprise_ o _Compliance_.
+
--
*** En el modo _Enterprise_, un archivo inmutable o SnapLock, el administrador puede eliminar un archivo durante su período de retención.
*** En el modo _Compliance_, no se puede eliminar un archivo WORM antes de que caduque su período de retención. De igual modo, el volumen inmutable no se puede eliminar hasta que caduquen los períodos de retención de todos los archivos en el volumen.


--
Período de retención:: El período de retención tiene dos valores: _Retention policy_ y _retention period_. La _retention policy_ define cuánto tiempo se retendrán los archivos en un estado WORM inmutable. Puede especificar su propia política de retención o utilizar la política de retención predeterminada (no especificada), que es de 30 años. Los periodos de retención mínimo y máximo definen el intervalo de tiempo permitido para bloquear archivos.
+
--
NOTA:: Incluso después de que caduque el período de retención, no es posible modificar un ARCHIVO WORM. Solo puede eliminarlo o establecer un nuevo período de retención para volver a activar la protección WORM.


--
Confirmación automática:: Tendrá la opción de activar la función de confirmación automática. La función de compromiso automático confirma un archivo en estado WORM en un volumen SnapLock si el archivo no cambió durante el período de compromiso automático. La función de compromiso automático está deshabilitada de forma predeterminada. Los archivos que desea confirmar automáticamente deben residir en un volumen de SnapLock.
Modo de adición de volúmenes:: No es posible modificar los datos existentes en un archivo protegido CON WORM. Sin embargo, los archivos inmutables le permiten conservar la protección de los datos existentes con archivos que se pueden agregar con WORM. Por ejemplo, puede generar archivos de registro o conservar datos de transmisión de audio o vídeo mientras escribe datos en ellos de forma incremental. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["Obtenga más información sobre el modo de adición de volúmenes"^] En documentación de Amazon FSx para NetApp ONTAP.
+
--
.Pasos para archivos inmutables
... Seleccione esta opción para habilitar *archivos inmutables con tecnología SnapLock*.
... Seleccione la casilla para aceptar y continuar.
... Selecciona *Activar*.
... *Modo de retención*: Selecciona el modo *Enterprise* o *Compliance*.
... *Período de retención*:
+
**** Seleccione la política de retención:
+
***** *Sin especificar*: Establece la política de retención a 30 años.
***** *Especifique el período*: Ingrese el número de segundos, minutos, horas, días, meses o años para establecer su propia política de retención.


**** Seleccione los períodos de retención mínimo y máximo:
+
***** *Mínimo*: Introduzca el número de segundos, minutos, horas, días, meses o años para establecer el período de retención mínimo.
***** *Máximo*: Introduzca el número de segundos, minutos, horas, días, meses o años para establecer el período de retención máximo.




... *Autocommit*: Desactiva o activa la autocommit. Si habilita la confirmación automática, establezca el período de compromiso automático.
... *Modo de adición de volumen*: Desactivar o activar. Permite agregar nuevo contenido a archivos WORM.


--


.. *Política de instantáneas*: Seleccione la política de instantáneas para especificar la frecuencia y retención de instantáneas.
+
Las siguientes son políticas predeterminadas de AWS. Para las políticas de instantáneas personalizadas, debe link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["asocie un enlace"] .

+
`default`:: Esta política crea Snapshot de forma automática según la siguiente programación, siendo las copias Snapshot más antiguas eliminadas para dejar espacio para las copias más recientes:
+
--
*** Un máximo de seis instantáneas cada hora tomadas cinco minutos más allá de la hora.
*** Un máximo de dos instantáneas diarias tomadas de lunes a sábado a las 10 minutos después de la medianoche.
*** Un máximo de dos instantáneas semanales tomadas cada domingo a las 15 minutos después de la medianoche.
+

NOTE: Las horas de las instantáneas se basan en la zona horaria del sistema de archivos, que se establece de forma predeterminada en Hora universal coordinada (UTC). Para obtener información sobre cómo cambiar la zona horaria, consulte link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["Mostrar y configurar la zona horaria del sistema"^] en la documentación de soporte de NetApp.



--
`default-1weekly`:: Esta política funciona del mismo modo que la `default` política, excepto que solo conserva una copia de Snapshot de la programación semanal.
`none`:: Esta política no toma ninguna instantánea. Es posible asignar esta política a los volúmenes para evitar que se tomen Snapshot automáticas.


.. *Política de niveles*: Seleccione la política de organización en niveles para los datos almacenados en el volumen.
+
_Balanced (Auto)_ es la política de organización en niveles predeterminada al crear un volumen con la consola de cargas de trabajo de fábrica. Para obtener más información sobre las políticas de organización en niveles de volúmenes, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento del volumen"^] la documentación de AWS FSx para NetApp ONTAP. Tenga en cuenta que la fábrica de carga de trabajo utiliza nombres basados en casos de uso en la consola de fábrica de cargas de trabajo para las políticas de organización en niveles e incluye los nombres de las políticas de organización en niveles de FSx para ONTAP entre paréntesis.



. En Configuración avanzada, proporcione lo siguiente:
+
.. *Ruta de unión*: Introduzca la ubicación en el espacio de nombres de la VM de almacenamiento donde se monta el volumen. La ruta de unión predeterminada es `/<volume-name>`.
.. *Lista de agregados*: Solo para volúmenes FlexGroup. Añada o quite agregados. El número mínimo de agregados es uno.
.. *Número de constituyentes*: Solo para volúmenes FlexGroup. Introduzca el número de componentes por agregado. Se requiere 100 GiB por componente.


. Seleccione *Crear*.


.Resultado
Se inicia la creación del volumen. Una vez creado, el nuevo volumen aparecerá en la pestaña Volumes.
