---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: Cree una instantánea manual de un volumen FSx para ONTAP en NetApp Workload Factory.  Las instantáneas son versiones puntuales del contenido de su volumen. 
---
= Cree una snapshot manual de un volumen de FSx para ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cree una instantánea manual de un volumen FSx para ONTAP en NetApp Workload Factory.  Las instantáneas son versiones puntuales del contenido de su volumen.

Las Snapshot son recursos de volúmenes y son capturas instantáneas de los datos que solo consumen espacio para los datos modificados. Debido a que los datos cambian con el tiempo, las snapshots suelen consumir más espacio a medida que envejecen.

FSX para volúmenes de ONTAP utiliza la copia puntual en escritura, de modo que cualquier archivo sin modificar en las copias snapshot no consuma ninguna capacidad del volumen.


NOTE: Las copias Snapshot no son copias de sus datos. Si desea hacer copias de sus datos, considere la posibilidad de utilizar las funciones de replicación de volúmenes o backups de FSx para ONTAP.

.Antes de empezar
Debe asociar un enlace para crear una instantánea manual de un volumen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos que contiene el volumen para el cual se creará una instantánea y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña *Volúmenes*, seleccione el menú de acciones para el volumen que desea proteger con instantáneas.
. Seleccione *Acciones de protección de datos* y luego *Administrar instantáneas*.
. Desde la página Administrar instantáneas, seleccione *Crear instantánea*.
. En el cuadro de diálogo Crear una instantánea, haga lo siguiente:
+
.. Introduzca un nombre para la instantánea en el campo *Nombre de la instantánea*.
.. Opcionalmente, seleccione una etiqueta o cree una nueva etiqueta.
.. Establezca el *Período de retención* como un número de horas, días, meses o años.
.. Opcional: *Hacer que esta instantánea sea inmutable* para evitar que se elimine durante el período de retención.
+
Acepte la declaración sobre instantáneas inmutables.



. Seleccione *Crear*.

