---
sidebar: sidebar 
permalink: create-replication.html 
keywords: replication, replicate 
summary: Crea una relación de replicación para un sistema de archivos FSx para ONTAP para evitar la pérdida de datos en caso de un desastre imprevisto. 
---
= Crea una relación de replicación en la fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crea una relación de replicación para un sistema de archivos FSx para ONTAP en el fábrica de cargas de trabajo de BlueXP  para evitar la pérdida de datos en caso de un desastre imprevisto.

.Acerca de esta tarea
La replicación es una capa adicional de protección de datos que es esencial en caso de que la región en la que residen los datos experimente un desastre. La pérdida de datos puede evitarse si se utiliza replicación entre regiones.

Esta operación crea una relación de replicación para uno o todos los volúmenes de origen en un sistema de archivos FSx para ONTAP.

Los volúmenes replicados en el sistema de archivos de destino siguen el formato de nomenclatura: `{OriginalVolumeName}_copy`.

.Antes de empezar
Asegúrese de cumplir con los siguientes requisitos previos antes de comenzar.

* Debe tener dos sistemas de archivos disponibles en el inventario de almacenamiento para crear una relación de replicación.
* Los dos sistemas de archivos que se utilizan para la relación de replicación deben tener un enlace asociado. Si los sistemas de archivos no tienen enlaces existentes, link:create-link.html["primero crea un enlace"]. link:manage-links.html["asocie un enlace"]En los sistemas de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Una vez que el enlace se asocia en ambos sistemas de archivos, vuelva a esta operación.


Complete los siguientes pasos para replicar un único volumen o replicar todos los volúmenes en un sistema de archivos.

[role="tabbed-block"]
====
.Replicación de un único volumen
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos que contiene el volumen a replicar y luego selecciona *Administrar*.
. En la pestaña Volumes, seleccione el menú de tres puntos del volumen que desea replicar.
. Seleccione *Acciones de protección de datos* y luego *Replicar datos de volumen*.
. En la página Create replication, en Replication target, proporcione lo siguiente:
+
.. *FSX para el sistema de archivos ONTAP*: Seleccione credenciales, región y FSX para el nombre del sistema de archivos ONTAP para el sistema de archivos FSX para ONTAP de destino.
.. *Nombre de VM de almacenamiento*: Seleccione la VM de almacenamiento en el menú desplegable.
.. *Nombre del volumen*: El nombre del volumen de destino se genera automáticamente con el siguiente formato `{OriginalVolumeName}_copy`. Se puede usar el nombre de volumen generado automáticamente o introducir otro nombre de volumen.
.. *Política de niveles*: Seleccione la política de organización en niveles para los datos almacenados en el volumen de destino.
+
_Auto_ es la política de organización en niveles predeterminada al crear un volumen mediante la interfaz de usuario de FSx para ONTAP de la fábrica de cargas de trabajo. Para obtener más información sobre las políticas de organización en niveles de volúmenes, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento del volumen"^]la documentación de AWS FSx para NetApp ONTAP.

.. *Tasa de transferencia máxima*: Selecciona *Limited* e introduce el límite máximo de transferencia en MB/s.. Alternativamente, selecciona *Ilimitado*.
+
Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir. También recomendamos una tasa de transferencia ilimitada para los sistemas de archivos de FSx for ONTAP para cargas de trabajo cruciales; por ejemplo, aquellas que se usan principalmente para la recuperación ante desastres.



. En Configuración de replicación, proporcione lo siguiente:
+
.. *Intervalo de replicación*: Seleccione la frecuencia con la que se transfieren las instantáneas del volumen de origen al volumen de destino.
.. *Retención a largo plazo*: Opcionalmente, habilita instantáneas para la retención a largo plazo.
+
Si habilita la retención a largo plazo, seleccione una política existente o cree una nueva política para definir las snapshots que se replicarán y el número que se retendrá.

+
... Para *Elige una política existente*, selecciona una política existente en el menú desplegable.
... Para *Crear una nueva política*, proporcione lo siguiente:
+
.... *Nombre de la política*: Introduzca un nombre de política.
.... *Políticas de instantáneas*: En la tabla, seleccione la frecuencia de la política de instantáneas y el número de copias que se deben retener. Puede seleccionar más de una política de Snapshot.






. Seleccione *Crear*.


--
.Replicar todos los volúmenes en un sistema de archivos
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña FSX para ONTAP, seleccione el menú de tres puntos del sistema de archivos con los volúmenes y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, seleccione *Crear replicación*.
. En la página Create replication, en Replication target, proporcione lo siguiente:
+
.. *FSX para el sistema de archivos ONTAP*: Seleccione credenciales, región y FSX para el nombre del sistema de archivos ONTAP para el sistema de archivos FSX para ONTAP de destino.
.. *Nombre de VM de almacenamiento*: Seleccione la VM de almacenamiento en el menú desplegable.
.. *Nombre del volumen*: El nombre del volumen de destino se genera automáticamente con el siguiente formato `{OriginalVolumeName}_copy`.
.. *Política de niveles*: Seleccione la política de organización en niveles para los datos almacenados en el volumen de destino.
+
_Auto_ es la política de organización en niveles predeterminada al crear un volumen mediante la interfaz de usuario de FSx para ONTAP de la fábrica de cargas de trabajo. Para obtener más información sobre las políticas de organización en niveles de volúmenes, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento del volumen"^]la documentación de AWS FSx para NetApp ONTAP.

.. *Tasa de transferencia máxima*: Selecciona *Limited* e introduce el límite máximo de transferencia en MB/s.. Alternativamente, selecciona *Ilimitado*.
+
Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir. También recomendamos una tasa de transferencia ilimitada para los sistemas de archivos de FSx for ONTAP para cargas de trabajo cruciales; por ejemplo, aquellas que se usan principalmente para la recuperación ante desastres.



. En Configuración de replicación, proporcione lo siguiente:
+
.. *Intervalo de replicación*: Seleccione la frecuencia con la que se transfieren las instantáneas del volumen de origen al volumen de destino.
.. *Retención a largo plazo*: Opcionalmente, habilita instantáneas para la retención a largo plazo.
+
Si habilita la retención a largo plazo, seleccione una política existente o cree una nueva política para definir las snapshots que se replicarán y el número que se retendrá.

+
... Para *Elige una política existente*, selecciona una política existente en el menú desplegable.
... Para *Crear una nueva política*, proporcione lo siguiente:
+
.... *Nombre de la política*: Introduzca un nombre de política.
.... *Políticas de instantáneas*: En la tabla, seleccione la frecuencia de la política de instantáneas y el número de copias que se deben retener. Puede seleccionar más de una política de Snapshot.






. Seleccione *Crear*.


--
====
.Resultado
La relación de replicación aparece en la pestaña *Relaciones de replicación*.
