---
sidebar: sidebar 
permalink: delete-file-system.html 
keywords: file system, delete file system, file system deletion 
summary: Para eliminar un sistema de archivos en la fábrica de cargas de trabajo BlueXP , primero debe eliminar todos los volúmenes, las máquinas virtuales de almacenamiento o las relaciones de replicación asociadas con el sistema de archivos. 
---
= Eliminar un sistema de archivos en la fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para eliminar un sistema de archivos en la fábrica de cargas de trabajo BlueXP , primero debe eliminar todos los volúmenes, las máquinas virtuales de almacenamiento o las relaciones de replicación asociadas con el sistema de archivos.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos FSX for ONTAP que deseas eliminar.
. Seleccione *gestionar*.
. En la pestaña *Overview*, seleccione el menú de tres puntos.
. Seleccione *Eliminar*.
. En el cuadro de diálogo Eliminar FSX para el sistema de archivos ONTAP, introduzca el nombre del sistema de archivos FSx para ONTAP que desea eliminar.
. Seleccione *Eliminar*.

