---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Elimina una máquina virtual de almacenamiento (SVM) que ya no necesitas de una configuración del sistema de archivos FSx para ONTAP.' 
---
= Eliminar una máquina virtual de almacenamiento en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Elimina una máquina virtual de almacenamiento (SVM) que ya no necesitas de una configuración del sistema de archivos FSx para ONTAP.

.Antes de empezar
Revise lo siguiente antes de eliminar una máquina virtual de almacenamiento:

* Asegúrese de que ninguna aplicación esté accediendo a los datos en la SVM.
* Elimine todos los volúmenes que no son raíz conectados a la SVM.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos a actualizar y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, en Máquinas virtuales de almacenamiento, seleccione *Administrar*.
. En la pantalla Administrar máquinas virtuales de almacenamiento, seleccione el menú de acciones de la máquina virtual de almacenamiento que desea eliminar.
. Seleccione *Eliminar VM de almacenamiento*.
. En el cuadro de diálogo Delete storage VM, escriba «delete» para eliminar la máquina virtual de almacenamiento.
. Seleccione *Eliminar* para confirmar.

