---
sidebar: sidebar 
permalink: delete-volume.html 
keywords: delete volume, volume deletion 
summary: Puede eliminar un volumen en su sistema de archivos FSx para ONTAP en cualquier momento. Esta operación es irreversible. 
---
= Elimine un volumen en la fábrica de carga de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puede eliminar un volumen en su sistema de archivos FSx para ONTAP en cualquier momento. Esta operación es irreversible.

.Antes de empezar
Considere lo siguiente antes de eliminar un volumen:

* Relaciones de replicación: Debe link:delete-replication.html["suprimir todas las relaciones de replicación existentes"] para este volumen antes de eliminar el volumen para que no se queden relaciones rotas.
* Snapshots locales: Todas las snapshots asociadas con este sistema de archivos FSx para ONTAP se eliminarán de forma permanente.
* FSX para backup de ONTAP: Permanecerán las copias de backup de FSx para ONTAP y aún podrás utilizarlas.
* Archivos inmutables: Los volúmenes que contienen archivos inmutables con tecnología SnapLock no se pueden eliminar hasta que caduque el período de retención.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, seleccione el menú de tres puntos del sistema de archivos con el volumen que desea eliminar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volumes, seleccione el menú de tres puntos del volumen que desea eliminar.
. Seleccione *Acciones básicas* y luego *Eliminar volumen*.
. En el cuadro de diálogo Delete volume, realice lo siguiente:
+
.. Opcionalmente, seleccione *Realizar una copia de seguridad del volumen* para hacer una copia de seguridad del volumen antes de la eliminación.
+
La copia de seguridad permanecerá en el sistema de archivos hasta que la elimine manualmente.

.. Seleccione *continuar*.
.. Escriba «delete» para eliminar el volumen.
.. Seleccione *Eliminar*.



