---
sidebar: sidebar 
permalink: delete-replication.html 
keywords: delete replication 
summary: Elimine una relación de replicación en NetApp Workload Factory según sea necesario. 
---
= Eliminar una relación de replicación en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Eliminar una relación de replicación en NetApp Workload Factory.  Cuando se elimina una relación de replicación, se elimina la relación de replicación entre el volumen de origen y el de destino.  Una vez eliminada la relación de replicación, ambos volúmenes continúan existiendo independientemente con los datos actuales que contienen.

Al eliminar una relación de replicación, FSx para ONTAP también elimina las snapshots de replicación comunes del volumen de origen y del volumen de destino.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos a actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, seleccione el menú de acciones de la relación de replicación que desea eliminar.
. Seleccione *Eliminar*.
. En el cuadro de diálogo Eliminar relación, seleccione *Eliminar*.

