---
sidebar: sidebar 
permalink: delete-volume.html 
keywords: delete volume, volume deletion 
summary: Elimina un volumen en tu sistema de archivos FSx para ONTAP que ya no sea necesario y para liberar espacio. Esta operación es irreversible. 
---
= Eliminar un volumen en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Elimina un volumen en tu sistema de archivos FSx para ONTAP que ya no sea necesario y para liberar espacio. Esta operación es irreversible.

.Antes de empezar
Considere lo siguiente antes de eliminar un volumen:

* Relaciones de replicación: Debe link:delete-replication.html["suprimir todas las relaciones de replicación existentes"] para este volumen antes de eliminar el volumen para que no se queden relaciones rotas.
* Snapshots locales: Todas las snapshots asociadas con este sistema de archivos FSx para ONTAP se eliminarán de forma permanente.
* FSX para backup de ONTAP: Permanecerán las copias de backup de FSx para ONTAP y aún podrás utilizarlas.
* Copias Snapshot y archivos inmutables: Los volúmenes que contienen archivos inmutables y copias Snapshot no se pueden eliminar hasta que finalice el período de retención.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el actionsenu del sistema de archivos con el volumen que desea eliminar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña Volúmenes, seleccione el menú de acciones del volumen que desea eliminar.
. Seleccione *Acciones básicas* y luego *Eliminar volumen*.
. En el cuadro de diálogo Delete volume, realice lo siguiente:
+
.. Opcionalmente, seleccione *Realizar una copia de seguridad del volumen* para hacer una copia de seguridad del volumen antes de la eliminación.
+
La copia de seguridad permanecerá en el sistema de archivos hasta que la elimine manualmente.

.. Seleccione *continuar*.
.. Escriba «delete» para eliminar el volumen.
.. Seleccione *Eliminar* para confirmar.



