---
sidebar: sidebar 
permalink: delete-file-system.html 
keywords: file system, delete file system, file system deletion 
summary: Para eliminar un sistema de archivos en NetApp Workload Factory, primero debe eliminar todos los volúmenes, las máquinas virtuales de almacenamiento o las relaciones de replicación asociadas con el sistema de archivos. 
---
= Eliminar un sistema de archivos en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para eliminar un sistema de archivos en NetApp Workload Factory, primero debe eliminar todos los volúmenes, las máquinas virtuales de almacenamiento o las relaciones de replicación asociadas con el sistema de archivos.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos FSx for ONTAP que desea eliminar.
. Seleccione *gestionar*.
. En la pestaña *Descripción general*, seleccione el menú de acciones.
. Seleccione *Eliminar*.
. En el cuadro de diálogo Eliminar FSX para el sistema de archivos ONTAP, introduzca el nombre del sistema de archivos FSx para ONTAP que desea eliminar.
. Seleccione *Eliminar* para confirmar.

