---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: Habilite el crecimiento automático de volúmenes para que las cargas de trabajo de BlueXP  gestionen la capacidad de los volúmenes a su medida. Puede deshabilitarla en cualquier momento. 
---
= Habilite el crecimiento automático de volúmenes en el centro de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Habilite el crecimiento automático de volúmenes para que las cargas de trabajo de BlueXP  gestionen la capacidad de los volúmenes a su medida. Puede deshabilitarla en cualquier momento.

Opcionalmente, es posible aumentar manualmente la capacidad del volumen de un volumen en cualquier momento mediante el link:increase-volume-capacity.html["función aumentar capacidad del volumen"].


NOTE: No se admite el crecimiento automático de volúmenes para los volúmenes iSCSI.

.Antes de empezar
Para habilitar el crecimiento automático de volúmenes, link:manage-links.html["asocie un enlace"]debe . Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Una vez asociado el enlace, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña FSX para ONTAP, seleccione el menú de tres puntos del sistema de archivos con el volumen que desea actualizar y, a continuación, seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volumes, seleccione el menú de tres puntos para el volumen que desea modificar.
. Selecciona *Acciones básicas*, luego *Editar crecimiento automático del volumen*.
. En el cuadro de diálogo Edit autogrow, habilite el crecimiento automático de volúmenes.
. Seleccione *aplicar*.

