---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: Habilite el crecimiento automático del volumen para permitir que Workload Factory administre la capacidad del volumen por usted.  Puedes desactivarlo en cualquier momento. 
---
= Habilitar el crecimiento automático del volumen en Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Habilite el crecimiento automático del volumen para permitir que Workload Factory administre la capacidad del volumen por usted.  Puedes desactivarlo en cualquier momento.

Opcionalmente, puede aumentar manualmente la capacidad de volumen de un volumen en cualquier momento utilizando lalink:adjust-volume-capacity.html["Función de ajuste de capacidad de volumen"] .


NOTE: No se admite el crecimiento automático de volúmenes para los volúmenes iSCSI.

.Antes de empezar
Para habilitar el crecimiento automático del volumen, debe asociar un enlace. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con el volumen a actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña Volúmenes, seleccione el menú de acciones del volumen que desea modificar.
. Seleccione *Acciones básicas* y luego *Establecer crecimiento automático del volumen*.
. En el cuadro de diálogo "Configurar crecimiento automático", habilite el crecimiento automático del volumen para expandir automáticamente la capacidad del volumen hasta que alcance su tamaño máximo. Esta función se adapta al aumento del uso de datos, garantizando así operaciones ininterrumpidas.
+
Especifique el tamaño máximo de crecimiento del volumen y la unidad. El tamaño máximo de crecimiento no puede ser menor que el tamaño actual del volumen.

. Seleccione *aplicar*.

