---
sidebar: sidebar 
permalink: enable-snapshots-long-term.html 
keywords: snapshot long-term retention, enable long-term retention 
summary: Cambie la programación de replicación del volumen de origen en una relación de replicación. 
---
= Habilite y edite snapshots para retención a largo plazo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Habilitar snapshots para la retención a largo plazo le permite replicar snapshots concretos para una recuperación ante desastres a largo plazo.

La retención a largo plazo permite que los servicios empresariales continúen funcionando incluso si se produce un fallo completo del sitio, compatible con la conmutación por error de forma transparente mediante una copia secundaria.

Los mismos pasos se aplican para habilitar y editar copias Snapshot para una retención a largo plazo.

.Pasos
. Inicie sesión en la consola de Workload Factory.
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, haz clic en el menú de tres puntos del sistema de archivos para actualizar y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, haga clic en el menú de tres puntos de la programación de la relación de replicación que desea cambiar.
. Seleccione *Editar retención a largo plazo*.
. En el cuadro de diálogo Editar retención a largo plazo, habilite o deshabilite instantáneas para retención a largo plazo.
. Si selecciona desactivar las instantáneas para la retención a largo plazo, haga clic en *Aplicar* para completar esta operación.
. Si selecciona habilitar Snapshot para la retención a largo plazo, elija entre seleccionar una política existente o crear una nueva.
+
.. Para una política existente, seleccione una política existente del menú desplegable.
.. Para crear una nueva política, proporcione lo siguiente:
+
... *Nombre de la política*: Introduzca un nombre de política.
... *Políticas de instantáneas*: Seleccione una o más políticas de instantáneas.
... *Copias para retener*: Introduzca el número de copias instantáneas que se deben conservar en el sistema de archivos de destino.




. Haga clic en *aplicar*.

