---
sidebar: sidebar 
permalink: explore-savings.html 
keywords: cost, savings, compare costs, EBS, EFS, FSx for Windows file servers FSx for ONTAP 
summary: 'Explora el ahorro en tus cargas de trabajo de almacenamiento en el almacenamiento de Amazon Elastic Block Store (EBS), Elastic File System (EFS) y FSx para servidores de archivos de Windows frente a AWS FSx para NetApp ONTAP.' 
---
= Explora el ahorro con FSx para ONTAP en la fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubre el ahorro en las cargas de trabajo de almacenamiento que usan Amazon Elastic Block Store (EBS), Elastic File System (EFS) y FSx para servidor de archivos de Windows frente a FSx para NetApp ONTAP.

El centro de cargas de trabajo de BlueXP  incluye una calculadora de ahorro en el almacenamiento para comparar los entornos de almacenamiento de Amazon con FSx para ONTAP. Puede obtener más ahorro con o sin necesidad de proporcionar sus credenciales de AWS y personalizar los ajustes de configuración para su entorno de almacenamiento. Al proporcionar credenciales de AWS, puede seleccionar una o más instancias de Amazon Elastic Block Store, por ejemplo, y dejar que la carga de trabajo realice la comparación automáticamente. Tanto de forma manual como automática, la calculadora determina qué servicio de almacenamiento proporciona el menor coste posible para sus necesidades de almacenamiento.

Si la calculadora de almacenamiento determina que el almacenamiento más rentable es FSx para ONTAP, puedes crear o guardar configuraciones de FSx para ONTAP y usar el CodeBox para generar plantillas de infraestructura como código independientemente de los permisos que otorgues a la fábrica de cargas de trabajo.



== Opciones de calculadora

Hay dos opciones de calculadora disponibles para comparar costes entre tus sistemas y FSx for ONTAP: Personalización y detección automática para tus entornos de almacenamiento de Amazon.

Explorar el ahorro a través de la personalización: Proporciona los ajustes de configuración para un entorno de almacenamiento, incluidos el caso de uso, la región, el número de volúmenes o sistemas de archivos, la cantidad de copias Snapshot, la cantidad que se cambia por snapshot, el IOPS aprovisionado, el rendimiento y mucho más.

Explora el ahorro de los entornos de almacenamiento detectados: La fábrica de cargas de trabajo se conecta a los entornos de almacenamiento de AWS existentes y añade los detalles a la calculadora para realizar una comparación automática. Tendrás que conceder permisos de automatización para usar el modo automático. Puede cambiar el caso de uso, pero todos los demás detalles se determinan automáticamente en el cálculo.

Además, puede link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Añada las credenciales de AWS"^]mejorar la precisión del análisis de la calculadora. Selecciona *Calcular los ahorros en función de los recursos existentes*. Se le redirigirá a la página Agregar credenciales. Después de agregar credenciales, seleccione los recursos existentes para comparar con FSx para ONTAP y seleccione *Explorar ahorros*.



== Explora el ahorro a través de la personalización

Siga los pasos debajo de la pestaña para su selección de almacenamiento.

[role="tabbed-block"]
====
.Elastic Block Store (EBS) de Amazon
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Explorar ahorros* y luego *Amazon Elastic Block Store (EBS)*.
. En la calculadora de ahorro de almacenamiento, proporcione la siguiente información:
+
.. *Caso de uso*: Requerido. Seleccione un caso de uso en el menú desplegable. El caso de uso seleccionado determina las características del sistema de archivos FSx para ONTAP para su comparación.
.. *Región*: Opcional. Seleccione la región para la configuración de EBS en el menú desplegable.
.. *Seleccione el tipo de volumen EBS*: Opcional. Seleccione el tipo de volumen de EBS que utiliza para la configuración.
.. *Número de volúmenes*: Opcional. Introduzca el número de volúmenes en la configuración de EBS.
.. *Cantidad de almacenamiento por volumen (TiB)*: Opcional. Introduzca la cantidad de almacenamiento por volumen en TiB.
.. *Frecuencia de instantánea*: Opcional. Seleccione la frecuencia de Snapshot para la configuración de EBS.
.. *Cantidad cambiada por instantánea (GiB)*: Opcional. Solo para el almacenamiento Snapshot. Introduzca la cantidad modificada por snapshot en GiB.
.. *IOPS provisionadas por volumen*: Opcional. Para volúmenes GP3, io1 y io2. Introduzca las IOPS aprovisionadas por volumen.
.. *Rendimiento (MIB/s)*: Opcional. Solo para volúmenes GP3. Introduzca el rendimiento en MiB/s por volumen.




--
.Amazon FSx para Windows File Server
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Explorar ahorros* y luego *Amazon FSx para Windows File Server*.
. En la calculadora de ahorro de almacenamiento, proporcione la siguiente información:
+
.. *Caso de uso*: Requerido. Seleccione un caso de uso en el menú desplegable. El caso de uso seleccionado determina las características del sistema de archivos FSx para ONTAP para su comparación.
.. *Región*: Opcional. Seleccione la región para la configuración de su servidor de archivos de FSx para Windows en el menú desplegable.
.. *Tipo de implementación*: Opcional. Seleccione *Zona de disponibilidad única* o *Múltiples zonas de disponibilidad*.
.. *Tipo de almacenamiento*: El tipo de almacenamiento SSD se selecciona por defecto.
.. *Capacidad de almacenamiento (TiB)*: Opcional. Introduzca la capacidad de almacenamiento para la configuración.
.. *Ahorro en deduplicación (%)*: Opcional. Introduzca el porcentaje de ahorro de capacidad que espera de la deduplicación.
.. *Frecuencia de instantánea*: Opcional. Seleccione la frecuencia de Snapshot para la configuración.
.. *Cantidad cambiada por instantánea (GiB)*: Opcional. Solo para el almacenamiento Snapshot. Introduzca la cantidad modificada por snapshot en GiB.
.. * IOPS SSD aprovisionado*: Opcional. Introduzca la IOPS de SSD aprovisionada.
.. *Rendimiento (MIB/s)*: Opcional. Introduzca el rendimiento en MiB/s.




--
.Amazon Elastic File System (EFS)
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Explorar ahorros* y luego *Amazon Elastic File System (EFS)*.
. En la calculadora de ahorro de almacenamiento, proporcione la siguiente información:
+
.. *Caso de uso*: Requerido. Seleccione un caso de uso en el menú desplegable. El caso de uso seleccionado determina las características del sistema de archivos FSx para ONTAP para su comparación.
.. *Región*: Opcional. Seleccione la región para la configuración de su servidor de archivos de FSx para Windows en el menú desplegable.
.. *Tipo de sistema de archivos*: Opcional. Selecciona *Regional* o *una zona*.
.. *Capacidad de almacenamiento (TiB)*: Opcional. Introduzca la capacidad de almacenamiento de la configuración de EFS.
.. *Datos de acceso frecuente (%)*: Opcional. Introduzca el porcentaje de datos a los que se accede con frecuencia.
.. *Modo de rendimiento*: Opcional. Seleccione *Rendimiento aprovisionado* o *Rendimiento elástico*.
.. *Rendimiento (MIB/s)*: Opcional. Introduzca el rendimiento en MiB/s.




--
====
Después de proporcionar detalles sobre la configuración del sistema de almacenamiento, revise los cálculos y las recomendaciones que se proporcionan en la página.

Además, desplácese hasta la parte inferior de la página para ver el informe seleccionando una de las siguientes opciones:

* *Exportar PDF*
* *Enviar por correo electrónico*
* *Ver los cálculos*


Para cambiar a FSX para ONTAP, siga las instrucciones a <<Pon en marcha FSx para sistemas de archivos ONTAP,Pon en marcha FSx para sistemas de archivos ONTAP>>.



== Explore el ahorro para los entornos de almacenamiento detectados

.Antes de empezar
Para que la fábrica de cargas de trabajo detecte los entornos de almacenamiento de Amazon Elastic Block Store (EBS), Elastic File System (EFS) y FSx para Windows File Server en su cuenta de AWS, asegúrese de hacerlo  en su cuenta link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["conceder permisos de _solo lectura_"^]de AWS.


NOTE: Esta opción de calculadora no admite cálculos para las instantáneas de EBS y las copias redundantes de FSx para Windows File Server. Al analizar el ahorro mediante la personalización, puedes proporcionar detalles de copias Snapshot de EBS y FSx para el servidor de archivos de Windows.

Siga los pasos debajo de la pestaña para su selección de almacenamiento.

[role="tabbed-block"]
====
.Elastic Block Store (EBS) de Amazon
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Ir al inventario de almacenamiento*.
. En el Inventario de almacenamiento, selecciona la pestaña *Explorar ahorros*.
. En la pestaña *Tienda de bloques elásticos (EBS)*, selecciona las instancias para comparar con FSX para ONTAP y selecciona *Explorar ahorros*.
. Aparece la calculadora de ahorro en almacenamiento. Las siguientes características del sistema de almacenamiento se rellenan previamente en función de las instancias seleccionadas:
+
.. *Caso de uso*: El caso de uso para su configuración. Puede cambiar el caso de uso si es necesario.
.. *Volúmenes seleccionados*: El número de volúmenes en la configuración de EBS
.. *Cantidad total de almacenamiento (TiB)*: La cantidad de almacenamiento por volumen en TiB
.. *Total de IOPS aprovisionadas*: Para volúmenes de GP3, io1 y io2
.. *Rendimiento total (MIB/s)*: Solo para GP3 volúmenes




--
.Amazon FSx para Windows File Server
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Ir al inventario de almacenamiento*.
. En el Inventario de almacenamiento, selecciona la pestaña *Explorar ahorros*.
. En la pestaña *Servidor de archivos de Amazon FSx para Windows*, selecciona las instancias para comparar con FSx para ONTAP y selecciona *Explorar ahorros*.
. Aparece la calculadora de ahorro en almacenamiento. Las siguientes características del sistema de almacenamiento se rellenan previamente según el tipo de implementación de las instancias seleccionadas:
+
.. *Caso de uso*: El caso de uso para su configuración. Puede cambiar el caso de uso si es necesario.
.. * Sistemas de archivos seleccionados
.. *Cantidad total de almacenamiento (TiB)*
.. * IOPS SSD aprovisionado*
.. *Rendimiento (MIB/s)*




--
.Amazon Elastic File System (EFS)
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Ir al inventario de almacenamiento*.
. En el Inventario de almacenamiento, selecciona la pestaña *Explorar ahorros*.
. En la pestaña *Sistema de archivos elásticos (EFS)*, selecciona las instancias para comparar con FSX para ONTAP y selecciona *Explorar ahorros*.
. Aparece la calculadora de ahorro en almacenamiento. Las siguientes características del sistema de almacenamiento se rellenan previamente en función de las instancias seleccionadas:
+
.. *Caso de uso*: El caso de uso para su configuración. Puede cambiar el caso de uso si es necesario.
.. *Sistemas de archivos totales*
.. *Cantidad total de almacenamiento (TiB)*
.. *Rendimiento total aprovisionado (MIB/s)*
.. *Rendimiento elástico total - leer (GiB)*
.. *Rendimiento elástico total – escribir (GiB)*




--
====
Después de proporcionar detalles sobre la configuración del sistema de almacenamiento, revise los cálculos y las recomendaciones que se proporcionan en la página.

Además, desplácese hasta la parte inferior de la página para ver el informe seleccionando una de las siguientes opciones:

* *Exportar PDF*
* *Enviar por correo electrónico*
* *Ver los cálculos*




== Pon en marcha FSx para sistemas de archivos ONTAP

Si desea cambiar a FSX para ONTAP para obtener ahorros de costos, seleccione *Crear* para crear los sistemas de archivos directamente desde el Asistente para crear un FSX para el sistema de archivos ONTAP o seleccione *Guardar* para guardar las configuraciones recomendadas para más adelante.

Métodos de despliegue:: En el modo _Automate_, puede implementar el sistema de archivos FSx para ONTAP directamente desde la fábrica de cargas de trabajo. También puede copiar el contenido de la ventana CodeBox e implementar el sistema utilizando uno de los métodos CodeBox.
+
--
En el modo _BASIC_, puede copiar el contenido de la ventana CodeBox e implementar el sistema de archivos FSX for ONTAP utilizando uno de los métodos CodeBox.

--

