---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: La fábrica de cargas de trabajo de BlueXP  para bases de datos analiza las configuraciones de Microsoft SQL Server proporcionando información y recomendaciones para ayudarle a lograr la excelencia operativa. 
---
= Implemente configuraciones de sistemas de archivos bien diseñadas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mediante información y recomendaciones de análisis de la configuración, aprovecha la fábrica de cargas de trabajo de BlueXP  para implementar las prácticas recomendadas para tus sistemas de archivos FSx para ONTAP. Puede encontrar problemas fácilmente y emprender acciones para mejorar la arquitectura de cualquier sistema que no esté optimizado para ofrecer fiabilidad, seguridad, eficiencia, rendimiento y costos.

.Acerca de esta tarea
BlueXP  analiza a diario las configuraciones de puesta en marcha del sistema de archivos de Amazon FSx para NetApp ONTAP. El análisis diario proporciona información y recomendaciones con opciones para solucionar automáticamente problemas de configuración para que su sistema de archivos cumpla las prácticas recomendadas.

Tiene opciones para revisar las recomendaciones sobre problemas de configuración con los sistemas de archivos y corregir esos problemas desde el inventario de almacenamiento en la consola de fábrica de cargas de trabajo.

Qué se analiza:: La fábrica de cargas de trabajo analiza el estado bien diseñado de las siguientes configuraciones para los sistemas de archivos FSx para ONTAP:
+
--
* Umbral de capacidad de SSD
* Organización en niveles de los datos
* Snapshots locales programadas
* FSX para backups de ONTAP y.
* Replicación de datos remota


--


.Antes de empezar
* Debe tener credenciales con permisos de solo lectura o de lectura/escritura. link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Aprende a otorgar permisos en tu cuenta de AWS"^].
* Asegúrese de revisar cada recomendación cuidadosamente antes de seleccionar para corregir una configuración o configuración.



NOTE: El proceso de corrección puede provocar tiempos de inactividad de instancias o interrupciones del servicio. Asegúrese de revisar cuidadosamente la recomendación antes de decidir solucionar un problema de configuración.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, navega a la columna *Estado bien diseñado* y selecciona los problemas para que el sistema de archivos corrija.
. En la consola bien diseñada para el sistema de archivos, filtre los problemas de configuración por categorías, subcategorías, estado, gravedad y etiquetas.
. Seleccione la flecha desplegable para ver la recomendación de cualquier configuración. Asegúrese de revisar la recomendación cuidadosamente.
+
La recomendación explica las prácticas recomendadas y las posibles dificultades de las configuraciones no optimizadas.

. Seleccione *Fix*.
+
Cuando *Ver y corregir* sea una opción, seleccione los volúmenes afectados para corregir.

. Revise los elementos de resumen y acción que aparecen en el cuadro de diálogo para saber qué sucederá si decide solucionar el problema. Algunas operaciones pueden provocar tiempos de inactividad de instancias o interrupciones del servicio.
. Seleccione *Continuar* para solucionar el problema de configuración.


.Resultado
Se inicia el proceso para solucionar el problema. Seleccione la pestaña *Supervisión de trabajos* para ver el estado de la operación.
