---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: La fábrica de cargas de trabajo de BlueXP  para bases de datos analiza las configuraciones de Microsoft SQL Server proporcionando información y recomendaciones para ayudarle a lograr la excelencia operativa. 
---
= Implemente configuraciones de sistemas de archivos bien diseñadas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Con la información y las recomendaciones del análisis de configuración, aproveche Workload Factory para implementar las mejores prácticas para sus sistemas de archivos de FSx for ONTAP . Puede revisar fácilmente el estado de la arquitectura, conocer los problemas de sus configuraciones y tomar medidas para mejorar la arquitectura de cualquier sistema que no esté optimizado en términos de confiabilidad, seguridad, eficiencia, rendimiento y costo.

link:configuration-analysis.html["Obtenga información sobre el análisis de configuración y el estado de buena arquitectura en la fábrica de carga de trabajo."]

.Acerca de esta tarea
Workload Factory analiza diariamente las configuraciones de implementación del sistema de archivos de Amazon FSx for NetApp ONTAP . Este análisis diario proporciona el estado de la arquitectura, así como información y recomendaciones, con opciones para corregir automáticamente los problemas de configuración y que su sistema de archivos cumpla con las prácticas recomendadas.

Tiene opciones para revisar las recomendaciones para problemas de configuración con sus sistemas de archivos y solucionar los problemas desde el inventario de almacenamiento dentro de la consola de fábrica de carga de trabajo.

Qué se analiza:: La fábrica de cargas de trabajo analiza el estado bien diseñado de las siguientes configuraciones para los sistemas de archivos FSx para ONTAP:
+
--
* Umbral de capacidad de SSD
* Organización en niveles de los datos
* Snapshots locales programadas
* FSx para copias de seguridad de ONTAP
* Replicación de datos remota
* Eficiencias del almacenamiento
* Gestión de la capacidad automática


--


.Antes de empezar
* Debe tener credenciales con permisos de _solo lectura_ o de _lectura/escritura_. link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Aprende a otorgar permisos en tu cuenta de AWS"^].
* Asegúrese de revisar cada recomendación cuidadosamente antes de seleccionar para corregir una configuración o configuración.



NOTE: El proceso de corrección puede provocar tiempos de inactividad de instancias o interrupciones del servicio. Asegúrese de revisar cuidadosamente la recomendación antes de decidir solucionar un problema de configuración.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, navega a la columna *Estado bien diseñado* y selecciona los problemas para que el sistema de archivos corrija.
. En la consola bien diseñada para el sistema de archivos, filtre los problemas de configuración por categorías, subcategorías, estado, gravedad y etiquetas.
. Seleccione la flecha desplegable para ver la recomendación de cualquier configuración. Asegúrese de revisar la recomendación cuidadosamente.
+
La recomendación explica las prácticas recomendadas y las posibles dificultades de las configuraciones no optimizadas.

. Seleccione *Fix*.
+
Cuando *Ver y corregir* sea una opción, seleccione los volúmenes afectados para corregir.

. Revise los elementos de resumen y acción que aparecen en el cuadro de diálogo para saber qué sucederá si decide solucionar el problema. Algunas operaciones pueden provocar tiempos de inactividad de instancias o interrupciones del servicio.
. Seleccione *Continuar* para solucionar el problema de configuración.


.Resultado
Se inicia el proceso para solucionar el problema. Seleccione el menú de configuración de la cuenta y luego seleccione *Rastreador* para ver el estado de la operación.
