---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: Aumente manualmente la capacidad de volumen de un volumen en NetApp Workload Factory en cualquier momento. 
---
= Aumente la capacidad de volumen en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aumente manualmente la capacidad de volumen de un volumen en cualquier momento en NetApp Workload Factory.

Opcionalmente, puedeslink:edit-volume-autogrow.html["habilite la función crecimiento automático"] para permitir que Workload Factory administre la capacidad de volumen por usted.

.Acerca de esta tarea
Para un LUN de iSCSI, esta operación aumenta el tamaño del LUN del host. Después de aumentar la capacidad, siga el procedimiento proporcionado por el sistema operativo del host para detectar el nuevo tamaño de la LUN y expandir el sistema de archivos de la LUN.

.Antes de empezar
Para aumentar la capacidad de volumen, debe asociar un enlace. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con el volumen a actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña Volúmenes, seleccione el menú de acciones del volumen cuya capacidad desea aumentar.
. Selecciona *Acciones básicas* y luego *Aumentar capacidad de volumen*.
. En el cuadro de diálogo Aumentar capacidad del volumen, realice lo siguiente:
+
.. Seleccione un tamaño más grande.
.. Cambie la unidad si es necesario.


. Seleccione *Aumentar* para aplicar el cambio.

