---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: increase capacity, increase file system capacity, increase FSx capacity 
summary: Aumente manualmente la capacidad de almacenamiento en SSD de un sistema de archivos FSx para ONTAP cuando la cantidad de capacidad de almacenamiento SSD utilizada supere un umbral que haya especificado. 
---
= Aumente la capacidad del sistema de archivos en la fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aumente manualmente la capacidad de almacenamiento en SSD de un sistema de archivos FSx para ONTAP cuando la cantidad de capacidad de almacenamiento SSD utilizada supere un umbral que haya especificado.

De forma alternativa, link:enable-auto-capacity-management.html["habilite la función de gestión automática de capacidad"]la fábrica de carga de trabajo gestiona la capacidad del sistema de archivos.

.Acerca de esta tarea
El aumento de la capacidad del sistema de archivos afecta al IOPS de su sistema de archivos FSx para ONTAP.

Cuando se utiliza automáticamente link:provision-iops.html["Aprovisione IOPS"] en el caso de un sistema de archivos, IOPS aumenta en 3 IOPS con cada aumento de 1 GiB de la capacidad de SSD.

Cuando se realiza link:provision-iops.html["Aprovisione IOPS"] manualmente, es posible que deba aumentar la asignación de IOPS para respaldar la mayor capacidad del sistema de archivos.

Para ver los límites de capacidad de almacenamiento de SSD, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Cuotas"^] la documentación de AWS FSx para NetApp ONTAP.

.Antes de empezar
Para aumentar la capacidad de un sistema de archivos, primero debe link:enable-auto-capacity-management.html["deshabilite la gestión automática de la capacidad"].

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Ir a Inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos para aumentar la capacidad.
. Seleccione *gestionar*.
. En Información, seleccione el icono del lápiz junto a *Distribución de capacidad*. El icono del lápiz aparece junto a la flecha desplegable cuando el ratón pasa por encima de la fila *distribución de capacidad*.
. En el cuadro de diálogo de tamaño de almacenamiento SSD, introduzca un número para *Provisioned Capacity*.
. Seleccione la unidad de la capacidad aprovisionada.
. Seleccione *aplicar*.

