---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. 
---
= Limitaciones conocidas de Amazon FSx para NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.



== Enlace necesario para operaciones de ONTAP avanzadas

Se necesita un enlace para completar algunas operaciones como la replicación en la interfaz de usuario de la fábrica de cargas de trabajo.



== Limitaciones de añadir pares de alta disponibilidad

* Esta operación puede tardar aproximadamente 30 minutos en completarse.
* La adición de pares de alta disponibilidad limita las siguientes operaciones: Agregar más pares de alta disponibilidad, aprovisionar IOPS, aumentar la capacidad de SSD y actualizar la capacidad de rendimiento.




== Soporte regional de capacidad de rendimiento



=== Puestas en marcha de escalado vertical

Las configuraciones de escalado vertical se admiten hasta 2 Gb/s en todas las regiones. Las siguientes regiones admiten hasta 4 GB/s de capacidad de rendimiento máxima para implementaciones de escalado vertical: Región del Este de LOS EE. UU. (Ohio), región del Este de los EE. UU. (Norte de Virginia), región del Oeste de los EE. UU. (Oregón) y Europa (Irlanda).



=== Puestas en marcha de escalado horizontal

Las siguientes regiones admiten hasta 3 TB y 6 GB/s de capacidad de rendimiento máxima para puestas en marcha de escalado horizontal: EE. UU. Este (N. Virginia), Oriente de los EE. UU. (Ohio), Oeste de los EE. UU. (Oregón), Europa (Irlanda) y Asia Pacífico (Sídney).



== Gestión de la capacidad

* Actualmente, la función de crecimiento automático del volumen no se admite con el protocolo iSCSI.
* Cuando se ejecuta la función de gestión automática de la capacidad, no se permite el aumento de la capacidad manual.
* Solo es posible deshabilitar la función de gestión automática de capacidad con los mismos permisos que se usan para habilitarla.




== Máquinas virtuales de almacenamiento

El número de equipos virtuales de almacenamiento es limitado por SKU. No se admite la creación de equipos virtuales de almacenamiento más allá de esta limitación en la fábrica de cargas de trabajo.^1^

Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gestión de máquinas virtuales de almacenamiento de FSx para ONTAP"^] en la documentación de AWS el número máximo de SVM por sistema de archivos.



== Compatibilidad con el protocolo iSCSI

* El protocolo iSCSI solo está disponible para volúmenes FlexVol. 1
* Solo se puede configurar un único LUN por volumen.




== Protección de datos

* No se pueden eliminar las snapshots.
* Al replicar un sistema de archivos, todos los volúmenes del sistema de archivos usan la misma política de replicación.
* Para relaciones de replicación de retención a largo plazo, solo se puede restaurar la última copia Snapshot.




== Calculadora del ahorro en almacenamiento

La calculadora de ahorro en almacenamiento no calcula el ahorro de costes si utiliza las siguientes configuraciones:

* FSX para Windows File Server: Tipo de almacenamiento de HDD
* Almacenamiento de bloques elásticos (EBS): Tipos de volumen estándar, ST1 y sc1
* Sistema de archivos elásticos (EFS): Modo de rendimiento de repartición




== System Manager

System Manager no admite los enlaces de FSx para la conectividad de ONTAP.

Nota:

. Se aplica a Amazon FSx para NetApp ONTAP

