---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. 
---
= Limitaciones conocidas de Amazon FSx para NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.



== Soporte regional

Las siguientes regiones de AWS no son compatibles:

* regiones de China
* Regiones de GovCloud (EE. UU.)
* Nube secreta
* Nube de alto secreto




== Limitaciones de añadir pares de alta disponibilidad

* Es posible que esta operación tarde aproximadamente 30 minutos en completarse.
* La adición de pares de alta disponibilidad limita las siguientes operaciones: Agregar más pares de alta disponibilidad, aprovisionar IOPS, aumentar la capacidad de SSD y actualizar la capacidad de rendimiento.




== Soporte regional de capacidad de rendimiento



=== Puestas en marcha de escalado vertical

Las configuraciones de escalado vertical se admiten hasta 2 Gb/s en todas las regiones. Las siguientes regiones admiten hasta 4 GB/s de capacidad de rendimiento máxima para implementaciones de escalado vertical: Región del Este de LOS EE. UU. (Ohio), región del Este de los EE. UU. (Norte de Virginia), región del Oeste de los EE. UU. (Oregón) y Europa (Irlanda).



=== Puestas en marcha de escalado horizontal

Las siguientes regiones admiten una capacidad de rendimiento máxima de hasta 6 GB/s para implementaciones de escalamiento horizontal: Este de EE. UU. (Norte de Virginia y Ohio), Oeste de EE. UU. (Norte de California y Oregón), Europa (Fráncfort, Irlanda y Estocolmo) y Asia Pacífico (Singapur y Sídney).



== Gestión de la capacidad

* Actualmente, la función de crecimiento automático del volumen no se admite con el protocolo iSCSI.
* Cuando se ejecuta la función de gestión automática de la capacidad, no se permite el aumento de la capacidad manual.
* Solo es posible deshabilitar la función de gestión automática de capacidad con los mismos permisos que se usan para habilitarla.
* Cuando está habilitada la gestión automática de la capacidad, se requiere un enlace para garantizar que los inodos de volumen aumenten junto con la capacidad de almacenamiento.




== Máquinas virtuales de almacenamiento

La cantidad de máquinas virtuales de almacenamiento está limitada por SKU.  La creación de máquinas virtuales de almacenamiento más allá del límite no es compatible con Workload Factory.^1^

Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gestión de máquinas virtuales de almacenamiento de FSx para ONTAP"^] en la documentación de AWS el número máximo de SVM por sistema de archivos.



== Compatibilidad con el protocolo iSCSI

* El protocolo iSCSI solo está disponible para volúmenes FlexVol. 1
* La reducción del tamaño del volumen no es compatible con volúmenes iSCSI.




== Protección de datos

* No se pueden eliminar las snapshots.
* Al replicar un sistema de archivos, todos los volúmenes del sistema de archivos usan la misma política de replicación.
* Para relaciones de replicación de retención a largo plazo, solo se puede restaurar la última copia Snapshot.
* Las siguientes funciones no son compatibles con instantáneas inmutables:
+
** Grupos de consistencia
** FabricPool
** Volúmenes de FlexCache
** SMTape
** SnapMirror síncrono activo
** Reglas de políticas de SnapMirror con el parámetro -schedule
** SnapMirror síncrono
** Movilidad de datos de SVM (se usa para migrar o reubicar una SVM desde un clúster de origen a un clúster de destino)






== Calculadora del ahorro en almacenamiento

La calculadora de ahorro en almacenamiento no calcula el ahorro de costes si utiliza las siguientes configuraciones:

* FSX para Windows File Server: Tipo de almacenamiento de HDD
* Almacenamiento de bloques elásticos (EBS): Tipos de volumen estándar, ST1 y sc1
* Sistema de archivos elásticos (EFS): Modo de rendimiento de repartición




== Compatibilidad con AWS Secrets Manager

AWS Secrets Manager no es compatible cuando se utiliza un agente de consola.



== Limitación de los puntos de acceso de Amazon S3

El límite para la cantidad de puntos de acceso S3 por máquina virtual de almacenamiento es 4000.

Nota:

. Se aplica a Amazon FSx para NetApp ONTAP

