---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: Amazon FSx para NetApp ONTAP es un servicio totalmente gestionado que permite a los clientes iniciar y ejecutar sistemas de archivos como el back-end de almacenamiento para las cargas de trabajo dentro de la fábrica de cargas de trabajo. 
---
= Obtén más información sobre Amazon FSx para NetApp ONTAP en la fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSx para NetApp ONTAP es un servicio de almacenamiento de datos basado en cloud totalmente gestionado que ofrece capacidades de gestión de datos avanzadas y un rendimiento muy escalable. FSX para ONTAP le permite crear y gestionar sistemas de archivos como back-end de almacenamiento para todas sus cargas de trabajo en la fábrica de cargas de trabajo de BlueXP .

FSX para ONTAP proporciona las mismas funciones, rendimiento y funcionalidades administrativas que los clientes de NetApp utilizan actualmente en las instalaciones, con la simplicidad, agilidad, seguridad y escalabilidad de un servicio de AWS nativo.

FSX para ONTAP es el componente _Storage_ de la fábrica de cargas de trabajo.



== Funciones

FSX para ONTAP ofrece las siguientes características:

* *Servicio totalmente administrado*: Proporciona un servicio totalmente administrado integrado con la consola de la fábrica de carga de trabajo.
* * Alta disponibilidad*: Proporciona alta disponibilidad para cada sistema de archivos FSX for ONTAP, compatible con implementaciones de zonas de disponibilidad únicas y múltiples.
* *Instantáneas automatizadas*: Protege los datos con instantáneas automatizadas y eficientes, que son copias puntuales casi instantáneas y eficientes en el espacio del sistema de archivos o volúmenes.
* *Replicación de volúmenes*: Proporciona recuperación ante desastres con replicación entre regiones en Amazon Web Services.
* *Copias de seguridad eficientes*: Añade una capa extra de protección con una copia de los datos en otra región para emergencias.
* *Clonación rápida*: Acelera el desarrollo de aplicaciones con clonación rápida.
* *Compatibilidad con varios protocolos*: Admite los protocolos Sistema de archivos de red (NFS), Bloque de mensajes del servidor (SMB) e Interfaz de sistemas informáticos pequeños de Internet (iSCSI).
* * Alto rendimiento*: Ofrece un alto rendimiento para garantizar latencias bajas para cargas de trabajo que se ejecutan sobre sistemas de archivos FSX para ONTAP.
* *Caché en memoria y caché NVMe*: Incluye una caché en memoria única y caché NVMe, que aumenta el rendimiento de los datos a los que se accede con frecuencia.
* *Cientos de miles de IOPS*: Proporciona cientos de miles de IOPS con discos SSD, lo que garantiza que su almacenamiento y cargas de trabajo reciban resultados oportunos.
* *Thin Provisioning*: Permite el aprovisionamiento de capacidad por adelantado, ahorrando costos hasta que se necesite más capacidad.
* *Desduplicación y compresión de datos*: Elimina los datos duplicados y comprime los datos para reducir la cantidad de almacenamiento físico que se necesita para los sistemas de archivos FSX para ONTAP, lo que resulta en un ahorro de costes.
* *Data Tiering*: Permite reducir los costes de almacenamiento al mover los datos a los que se accede con menos frecuencia desde el nivel de almacenamiento primario SSD de alto rendimiento al nivel de almacenamiento secundario del pool de capacidad.




== Características adicionales en fábrica de cargas de trabajo

* *Calculadora de comparación de costos de almacenamiento*: Compara los costos de almacenamiento de tu tienda de bloques elásticos de Amazon (EBS), sistema de archivos elásticos (EFS) y FSX para el servidor de archivos de Windows con FSx para ONTAP. En la calculadora, puede ver cómo las configuraciones de almacenamiento de FSx para ONTAP ofrecen posibles ahorros y planificar la transición a FSx para el almacenamiento de ONTAP.
* *Interfaz de usuario de Workload Factory*: Proporciona opciones de modo de implementación _Quick create_ y _Advanced create_. La creación rápida incluye AWS, NetApp y prácticas recomendadas estándar del sector para sus configuraciones de almacenamiento.
* *CodeBox*: Proporciona a los desarrolladores un visor de código para las operaciones de FSX para ONTAP, plantillas de código para copiar y descargar, y un catálogo de automatización para la reutilización de código.




== Herramientas para utilizar la fábrica de cargas de trabajo

Puede utilizar la fábrica de cargas de trabajo de BlueXP  con las siguientes herramientas:

* *Consola de fábrica de carga de trabajo*: La consola de fábrica de carga de trabajo proporciona una interfaz visual que le brinda una visión integral de sus aplicaciones y proyectos
* *Consola BlueXP *: La consola BlueXP  proporciona una experiencia de interfaz híbrida para que pueda usar la fábrica de cargas de trabajo BlueXP  junto con otros servicios BlueXP 
* *API REST*: Las API REST DE la fábrica de cargas de trabajo le permiten implementar y administrar sus sistemas de archivos FSx para ONTAP y otros recursos de AWS
* *CloudFormation*: El código CloudFormation de AWS le permite realizar las acciones que definió en la consola de la fábrica de cargas de trabajo para modelar, aprovisionar y administrar recursos de AWS y de terceros desde la pila CloudFormation en su cuenta de AWS
* * Proveedor de fábrica de cargas de trabajo Terraform BlueXP *: Terraform le permite construir y administrar flujos de trabajo de infraestructura generados en la consola de la fábrica de cargas de trabajo




== Coste

AWS mantiene tu cuenta de FSx para ONTAP, no la fábrica de cargas de trabajo. Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Precios para Amazon FSx for NetApp ONTAP"^].



== Regiones admitidas

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Consulte las regiones de Amazon admitidas."^]



== Obtener ayuda

Amazon FSX para ONTAP de NetApp es una solución de primera parte de AWS. Para preguntas o problemas de soporte técnico asociados con tu ONTAP sistema de archivos, infraestructura o cualquier solución que use este servicio, usa el Centro de soporte de tu consola de administración de AWS para abrir un caso de soporte con AWS. Seleccione el servicio "FSX for ONTAP" y la categoría adecuada. Proporcione la información restante necesaria para crear su caso de soporte de AWS.

Para preguntas generales sobre la fábrica de cargas de trabajo o las aplicaciones y servicios de fábrica de cargas de trabajo, consulte link:get-help.html["Obtén ayuda para FSx for ONTAP para la fábrica de cargas de trabajo"].
