---
sidebar: sidebar 
permalink: limit-transfer-rate.html 
keywords: limit max transfer rate, limit transfer rate 
summary: Limite la tasa de transferencia máxima de una relación de replicación. Una tasa de transferencia ilimitada puede afectar negativamente al rendimiento de otras aplicaciones y su red. 
---
= Limite la tasa de transferencia máxima de una relación de replicación
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Limite la tasa de transferencia máxima de una relación de replicación. Una tasa de transferencia ilimitada puede afectar negativamente al rendimiento de otras aplicaciones y su red.

.Acerca de esta tarea
La limitación de la velocidad de transferencia máxima es opcional, pero se recomienda. Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir.

También recomendamos una tasa de transferencia ilimitada para los sistemas de archivos de FSx for ONTAP para cargas de trabajo cruciales; por ejemplo, aquellas que se usan principalmente para la recuperación ante desastres.

.Antes de empezar
Piense en la cantidad de ancho de banda que asignar a la replicación.

.Pasos
. Inicie sesión en link:https://console.workloads.netapp.com/["Consola de Workload Factory"^]
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, haz clic en el menú de tres puntos del sistema de archivos para actualizar y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, haga clic en el menú de tres puntos de la relación de replicación para limitar la tasa de transferencia máxima.
. Selecciona *Editar tasa de transferencia máxima*.
. En el cuadro de diálogo Editar velocidad de transferencia máxima, seleccione *Limited* e introduzca el límite máximo de transferencia en MB/s.
+
Alternativamente, selecciona *Ilimitado*.

. Haga clic en *aplicar*.

