---
sidebar: sidebar 
permalink: limit-transfer-rate.html 
keywords: limit max transfer rate, limit transfer rate 
summary: Limite la tasa de transferencia máxima de una relación de replicación en NetApp Workload Factory. 
---
= Limite la tasa de transferencia máxima de una relación de replicación
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Limite la tasa de transferencia máxima de una relación de replicación en NetApp Workload Factory.  Una tasa de transferencia ilimitada podría afectar negativamente el rendimiento de otras aplicaciones y de su red.

.Acerca de esta tarea
La limitación de la velocidad de transferencia máxima es opcional, pero se recomienda. Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir.

También recomendamos una tasa de transferencia ilimitada para los sistemas de archivos de FSx for ONTAP para cargas de trabajo cruciales; por ejemplo, aquellas que se usan principalmente para la recuperación ante desastres.

.Antes de empezar
Piense en la cantidad de ancho de banda que asignar a la replicación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el actionsenu del sistema de archivos que desea actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, seleccione las acciones de la relación de replicación para limitar la velocidad de transferencia máxima.
. Selecciona *Editar tasa de transferencia máxima*.
. En el cuadro de diálogo Editar velocidad de transferencia máxima, seleccione *Limited* e introduzca el límite máximo de transferencia en MB/s.
+
Alternativamente, selecciona *Ilimitado*.

. Seleccione *aplicar*.

