---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Un enlace de fábrica de cargas de trabajo crea una relación de confianza y conectividad entre una cuenta de fábrica de cargas de trabajo y uno o varios sistemas de archivos FSx para ONTAP. 
---
= Obtenga información sobre los enlaces de fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un enlace de fábrica de cargas de trabajo de BlueXP  crea una relación de confianza y conectividad entre una cuenta de fábrica de cargas de trabajo y uno o varios sistemas de archivos FSx para ONTAP. De este modo, puedes supervisar y gestionar determinadas funciones del sistema de archivos directamente desde las llamadas de la API DE REST DE ONTAP que no están disponibles a través de la API de Amazon FSx para ONTAP.

No es necesario establecer un vínculo para empezar con la fábrica de cargas de trabajo, pero en algunos casos deberá crear un vínculo para desbloquear todas las funciones de fábrica de cargas de trabajo y las capacidades de cargas de trabajo.



== Por qué son beneficiosos los enlaces

Los enlaces son beneficiosos porque permiten que la fábrica de cargas de trabajo realice operaciones que no están disponibles de forma nativa a través de la API de Amazon FSx for ONTAP . Los enlaces habilitan capacidades y automatizaciones avanzadas de ONTAP , lo que mejora la gestión de los sistemas de archivos de FSx for ONTAP .

A continuación se muestran algunos beneficios de utilizar enlaces:

* El enlace permite a BlueXP enviar comandos ONTAP directamente a su sistema de archivos FSx para ONTAP , aportando funciones ONTAP avanzadas más allá de lo que AWS ofrece de forma nativa.
* Los enlaces utilizan AWS Lambda para ejecutar código en respuesta a eventos. Este enfoque sin servidor elimina la dependencia de una instancia ejecutándose en su VPC.




== Cómo funcionan los enlaces

Los enlaces aprovechan AWS Lambda. Lambda ejecuta código en respuesta a eventos y gestiona automáticamente los recursos informáticos requeridos por ese código. Los enlaces que cree forman parte de su cuenta de NetApp y están asociados a una cuenta de AWS.

Después de crear un enlace, puede asociarlo con uno o muchos sistemas de archivos FSx para ONTAP . Cada sistema de archivos solo se puede asociar a un enlace en la misma cuenta de NetApp. Si tiene varias cuentas de NetApp, un único sistema de archivos se puede asociar con enlaces adicionales en diferentes cuentas de NetApp.

Crea y asocia vínculos desde la carga de trabajo de almacenamiento en la fábrica de cargas de trabajo.

Puede autenticar enlaces utilizando credenciales almacenadas en el servicio de credenciales de la fábrica de carga de trabajo o con sus credenciales almacenadas en AWS Secrets Manager. La fábrica de cargas de trabajo no admite el cambio de modos de autenticación.



== Externa

Cada transacción que realiza Lambda incurre en un cargo. Debido a que Lambda actúa como proxy entre los dos sistemas, hay un cargo cuando Lambda envía una solicitud a la API REST DE ONTAP en un sistema de archivos y cuando envía la respuesta de nuevo a la fábrica de cargas de trabajo.

link:https://aws.amazon.com/lambda/pricing/["Obtenga más información sobre los costos relacionados con el uso de AWS Lambda"^]



== Cuando se requiere un enlace

La fábrica de cargas de trabajo requiere un enlace para mostrar información y realizar algunas tareas. Si intenta realizar una operación que requiere un vínculo y no ha asociado un vínculo con el sistema de archivos FSx para ONTAP , la fábrica de carga de trabajo le notifica que la operación requiere un vínculo.

Las características que requieren un enlace incluyen:

* Estado bien diseñado de FSx para configuraciones del sistema de archivos ONTAP para mantenimiento proactivo, confiabilidad y optimización de costo-rendimiento
* Protección autónoma contra ransomware de NetApp (ARP/IA)
* Observabilidad de capacidad holística mejorada en FSx para sistemas de archivos ONTAP
* Replicación, administración y monitoreo de datos de máquinas virtuales de volumen y almacenamiento
* Acciones SMB/CIFS y aprovisionamiento y gestión de políticas de exportación NFS
* Gestión de volúmenes iSCSI en un sistema de archivos FSx para ONTAP
* Creación y gestión de políticas de instantáneas para SLA de protección personalizados
* Mejoras en la gestión de inodos para la gestión automática de la capacidad
* Crecimiento automático de volumen para escalamiento elástico
* Creación y gestión de clones para la clonación de datos instantánea e in situ
* Visualización de métricas adicionales directamente desde ONTAP , como la versión de ONTAP


Aprenda a link:create-link.html["conectar un enlace a un sistema de archivos FSx para ONTAP"].
