---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Un vínculo de Workload Factory crea una relación de confianza y conectividad entre una cuenta de Workload Factory y uno o más sistemas de archivos FSx para ONTAP . 
---
= Obtenga más información sobre los enlaces de NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un vínculo de NetApp Workload Factory crea una relación de confianza y conectividad entre una cuenta de Workload Factory y uno o más sistemas de archivos FSx para ONTAP .  Esto le permite monitorear y administrar ciertas características del sistema de archivos directamente desde las llamadas API REST de ONTAP que no están disponibles a través de la API de Amazon FSx para ONTAP .

No necesita un enlace para comenzar a usar Workload Factory, pero en algunos casos necesitará crear un enlace para desbloquear todas las funciones y capacidades de carga de trabajo de Workload Factory.



== Por qué son beneficiosos los enlaces

Los enlaces son beneficiosos porque permiten que Workload Factory realice operaciones que no están disponibles de forma nativa a través de la API de Amazon FSx para ONTAP .  Los enlaces habilitan capacidades y automatizaciones avanzadas de ONTAP , que mejoran la administración de FSx para los sistemas de archivos ONTAP .

A continuación se muestran algunos beneficios de utilizar enlaces:

* El enlace permite que la consola de NetApp envíe comandos ONTAP directamente a su sistema de archivos FSx para ONTAP , lo que aporta funciones ONTAP avanzadas más allá de lo que AWS ofrece de forma nativa.
* Los enlaces utilizan AWS Lambda para ejecutar código en respuesta a eventos. Este enfoque sin servidor elimina la dependencia de una instancia ejecutándose en su VPC.




== Cómo funcionan los enlaces

Los enlaces aprovechan AWS Lambda. Lambda ejecuta código en respuesta a eventos y gestiona automáticamente los recursos informáticos requeridos por ese código. Los enlaces que cree forman parte de su cuenta de NetApp y están asociados a una cuenta de AWS.

Después de crear un enlace, puede asociarlo con uno o muchos sistemas de archivos FSx para ONTAP . Cada sistema de archivos solo se puede asociar a un enlace en la misma cuenta de NetApp. Si tiene varias cuentas de NetApp, un único sistema de archivos se puede asociar con enlaces adicionales en diferentes cuentas de NetApp.

Crea y asocia vínculos desde la carga de trabajo de almacenamiento en Workload Factory.

Puede autenticar enlaces utilizando credenciales almacenadas en el servicio de credenciales de Workload Factory o con sus credenciales almacenadas en AWS Secrets Manager.  La fábrica de carga de trabajo no admite el cambio de modos de autenticación.



== Externa

Cada transacción que realiza Lambda genera un cargo.  Debido a que Lambda actúa como un proxy entre los dos sistemas, existe un cargo cuando Lambda envía una solicitud a la API REST de ONTAP en un sistema de archivos y cuando envía la respuesta a Workload Factory.

link:https://aws.amazon.com/lambda/pricing/["Obtenga más información sobre los costos relacionados con el uso de AWS Lambda"^]



== Cuando se requiere un enlace

La fábrica de carga de trabajo requiere un enlace para mostrar cierta información y realizar algunas tareas.  Si intenta realizar una operación que requiere un vínculo y no ha asociado un vínculo con el sistema de archivos FSx para ONTAP , Workload Factory le notifica que la operación requiere un vínculo.

Las características que requieren un enlace incluyen:

* Estado bien diseñado de FSx para configuraciones del sistema de archivos ONTAP para mantenimiento proactivo, confiabilidad y optimización de costo-rendimiento
* Monitoreo y alerta de eventos de ONTAP EMS
* Protección autónoma contra ransomware de NetApp (ARP/IA)
* Observabilidad de capacidad holística mejorada en FSx para sistemas de archivos ONTAP
* Replicación, administración y monitoreo de datos de máquinas virtuales de volumen y almacenamiento
* Acciones SMB/CIFS y aprovisionamiento y gestión de políticas de exportación NFS
* Gestión de volúmenes iSCSI en un sistema de archivos FSx para ONTAP
* Creación y gestión de políticas de instantáneas para SLA de protección personalizados
* Mejoras en la gestión de inodos para la gestión automática de la capacidad
* Crecimiento automático de volumen para escalamiento elástico
* Creación y gestión de clones para la clonación de datos instantánea e in situ
* Visualización de métricas adicionales directamente desde ONTAP , como la versión de ONTAP


Aprenda a link:create-link.html["conectar un enlace a un sistema de archivos FSx para ONTAP"].
