---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Un enlace Workload Factory crea una relación de confianza y conectividad entre una cuenta Workload Factory y uno o varios sistemas de archivos FSx para ONTAP. De este modo, puede supervisar y gestionar determinadas funciones del sistema de archivos directamente desde las API DE REST DE ONTAP que no están disponibles a través de las API de Amazon FSx para ONTAP. 
---
= Obtenga información sobre los enlaces de Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un enlace Workload Factory crea una relación de confianza y conectividad entre una cuenta Workload Factory y uno o varios sistemas de archivos FSx para ONTAP. De este modo, puede supervisar y gestionar determinadas funciones del sistema de archivos directamente desde las llamadas API DE REST DE ONTAP que no están disponibles a través de la API de Amazon FSx para ONTAP.

No necesita un vínculo para comenzar con Workload Factory, pero en algunos casos necesitará crear un vínculo para desbloquear todas las funciones de Workload Factory y capacidades de carga de trabajo.



== Cómo funcionan los enlaces

Los enlaces aprovechan AWS Lambda. Lambda ejecuta código en respuesta a eventos y gestiona automáticamente los recursos informáticos requeridos por ese código. Los enlaces que cree forman parte de su cuenta de NetApp y están asociados a una cuenta de AWS.

Después de crear un enlace, puede asociarlo con uno o varios sistemas de archivos FSX for ONTAP. Cada sistema de archivos solo se puede asociar a un enlace en la misma cuenta de NetApp. Si tiene varias cuentas de NetApp, un único sistema de archivos se puede asociar con enlaces adicionales en diferentes cuentas de NetApp.

Puede crear enlaces desde las páginas del sistema de archivos FSx para ONTAP en Workload Factory. link:create-link.html["Aprende a crear enlaces"] para obtener más detalles.



== Externa

Cada transacción que realiza Lambda incurre en un cargo. Como Lambda actúa como proxy entre los dos sistemas, se cobra cuando Lambda envía una solicitud a la API REST DE ONTAP en un sistema de archivos y cuando envía la respuesta a Workload Factory.

link:https://aws.amazon.com/lambda/pricing/["Obtenga más información sobre los costos relacionados con el uso de AWS Lambda"^]



== Cuando se requiere un enlace

Workload Factory necesita un enlace para mostrar información y realizar algunas tareas. Si intentas realizar una operación que requiere un enlace y no has asociado un enlace con el sistema de archivos FSX for ONTAP, verás un mensaje indicando que la operación requiere un enlace. Puede agregar un nuevo enlace o asociar el sistema de archivos FSx para ONTAP con un enlace existente en ese momento para que pueda realizar la operación.

Las características que requieren un enlace incluyen:

* Muestra la versión de ONTAP que está instalada en un sistema de archivos FSx for ONTAP
* Gestione volúmenes iSCSI en el sistema
* Habilite y deshabilite la función de crecimiento automático para los volúmenes
* Permite crear y gestionar políticas de Snapshot
* Configure las relaciones de replicación y replique volúmenes entre sistemas de archivos
* Configure las relaciones de backup y haga backups de los datos de volúmenes en el almacenamiento en cloud
* Clone volúmenes en un sistema de archivos
* Mostrar métricas adicionales directamente desde ONTAP (las métricas predeterminadas son recopiladas por Amazon CloudWatch)
* Gestión de las políticas de exportación de NFS

