---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Un enlace de fábrica de cargas de trabajo crea una relación de confianza y conectividad entre una cuenta de fábrica de cargas de trabajo y uno o varios sistemas de archivos FSx para ONTAP. 
---
= Obtenga información sobre los enlaces de fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un enlace de fábrica de cargas de trabajo de BlueXP  crea una relación de confianza y conectividad entre una cuenta de fábrica de cargas de trabajo y uno o varios sistemas de archivos FSx para ONTAP. De este modo, puede supervisar y gestionar determinadas funciones del sistema de archivos directamente desde las llamadas API DE REST DE ONTAP que no están disponibles a través de la API de Amazon FSx para ONTAP.

No es necesario establecer un vínculo para empezar con la fábrica de cargas de trabajo, pero en algunos casos deberá crear un vínculo para desbloquear todas las funciones de fábrica de cargas de trabajo y las capacidades de cargas de trabajo.



== Cómo funcionan los enlaces

Los enlaces aprovechan AWS Lambda. Lambda ejecuta código en respuesta a eventos y gestiona automáticamente los recursos informáticos requeridos por ese código. Los enlaces que cree forman parte de su cuenta de NetApp y están asociados a una cuenta de AWS.

Después de crear un enlace, puede asociarlo con uno o varios sistemas de archivos FSX for ONTAP. Cada sistema de archivos solo se puede asociar a un enlace en la misma cuenta de NetApp. Si tiene varias cuentas de NetApp, un único sistema de archivos se puede asociar con enlaces adicionales en diferentes cuentas de NetApp.

Crea enlaces desde las páginas del sistema de archivos FSx para ONTAP en la fábrica de cargas de trabajo. link:create-link.html["Aprende a crear enlaces"] para obtener más detalles.



== Externa

Cada transacción que realiza Lambda incurre en un cargo. Puesto que Lambda actúa como proxy entre los dos sistemas, se produce una carga cuando Lambda envía una solicitud a la API REST DE ONTAP en un sistema de archivos y cuando envía la respuesta de vuelta a la fábrica de cargas de trabajo.

link:https://aws.amazon.com/lambda/pricing/["Obtenga más información sobre los costos relacionados con el uso de AWS Lambda"^]



== Cuando se requiere un enlace

La fábrica de cargas de trabajo requiere un enlace para mostrar información y realizar algunas tareas. Si intentas realizar una operación que requiere un enlace y no has asociado un enlace con el sistema de archivos FSX for ONTAP, verás un mensaje indicando que la operación requiere un enlace. Puede agregar un nuevo enlace o asociar el sistema de archivos FSx para ONTAP con un enlace existente en ese momento para que pueda realizar la operación.

Las características que requieren un enlace incluyen:

* Visualización de la versión de ONTAP que está instalada en un sistema de archivos FSx for ONTAP
* Gestión de volúmenes iSCSI en un sistema de archivos FSx para ONTAP
* Función de crecimiento automático para volúmenes
* Creación y gestión de políticas de Snapshot
* Configuración de las relaciones de replicación
* Replicación de volúmenes entre sistemas de archivos FSx para ONTAP
* Configuración de las relaciones de backup
* Backups de datos de volúmenes en el almacenamiento en la nube
* Clones de volúmenes dentro de un sistema de archivos FSx para ONTAP
* Visualización de métricas adicionales directamente desde ONTAP (las métricas predeterminadas son recopiladas por Amazon CloudWatch)
* Gestión de las políticas de exportación de NFS
* Gestión de recursos compartidos CIFS

