---
sidebar: sidebar 
permalink: manage-nfs-export-policy.html 
keywords: NFS, nfs, export policy, change export policy, update export policy, modify export policy 
summary: Administre la política de exportación de NFS para un volumen que utiliza los tipos de protocolo NFSv3 o NFSv4.1 en NetApp Workload Factory. 
---
= Administrar la política de exportación de NFS para un volumen en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Administre la política de exportación de NFS para un volumen que utiliza los tipos de protocolo NFSv3 o NFSv4.1 en NetApp Workload Factory.

.Acerca de esta tarea
La política de exportación de un volumen implica añadir reglas de políticas de exportación que detallan las especificaciones del cliente, el control de acceso, el acceso de superusuarios y la versión de NFS. Puede añadir más de una política de exportación y asignarles prioridades.

.Antes de empezar
Determinar las especificaciones del cliente para las reglas de las políticas de exportación. Los valores válidos para la especificación de cliente son los siguientes:

* Direcciones IP
* Direcciones IP con máscaras de subred
* Las direcciones IP con una máscara de red
* Un nombre de netgroup precedido por el carácter «@»
* Un nombre de dominio precedido por un punto “.”
* Nombres de host


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con el volumen a actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña Volúmenes, seleccione el menú de acciones del volumen para el cual desea cambiar la política de exportación NFS.
. Seleccione *Acciones avanzadas* y luego *Editar política de exportación NFS*.
. En la página Edit NFS export policy, proporcione lo siguiente:
+
.. *Control de acceso*: Seleccione *Política de exportación personalizada* o *Política de exportación existente*.
+
Alternativamente, puede seleccionar *No hay acceso al volumen*.

.. *Nombre de la política de exportación*: Opcionalmente, introduzca un nombre para la política de exportación.
.. *Agregar regla de política de exportación*: Proporcione los siguientes detalles y clasifique las políticas que comienzan con #1 como regla de prioridad:
+
... *Especificación del cliente*: Separe múltiples valores con comas.
... *Control de acceso*: Selecciona *Leer/Escribir*, *Solo lectura* o *Sin acceso* en el menú desplegable.
... *Acceso de superusuario*: Selecciona *Sí* o *No*.
... *Versión NFS*: Seleccione *ALL*, *NFSv3* o *NFSv4*.




. Seleccione *aplicar*.

