---
sidebar: sidebar 
permalink: manage-svm-tags.html 
keywords: edit storage vm tags, vm tags, svm tags 
summary: Añada, actualice o quite etiquetas de máquinas virtuales de almacenamiento para una máquina virtual de almacenamiento en cualquier momento. 
---
= Administrar etiquetas de máquinas virtuales de almacenamiento en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Las etiquetas pueden ayudarle a categorizar sus recursos.  Puede agregar, editar y eliminar etiquetas de una máquina virtual de almacenamiento en cualquier momento en NetApp Workload Factory.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con la VM de almacenamiento que desea actualizar y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, en Máquinas virtuales de almacenamiento, seleccione *Administrar*.
. Desde la pantalla Administrar máquinas virtuales de almacenamiento, seleccione el menú de acciones de la máquina virtual de almacenamiento para la cual desea editar etiquetas y luego seleccione *Acciones básicas* > *Editar etiquetas de máquina virtual de almacenamiento*.
. En la página Edit storage VM tags, agregue, edite o elimine etiquetas.
+
La cantidad máxima de etiquetas que se pueden aplicar a una máquina virtual de almacenamiento es 50.

. Seleccione *aplicar*.

