---
sidebar: sidebar 
permalink: manage-snapshots.html 
keywords: snapshot, snapshots, manage snapshots, edit snapshots, access snapshots, delete snapshots, remove snapshots 
summary: Edite la configuración de instantáneas, habilite el acceso al directorio y elimine instantáneas para administrar sus instantáneas y la protección de datos en la fábrica de carga de trabajo. 
---
= Administrar instantáneas de un volumen FSx for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Edite la configuración de instantáneas, habilite el acceso al directorio y elimine instantáneas para administrar sus instantáneas y la protección de datos en la fábrica de carga de trabajo.



== Editar una instantánea

Editar el nombre, la etiqueta y el período de retención de una instantánea.  Si la instantánea aún no es inmutable, puedes hacerla inmutable.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña *Volúmenes*, seleccione el menú de tres puntos del volumen con la instantánea que desea editar.
. Seleccione *Acciones de protección de datos* y luego *Administrar instantáneas*.
. Desde la página Administrar instantáneas, seleccione el menú de tres puntos correspondiente a la instantánea que desea editar y, luego, seleccione *Editar*.
. En el cuadro de diálogo Editar una instantánea, puede editar lo siguiente:
+
.. Cambiar el nombre.
.. Cambiar la etiqueta.
.. Cambiar el período de retención.
.. Opcional: *Hacer que esta instantánea sea inmutable* para evitar que se elimine durante el período de retención.
+
Si la instantánea ya es inmutable, no puedes editar esta configuración.

+
Acepte la declaración sobre instantáneas inmutables.



. Seleccione *aplicar*.




== Acceder a una instantánea

Habilite el acceso al directorio de instantáneas para brindarles a los usuarios la posibilidad de acceder a las instantáneas de forma autónoma.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña *Volúmenes*, seleccione el menú de tres puntos correspondiente al volumen con la instantánea al que desea acceder.
. Seleccione *Acciones de protección de datos* y luego *Administrar instantáneas*.
. Desde la página Administrar instantáneas, seleccione el menú de tres puntos para la instantánea a la que desea acceder y luego seleccione *Acceso*.
. En el cuadro de diálogo Acceder a instantánea, seleccione *Habilitar acceso al directorio de instantáneas* para acceder a esta instantánea de volumen y a todas las instantáneas del volumen.
+
** Para volúmenes NFS: seleccione *Ruta de acceso NFS* para ver la ruta NFS de la instantánea.
** Para volúmenes SMB/CIFS: seleccione *Ruta de acceso SMB* para ver la ruta SMB de la instantánea.


. Copiar la ruta de acceso.
. Seleccione *aplicar*.




== Restaurar datos desde una instantánea

Tiene la opción de restaurar datos de una instantánea a un volumen existente o a un volumen nuevo.

link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_snapshot-mgmt/restore-volume-from-snapshot.html["Restaurar un volumen a partir de una copia de Snapshot"]



== Eliminar una instantánea

Eliminar una instantánea para liberar espacio.

Las instantáneas inmutables no se pueden eliminar hasta que finalice el período de retención.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña *Volúmenes*, seleccione el menú de tres puntos del volumen con la instantánea que desea eliminar.
. Seleccione *Acciones de protección de datos* y luego *Administrar instantáneas*.
. Desde la página Administrar instantáneas, seleccione el menú de tres puntos correspondiente a la instantánea que desea eliminar y, luego, seleccione *Eliminar*.
. En el cuadro de diálogo Eliminar instantánea, escriba "eliminar".
. Seleccione *Eliminar* para confirmar la eliminación.


.Información relacionada
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-snapshot.html["Crear una copia de Snapshot"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-snapshot-policy.html["Crear una política de Snapshot"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-volume-from-snapshot.html["Restaurar un volumen a partir de una copia de Snapshot"]

