---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share 
summary: Cambie el recurso compartido de CIFS de un volumen en la fábrica de cargas de trabajo BlueXP  que utiliza el tipo de protocolo SMB/CIFS. 
---
= Gestione el recurso compartido de CIFS de un volumen en la fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La gestión del recurso compartido CIFS de un volumen en la fábrica de cargas de trabajo de BlueXP  implica determinar los usuarios y grupos que deben otorgar acceso y el tipo de acceso que se les otorga.

.Antes de empezar
Determine los usuarios o grupos a los que se va a dar acceso y el tipo de acceso que se les debe otorgar.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, seleccione el menú de tres puntos del sistema de archivos con el volumen que desea actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volumes, seleccione el menú de tres puntos del volumen para cambiar el recurso compartido de SMB.
. Seleccione *Acciones avanzadas* y luego *Editar recurso compartido de CIFS*.
. En la página Edit CIFS Share, proporcione lo siguiente:
+
.. *Nombre*: Introduzca el nombre del recurso compartido CIFS.
.. *Permisos*: Seleccione Control total, Acceso de lectura/escritura, Lectura o Sin acceso y, a continuación, introduzca los usuarios o grupos separados por un punto y coma ( ; ). Los usuarios o grupos distinguen entre mayúsculas y minúsculas y el dominio del usuario se debe incluir con el formato “dominio\nombre de usuario”.


. Seleccione Aplicar.
+
Los cambios pueden hacer que los usuarios o grupos actuales pierdan el acceso al recurso compartido CIFS.

. Selecciona *Continuar* para guardar los cambios.


.Resultado
Se aplican cambios en el recurso compartido CIFS.
