---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Gestiona las políticas de copias Snapshot de FSx para ONTAP Volumes en la fábrica de cargas de trabajo de BlueXP . Una política de Snapshot define la manera en que el sistema crea copias de Snapshot para un volumen. 
---
= Permite gestionar políticas Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gestiona las políticas de copias Snapshot de FSx para ONTAP Volumes en la fábrica de cargas de trabajo de BlueXP . Una política de Snapshot define la manera en que el sistema crea copias de Snapshot para un volumen.

.Acerca de esta tarea
Las operaciones de gestión de snapshots, como asignar, cambiar y eliminar políticas de snapshots para volúmenes en el sistema de archivos FSx para ONTAP, se gestionan a nivel de máquina virtual de almacenamiento. Las políticas de Snapshot se pueden compartir con una sola máquina virtual de almacenamiento o con todas las máquinas virtuales de almacenamiento.

Algunas tareas de gestión requieren que se link:manage-links.html["asocie un enlace"]conecte al sistema de archivos FSx para ONTAP. Si no tienes un enlace existente, link:create-link.html["cree un vínculo"].

De forma predeterminada, cada volumen está asociado con la política de Snapshot del sistema de archivos `default` . Recomendamos usar esta política para la mayoría de las cargas de trabajo.



== Cambiar una política de Snapshot

Es posible cambiar el nombre de la política de snapshots, la programación y la cantidad de copias para conservar, y habilitar o deshabilitar snapshots inmutables. No es posible habilitar o deshabilitar el uso compartido de políticas en los equipos virtuales de almacenamiento. Esta opción solo está disponible durante la creación de políticas de Snapshot.

.Antes de empezar
Para mostrar las políticas de instantáneas existentes, debe asociar un enlace. Para asociar un enlace, seleccione *Enlace asociado* en *Nombre de cuenta*. A continuación, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Storage VMs*.
. En la pestaña *VM de almacenamiento*, seleccione el menú de tres puntos para la VM de almacenamiento que contiene el volumen a proteger con instantáneas programadas, luego *Acciones avanzadas* y luego *Administrar políticas de instantáneas*.
. En la página de administración de políticas de Snapshot, seleccione el menú de tres puntos para que cambie la política de instantáneas y, a continuación, seleccione *Editar*.
. En el cuadro de diálogo Edit snapshot policy, realice los cambios necesarios en la política de Snapshot.
. Seleccione *aplicar*.


.Resultado
Se actualiza la política de instantáneas.



== Habilite instantáneas inmutables

Bloquee las snapshots para evitar que se eliminen durante el período de retención.

.Antes de empezar
link:manage-links.html["asocie un enlace"]Debe habilitar snapshots inmutables. Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Una vez asociado el enlace, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos que contiene el volumen para bloquear las instantáneas y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña *Volúmenes*, seleccione el menú de tres puntos para el volumen a proteger.
. Selecciona *Acciones de protección de datos*, *Snapshots*, luego *Hacer una instantánea inmutable*.
. En el cuadro de diálogo Make a snapshot immutable, haga lo siguiente:
+
.. *Nombre de la instantánea*: Seleccione la instantánea que desea bloquear.
.. Establezca el *Período de retención* en número de horas, días, meses o años.
.. Acepte la sentencia.


. Seleccione *aplicar*.


.Resultado
La instantánea del volumen está bloqueada.



== Asigne una política de Snapshot a un volumen

Es posible asignar una política de Snapshot a un solo volumen para crear Snapshot programadas para el volumen.

.Antes de empezar
Debe link:manage-links.html["asocie un enlace"]asignar una política de Snapshot. Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Después de asociar el enlace, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos que contiene el volumen al que asignar una política de instantáneas y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Storage VMs*.
. En la pestaña *VM de almacenamiento*, seleccione el menú de tres puntos para la VM de almacenamiento que contiene el volumen a proteger con instantáneas programadas, luego *Acciones avanzadas* y luego *Administrar políticas de instantáneas*.
. En la página de administración de políticas Snapshot, seleccione el menú de tres puntos de la política de instantáneas y, a continuación, seleccione *Asignar política al volumen*.
. En el cuadro de diálogo Assign snapshot policy, seleccione una política de Snapshot para asignar al volumen y revise la programación de políticas.
+
Si la política contiene instantáneas inmutables y desea utilizarlas, acepte la declaración.

. Selecciona *Asignar*.


.Resultado
La política de Snapshot está asignada al volumen.



== Quite una política de Snapshot de un volumen

Quite una política de Snapshot de un volumen porque ya no desea que las Snapshot del volumen o porque desea eliminar una política de Snapshot que está asignada a varios volúmenes. A <<Elimine una política de Snapshot,elimine una política de snapshot>>que está asignado a más de un volumen, debe eliminarlo manualmente de todos los volúmenes.

.Antes de empezar
Para quitar una política de Snapshot, debelink:manage-links.html["asocie un enlace"]. Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Después de asociar el enlace, vuelva a esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos que contiene el volumen al que asignar una política de instantáneas y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Storage VMs*.
. En la pestaña *VM de almacenamiento*, seleccione el menú de tres puntos para la VM de almacenamiento que contiene el volumen a proteger con instantáneas programadas, luego *Acciones avanzadas* y luego *Administrar políticas de instantáneas*.
. En la página de administración de políticas Snapshot, seleccione el menú de tres puntos de la política de instantáneas y, a continuación, seleccione *Asignar política al volumen*.
. En el cuadro de diálogo Asignar política de instantáneas, seleccione *Ninguno* para eliminar la política de instantáneas.
. Selecciona *Asignar*.


.Resultado
Se elimina la política de Snapshot del volumen.



== Elimine una política de Snapshot

Elimine una política de Snapshot cuando ya no la necesite.

Cuando se asigna una política de Snapshot a más de un volumen, debe configurarse de forma manual <<Quite una política de Snapshot de un volumen,retírelo>> desde todos los volúmenes para eliminar la política de Snapshot. Como alternativa, también es posible <<Asigne una política de Snapshot a un volumen,asigne una política de snapshot diferente>> acceder a los volúmenes.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Storage VMs*.
. En la pestaña *Storage VMs*, seleccione el menú de tres puntos de la VM de almacenamiento con la política de instantáneas que desea eliminar, luego *Advanced Actions* y luego *Manage snapshot policies*.
. En la página de administración de políticas de Snapshot, seleccione el menú de tres puntos para eliminar la política de instantáneas y, a continuación, seleccione *Eliminar*.
. En el cuadro de diálogo Eliminar, seleccione *Eliminar* para eliminar la política.


.Resultado
Se elimina la política de Snapshot.
