---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Amazon FSX para ONTAP de NetApp
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/known-limitations.html"
  - title: Manos a la obra
    entries:
    - title: Obtenga más información sobre Amazon FSX para ONTAP de NetApp
      url: "/learn-fsx-ontap.html"
    - title: Inicio rápido
      url: "/quick-start.html"
    - title: Crea un sistema de archivos FSx for ONTAP
      url: "/create-file-system.html"
  - title: Utilice Amazon FSX para ONTAP de NetApp
    entries:
    - title: Explora el ahorro
      url: "/explore-savings.html"
    - title: Seguimiento y análisis de FSx para los costos de ONTAP
      url: "/track-costs.html"
    - title: Utilice los enlaces
      entries:
      - title: Conozca los enlaces
        url: "/links-overview.html"
      - title: Conéctese a un sistema de archivos mediante un enlace
        url: "/create-link.html"
      - title: Gestionar enlaces
        url: "/manage-links.html"
    - title: Descubra y visualice los volúmenes de caché
      url: "/discover-cache-volumes.html"
    - title: Gestione los volúmenes
      entries:
      - title: Cree un volumen
        url: "/create-volume.html"
      - title: Acceda a sus datos
        url: "/access-data.html"
    - title: Crear recursos de almacenamiento en bloque
      entries:
      - title: Crear un igroup
        url: "/create-igroup.html"
      - title: Crear un dispositivo de bloque
        url: "/create-block-device.html"
    - title: Cree una máquina virtual de almacenamiento
      url: "/create-storage-vm.html"
    - title: Proteja sus datos
      entries:
      - title: Información general sobre la protección de datos
        url: "/data-protection-overview.html"
      - title: Usar instantáneas
        entries:
        - title: Crear una copia de Snapshot
          url: "/create-snapshot.html"
        - title: Crear una política de Snapshot
          url: "/create-snapshot-policy.html"
        - title: Restaurar un volumen a partir de una copia de Snapshot
          url: "/restore-volume-from-snapshot.html"
      - title: Utilice copias de seguridad para el almacenamiento de objetos
        entries:
        - title: Cree una copia de seguridad manual
          url: "/create-backup.html"
        - title: Restaurar un volumen desde un backup
          url: "/restore-from-backup.html"
      - title: Utilizar replicación
        entries:
        - title: Cree una relación de replicación
          url: "/create-replication.html"
        - title: Inicializar una relación de replicación
          url: "/initialize-replication.html"
      - title: Proteger los datos con Protección autónoma frente al ransomware
        url: "/ransomware-protection.html"
      - title: Clonar un volumen
        url: "/clone-volume.html"
      - title: Use datos de ONTAP en las instalaciones
        url: "/use-onprem-data.html"
      - title: Crea una bóveda cibernética para proteger los datos.
        url: "/create-cyber-vault.html"
  - title: Administración y supervisión
    entries:
    - title: Supervise las operaciones con Tracker
      url: "/monitor-operations.html"
    - title: Implementar las mejores prácticas del sistema de archivos
      entries:
      - title: Análisis de configuración de FSx para ONTAP
        url: "/configuration-analysis.html"
      - title: Implemente configuraciones de sistemas de archivos bien diseñadas
        url: "/improve-configurations.html"
    - title: Analizar FSx para eventos de ONTAP EMS
      url: "/analyze-events.html"
    - title: Administración de volúmenes
      entries:
      - title: Editar el crecimiento automático de volúmenes
        url: "/edit-volume-autogrow.html"
      - title: Ajustar la capacidad de volumen
        url: "/adjust-volume-capacity.html"
      - title: Reequilibrar la capacidad de volumen
        url: "/rebalance-volume.html"
      - title: Gestionar archivos inmutables
        url: "/manage-immutable-files.html"
      - title: Gestione etiquetas de volumen
        url: "/manage-volume-tags.html"
      - title: Administrar volúmenes de caché
        url: "/manage-cache-volumes.html"
      - title: Cambie una política de organización en niveles
        url: "/change-tiering-policy.html"
      - title: Actualice la eficiencia del almacenamiento
        url: "/update-storage-efficiency.html"
      - title: Gestione las políticas de exportación de NFS
        url: "/manage-nfs-export-policy.html"
      - title: Administrar recursos compartidos SMB/CIFS
        url: "/manage-cifs-share.html"
      - title: Administrar puntos de acceso S3
        url: "/manage-s3-access-points.html"
      - title: Divida un volumen clonado
        url: "/split-cloned-volume.html"
      - title: Eliminar un volumen
        url: "/delete-volume.html"
    - title: Administración de almacenamiento en bloque
      entries:
      - title: Gestiona igroups
        url: "/manage-igroups.html"
      - title: Administrar dispositivos de bloque
        url: "/manage-block-devices.html"
    - title: Administración del sistema de archivos
      entries:
      - title: Ajustar la capacidad del sistema de archivos
        url: "/increase-file-system-capacity.html"
      - title: Habilitar la gestión automática de capacidad e inodos
        url: "/enable-auto-capacity-management.html"
      - title: Administrar etiquetas del sistema de archivos
        url: "/manage-fsx-tags.html"
      - title: Restablezca la contraseña de fsxadmin
        url: "/reset-fsxadmin-password.html"
      - title: Suprimir un sistema de archivos
        url: "/delete-file-system.html"
    - title: Administración de máquinas virtuales de almacenamiento
      entries:
      - title: Replicación de un equipo virtual de almacenamiento en otro sistema
          de archivos
        url: "/replicate-svm-to-file-system.html"
      - title: Configure y actualice Active Directory para una máquina virtual de
          almacenamiento
        url: "/configure-active-directory.html"
      - title: Gestionar las etiquetas de equipos virtuales de almacenamiento
        url: "/manage-svm-tags.html"
      - title: Restablecer la contraseña de la máquina virtual de almacenamiento
        url: "/reset-svm-password.html"
      - title: Eliminar una máquina virtual de almacenamiento
        url: "/delete-svm.html"
    - title: Administración de la protección de datos
      entries:
      - title: Snapshot
        entries:
        - title: Permite gestionar políticas Snapshot
          url: "/manage-snapshot-policy.html"
        - title: Habilite y edite snapshots para retención a largo plazo
          url: "/enable-snapshots-long-term.html"
        - title: Gestionar copias Snapshot
          url: "/manage-snapshots.html"
      - title: Completos
        entries:
        - title: Gestione la programación de backups de FSx para ONTAP
          url: "/manage-backup-schedule.html"
      - title: Replicación
        entries:
        - title: Replique un volumen de protección de datos
          url: "/cascade-replication.html"
        - title: Invierta una relación de replicación
          url: "/reverse-replication.html"
        - title: Cambie la programación de replicación de un volumen de origen
          url: "/change-replication-schedule.html"
        - title: Limite la tasa de transferencia máxima de una relación de replicación
          url: "/limit-transfer-rate.html"
        - title: Actualización manual de datos de instantáneas en una relación de
            replicación
          url: "/update-snapshot-replication.html"
        - title: Pausa y reanuda una relación de replicación
          url: "/pause-resume-replication.html"
        - title: Detener una relación de replicación
          url: "/stop-replication.html"
        - title: Eliminar una relación de replicación
          url: "/delete-replication.html"
    - title: Administración del rendimiento
      entries:
      - title: Aprovisione IOPS para un sistema de archivos
        url: "/provision-iops.html"
      - title: Actualice la capacidad de rendimiento de un sistema de archivos
        url: "/update-throughput-capacity.html"
  - title: Referencia
    entries:
    - title: Rendimiento para FSx para ONTAP
      url: "/performance-reference.html"
    - title: Seguridad para FSx para ONTAP
      url: "/security-reference.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/support-registration.html"
    - title: Obtenga ayuda
      url: "/get-help.html"
    - title: Resolución de problemas
      url: "/troubleshooting.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
