---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Amazon FSX para ONTAP de NetApp
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/known-limitations.html"
  - title: Manos a la obra
    entries:
    - title: Obtenga más información sobre Amazon FSX para ONTAP de NetApp
      url: "/learn-fsx-ontap.html"
    - title: Inicio rápido
      url: "/quick-start.html"
  - title: Utilice Amazon FSX para ONTAP de NetApp
    entries:
    - title: Explora el ahorro
      url: "/explore-savings.html"
    - title: Crear recursos de almacenamiento
      entries:
      - title: Crea un sistema de archivos FSx for ONTAP
        url: "/create-file-system.html"
      - title: Cree una máquina virtual de almacenamiento
        url: "/create-storage-vm.html"
      - title: Cree un volumen
        url: "/create-volume.html"
      - title: Crear un igroup
        url: "/create-igroup.html"
      - title: Crear un dispositivo de bloque
        url: "/create-block-device.html"
    - title: Conozca los enlaces
      url: "/learn-about-links.html"
    - title: Descubra y visualice los volúmenes de caché
      url: "/discover-cache-volumes.html"
    - title: Acceda a sus datos
      url: "/access-data.html"
  - title: Proteja sus datos
    entries:
    - title: Información general sobre la protección de datos
      url: "/data-protection-overview.html"
    - title: Utiliza instantáneas para proteger datos
      entries:
      - title: Utiliza instantáneas para proteger datos
        url: "/use-snapshots.html"
      - title: Permite gestionar políticas Snapshot
        url: "/manage-snapshot-policy.html"
      - title: Gestionar copias Snapshot
        url: "/manage-snapshots.html"
    - title: Utilice copias de seguridad para el almacenamiento de objetos
      url: "/use-backups.html"
    - title: Utiliza la replicación para proteger los datos
      entries:
      - title: Replicar datos
        url: "/create-replication.html"
      - title: Replica datos de ONTAP locales en FSx for ONTAP
        url: "/use-onprem-data.html"
      - title: Replicación de un equipo virtual de almacenamiento en otro sistema
          de archivos
        url: "/replicate-svm-to-file-system.html"
      - title: Haz un seguimiento de los retrasos en la replicación
        url: "/track-replication-delays.html"
      - title: Gestiona las relaciones de replicación
        url: "/manage-replication.html"
    - title: Proteger los datos con Protección autónoma frente al ransomware
      url: "/ransomware-protection.html"
    - title: Clonar un volumen
      url: "/clone-volume.html"
    - title: Crea una bóveda cibernética para proteger los datos.
      url: "/create-cyber-vault.html"
  - title: Gestiona FSx para ONTAP en Workload Factory
    entries:
    - title: Analizar FSx para eventos de ONTAP EMS
      url: "/analyze-events.html"
    - title: Implementar las mejores prácticas del sistema de archivos
      entries:
      - title: Análisis de configuración de FSx para ONTAP
        url: "/configuration-analysis.html"
      - title: Implemente configuraciones de sistemas de archivos bien diseñadas
        url: "/improve-configurations.html"
    - title: Seguimiento y análisis de FSx para los costos de ONTAP
      url: "/track-costs.html"
    - title: Gestionar volúmenes
      entries:
      - title: Gestiona la capacidad de volumen
        url: "/manage-volume-capacity.html"
      - title: Establecer umbrales de latencia de volumen
        url: "/set-volume-latency-thresholds.html"
      - title: Gestiona la configuración del volumen
        url: "/manage-volume-settings.html"
      - title: Administrar volúmenes de caché
        url: "/manage-cache-volumes.html"
      - title: Cambie una política de organización en niveles
        url: "/change-tiering-policy.html"
      - title: Gestione las políticas de exportación de NFS
        url: "/manage-nfs-export-policy.html"
      - title: Administrar recursos compartidos SMB/CIFS
        url: "/manage-cifs-share.html"
      - title: Administrar puntos de acceso S3
        entries:
        - title: Crear y conectar puntos de acceso S3
          url: "/create-s3-access-points.html"
        - title: Editar puntos de acceso S3
          url: "/edit-s3-access-points.html"
        - title: Configura la infraestructura de la tabla de registro en diario
          url: "/setup-journal-table.html"
        - title: Ver detalles sobre los puntos de acceso S3
          url: "/view-s3-details.html"
        - title: Eliminar puntos de acceso S3
          url: "/delete-s3-access-points.html"
      - title: Divida un volumen clonado
        url: "/split-cloned-volume.html"
      - title: Eliminar un volumen
        url: "/delete-volume.html"
    - title: Gestiona el almacenamiento en bloque
      entries:
      - title: Gestiona el almacenamiento en bloque
        url: "/manage-block-storage.html"
      - title: Aplicar etiquetas a dispositivos de bloque
        url: "/apply-block-device-tags.html"
    - title: Gestiona sistemas de archivos
      entries:
      - title: Ajustar la capacidad del sistema de archivos
        url: "/adjust-file-system-capacity.html"
      - title: Administra la configuración del sistema de archivos
        url: "/manage-file-system-settings.html"
      - title: Aprovisione IOPS para un sistema de archivos
        url: "/provision-iops.html"
      - title: Suprimir un sistema de archivos
        url: "/delete-file-system.html"
    - title: Gestiona máquinas virtuales de almacenamiento
      entries:
      - title: Administra la configuración de las máquinas virtuales de almacenamiento
        url: "/manage-svm-settings.html"
      - title: Eliminar una máquina virtual de almacenamiento
        url: "/delete-svm.html"
    - title: Supervise las operaciones con Tracker
      url: "/monitor-operations.html"
  - title: Referencia
    entries:
    - title: Rendimiento para FSx para ONTAP
      url: "/performance-reference.html"
    - title: Seguridad para FSx para ONTAP
      url: "/security-reference.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/support-registration.html"
    - title: Obtenga ayuda
      url: "/get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
