---
sidebar: sidebar 
permalink: provision-iops.html 
keywords: iops, SSD, provision, allocate 
summary: Aprovisiona automáticamente o aprovisiona manualmente las IOPS de SSD para un sistema de archivos FSx para ONTAP. 
---
= Aprovisione las IOPS de SSD para un sistema de archivos FSx para ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aprovisiona automáticamente o aprovisiona manualmente IOPS de SSD para un sistema de archivos FSx para ONTAP en la fábrica de cargas de trabajo de BlueXP .

.Acerca de esta tarea
Puede habilitar el aprovisionamiento automático de IOPS de SSD para un sistema de archivos FSx o aprovisionar IOPS manualmente.

Las IOPS aprovisionadas automáticamente se calculan como 3 IOPS por GiB.

Si aprovisiona IOPS manualmente, es posible que deba aumentar las IOPS antes de link:increase-file-system-capacity.html["aumentando la capacidad del sistema de archivos"].

Para obtener más información sobre los límites de IOPS, consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Cuotas"^]la documentación de AWS FSx para NetApp ONTAP.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Ir a Inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos para aprovisionar IOPS y luego selecciona *Administrar*.
. En Información, seleccione el icono de lápiz que aparece junto a la flecha desplegable cuando el ratón pasa por encima de la fila de asignación de IOPS*.
. En el cuadro de diálogo de IOPS aprovisionado, seleccione *Automático* o *Provisioned por el usuario*.
. Si selecciona *User Provisioned*, introduzca el valor de *IOPS* deseado.
. Seleccione *aplicar*.

