---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: Compruebe y reequilibre la capacidad de un volumen para evitar desequilibrios que se desarrollan a lo largo del tiempo. 
---
= Comprobar y reequilibrar la capacidad de un volumen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Compruebe el equilibrio de la capacidad del volumen de FlexGroup y reequilibre la capacidad del volumen para distribuir los archivos de forma uniforme por todos los componentes de modo que todos los nodos participen en la carga de trabajo de un único volumen de Flex Group.

.Acerca de esta tarea
La capacidad de volumen de FlexGroup se distribuye entre varios componentes en un sistema de archivos de escalado horizontal FSx para ONTAP con dos o más pares de alta disponibilidad (HA). Cada componente es un contenedor que dicta el tamaño máximo de archivo único. FSX para ONTAP distribuye los archivos entre todos los componentes de forma uniforme para que todos los nodos participen en la carga de trabajo de un único volumen de FlexGroup.

Cuando los componentes no se distribuyen de manera uniforme entre todos los nodos, el rendimiento del volumen de FlexGroup disminuye.

La comprobación del equilibrio de la capacidad del volumen de FlexGroup incluye la evaluación de la distribución actual de los componentes. Cuando se reequilibra la capacidad del volumen, la fábrica de cargas de trabajo de BlueXP  diseña un nuevo diseño de componentes con un número par de componentes para distribuir los datos de manera uniforme entre todos los pares de alta disponibilidad. El servicio ejecuta el plan de reequilibrio que, a su vez, mejora las operaciones de lectura y escritura.

El reequilibrio de un volumen redistribuye la capacidad cuando se desarrollan desequilibrios con el tiempo debido al aumento de nuevos archivos y archivos. Después de iniciar manualmente la operación de reequilibrio, seleccionamos los archivos y los movemos automáticamente y sin interrupciones. Las operaciones de transferencia de volúmenes consumen recursos del sistema de archivos.


NOTE: El reequilibrio solo se admite para volúmenes FlexGroup, pero no para volúmenes FlexGroup de iSCSI o NVMe.



== Compruebe el equilibrio de un volumen de FlexGroup

Compruebe el equilibrio de un volumen de FlexGroup activo.

.Antes de empezar
* FlexGroup Volume Balance solo está disponible para sistemas de archivos FSx para ONTAP mediante una puesta en marcha de escalado horizontal con al menos dos pares de alta disponibilidad.
* El estilo del volumen debe ser un volumen FlexGroup.
* Para comprobar el equilibrio de un volumen de FlexGroup, link:manage-links.html["asocie un enlace"]debe . Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Después de asociar el enlace, vuelva a esta operación.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos que contiene el volumen a reequilibrar y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volúmenes, selecciona *Comprobar balance de FlexGroup* en la parte superior de la tabla.
. En la ventana FlexGroup Balance, revise el estado Balance de todos los volúmenes de FlexGroup en el sistema de archivos FSx para ONTAP.
+
Cuando un volumen de FlexGroup está desequilibrado, considere <<Reequilibrar un volumen de FlexGroup,reequilibrando la tecnología>>.





== Reequilibrar un volumen de FlexGroup

Vuelva a equilibrar uno o varios volúmenes desequilibrados. Los datos se redistribuyen por los volúmenes miembro para reequilibrar el volumen de FlexGroup. En función de la distribución de los datos que prefiera, la operación de reequilibrio puede añadir volúmenes miembro FlexGroup y aumentar el tamaño de los volúmenes aprovisionados.


NOTE: Un administrador de fábrica de cargas de trabajo puede detener el reequilibrio durante la operación.

.Antes de empezar
* <<Compruebe el equilibrio de un volumen de FlexGroup,Compruebe el equilibrio de un volumen de FlexGroup>> antes de reequilibrar volúmenes.
* Para reequilibrar un volumen, se debe link:manage-links.html["asocie un enlace"]. Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Después de asociar el enlace, vuelva a esta operación.
* Tenga en cuenta que las snapshots existentes de los volúmenes que se reequilibran se vuelven parciales y no se pueden usar para restaurar los datos del volumen. Sin embargo, se pueden utilizar nuevas snapshots creadas después del reequilibrio para restaurar datos del volumen.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos que contiene el volumen a reequilibrar y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volúmenes, selecciona *Comprobar balance de FlexGroup* en la parte superior de la tabla.
. En la ventana Balance de FlexGroup, selecciona *Reequilibrio* para reequilibrar uno o más volúmenes desequilibrados.
. En el asistente para reequilibrar, seleccione el diseño de distribución de datos que prefiera.
+
** *Rendimiento optimizado* (recomendado): Aumenta el número de volúmenes miembros de FlexGroup y el tamaño aprovisionado del volumen. Sigue las prácticas recomendadas de NetApp.
** *Restringido*: Soporta volúmenes en una relación de replicación. La cantidad de volúmenes miembro FlexGroup y el tamaño de los volúmenes aprovisionados siguen siendo los mismos. Se selecciona de forma predeterminada si todos los volúmenes seleccionados participan en una relación de replicación.
** *Manual*: Seleccione la cantidad deseada de volúmenes miembro de FlexGroup por par de alta disponibilidad. Según la selección, la cantidad de volúmenes miembro FlexGroup y el tamaño aprovisionado del volumen pueden aumentar.


. *Desaceleración*: Opcional. Desactivado de forma predeterminada. Habilite la limitación para limitar el ancho de banda de un movimiento de volúmenes en el sistema de archivos y ralentizar el tráfico de replicación de volúmenes saliente.
+
Introduzca el valor del acelerador en MB/s.

. Seleccione una vista de comparación de diseño y luego seleccione *Siguiente*.
+
** Comparación de la distribución de volúmenes
** Comparación de diseños de FSx para ONTAP


. Opcionalmente, puede descargar una lista de movimientos de volúmenes antes de reequilibrar.
. Selecciona *Reequilibrio*.


.Resultado
Según la cantidad de volúmenes miembro de FlexGroup que se añadan a FlexGroup, se producirá una operación de movimiento de miembro de volúmenes FlexGroup única cada vez. Una vez que finalice la operación, el sistema de archivos se acelerará de nuevo al valor original.
