---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: Verificar y reequilibrar la capacidad de volumen para evitar desequilibrios que se desarrollen con el tiempo. 
---
= Verificar y reequilibrar la capacidad de volumen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Verifique el equilibrio de la capacidad del volumen FlexVol o FlexGroup y reequilibre la capacidad del volumen para distribuir los archivos de manera uniforme entre todos los volúmenes FlexVol en un nodo o entre todos los constituyentes, de modo que todos los nodos participen en la carga de trabajo de un solo volumen FlexGroup.



== Acerca de esta tarea

Se admite el reequilibrio de la capacidad de volumen para los volúmenes FlexVol y los volúmenes FlexGroup. El reequilibrio de un volumen redistribuye la capacidad cuando se desarrollan desequilibrios con el tiempo debido al aumento de nuevos archivos y archivos. Después de iniciar manualmente la operación de reequilibrio, seleccionamos los archivos y los movemos automáticamente y sin interrupciones. Las operaciones de transferencia de volúmenes consumen recursos del sistema de archivos.

Cada tipo de volumen y operaciones de reequilibrio difieren de la siguiente manera.

.Volúmenes de FlexVol
Los volúmenes FlexVol son contenedores lógicos que ofrecen flexibilidad en la gestión de datos, permitiendo la expansión, contracción, movimiento y copia eficiente. Se pueden utilizar con entornos NAS y SAN.

Un volumen FlexVol se puede equilibrar con respecto a otros volúmenes FlexVol dentro de un nodo en un sistema de archivos de FSx for ONTAP. Si el sistema de archivos solo tiene un volumen FlexVol, no es posible reequilibrarlo. Cuando el sistema de archivos tiene más de un volumen FlexVol por nodo y se selecciona un solo volumen FlexVol, este se equilibra con respecto a todos los FlexVol, pero solo se permite el movimiento del volumen seleccionado.

.Volúmenes de FlexGroup
Los volúmenes FlexGroup, por otro lado, son contenedores NAS escalables diseñados para un alto rendimiento y una distribución automática de la carga. Constan de múltiples volúmenes miembros (componentes) que comparten el tráfico de forma transparente. Los volúmenes FlexGroup ofrecen una capacidad masiva, que supera los límites de FlexVol, con hasta 60 PB y 400 000 millones de archivos. Simplifican la gestión al ofrecer un único contenedor de espacio de nombres.

La capacidad se distribuye entre varios componentes en un sistema de archivos FSx para ONTAP escalable con dos o más pares de alta disponibilidad (HA). Cada componente es un contenedor que dicta el tamaño máximo de archivo único. FSX para ONTAP distribuye los archivos entre todos los componentes de forma uniforme para que todos los nodos participen en la carga de trabajo de un único volumen de FlexGroup.

Cuando los componentes no se distribuyen de manera uniforme entre todos los nodos, el rendimiento del volumen de FlexGroup disminuye.

Para comprobar el equilibrio de la capacidad de volumen de FlexGroup es necesario evaluar la distribución actual de los componentes.  Al reequilibrar la capacidad del volumen, NetApp Workload Factory diseña un nuevo diseño de constituyentes con una cantidad par de constituyentes para distribuir los datos de manera uniforme entre todos los pares de alta disponibilidad.  El servicio ejecuta el plan de reequilibrio que a su vez mejora las operaciones de lectura y escritura.


NOTE: El reequilibrio no es compatible con volúmenes SAN como iSCSI y NVMe.



== Comprueba el saldo de tus volúmenes

Verifique el equilibrio de los volúmenes FlexVol o FlexGroup en un sistema de archivos FSx para ONTAP.

.Antes de empezar
* FlexGroup Volume Balance solo está disponible para sistemas de archivos FSx para ONTAP mediante una puesta en marcha de escalado horizontal con al menos dos pares de alta disponibilidad.
* Para comprobar el saldo de un volumen, debes link:manage-links.html["asocie un enlace"] . Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Después de asociar el enlace, vuelva a esta operación.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, seleccione *Ir a almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos que contiene los volúmenes que desea reequilibrar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña Volúmenes, seleccione *Verificar saldo de volumen* en la parte superior de la tabla.
. En la ventana de saldo de volumen, revise el estado del saldo de:
+
** Volúmenes de FlexGroup
** Volúmenes de FlexVol
+
Cuando un volumen no está equilibrado, considere <<Reequilibrar la capacidad de volumen,reequilibrando la tecnología>> .







== Reequilibrar la capacidad de volumen

Vuelva a equilibrar uno o varios volúmenes desequilibrados.


NOTE: Un administrador de Workload Factory puede<<Detener una operación de reequilibrio de volumen,dejar de reequilibrar>> Durante la operación.

.Antes de empezar
* <<Comprueba el saldo de tus volúmenes,Comprobar el equilibrio de un volumen>> antes de reequilibrar volúmenes.
* Para reequilibrar un volumen, se debe link:manage-links.html["asocie un enlace"]. Si no tienes un enlace existente, link:create-link.html["cree un vínculo"]. Para asociar un enlace en el sistema de archivos, seleccione *Enlace asociado* en *Nombre de cuenta*. Después de asociar el enlace, vuelva a esta operación.
* Tenga en cuenta que las snapshots existentes de los volúmenes que se reequilibran se vuelven parciales y no se pueden usar para restaurar los datos del volumen. Sin embargo, se pueden utilizar nuevas snapshots creadas después del reequilibrio para restaurar datos del volumen.
* Es mejor reequilibrar los volúmenes FlexVol en su conjunto para equilibrar todos los recursos de volumen de forma uniforme. Los volúmenes deseleccionados no participan activamente en el proceso de equilibrio.


[role="tabbed-block"]
====
.Volumen FlexVol
--
Un volumen FlexVol se puede equilibrar con respecto a otros volúmenes FlexVol dentro de un nodo en un sistema de archivos FSx for ONTAP. Cuando el sistema de archivos tiene más de un volumen FlexVol por nodo y se selecciona un solo volumen FlexVol, este se equilibra con respecto a todos los FlexVol, pero solo se permite el movimiento del volumen seleccionado.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, seleccione *Ir a almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos que contiene el volumen que desea reequilibrar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña Volúmenes, seleccione *Verificar saldo de volumen* en la parte superior de la tabla.
. En la ventana de balance de volúmenes, seleccione opcionalmente *Distribución de datos* en el resumen de balance de FlexVol para ver la capacidad utilizada por agregado.
. Seleccione *Reequilibrar* para reequilibrar uno o más volúmenes desequilibrados.
. En el asistente de reequilibrio, siga los pasos.
+
.. *Velocidad máxima de transferencia*: Opcional. Desactivado de forma predeterminada. Habilite la limitación para limitar el ancho de banda de un movimiento de volúmenes en el sistema de archivos y ralentizar el tráfico de replicación de volúmenes saliente.
+
Introduzca el valor del acelerador en MB/s.

+
Seleccione *Siguiente*.

.. Revise los diseños actuales y propuestos de todos los volúmenes FlexVol y luego seleccione *Siguiente*.
.. Revise cuidadosamente lo que sucederá y la nota antes de comenzar la operación de reequilibrio.


. Selecciona *Reequilibrio*.


.Resultado
Se reequilibra el volumen FlexVol. Una vez que finalice la operación, el sistema de archivos se acelerará de nuevo al valor original.

--
.Volumen FlexGroup
--
Los datos se redistribuyen por los volúmenes miembro para reequilibrar el volumen de FlexGroup. Según el diseño elegido, la operación de reequilibrio podría agregar volúmenes miembros de FlexGroup y aumentar el tamaño de los volúmenes aprovisionados.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, seleccione *Ir a almacenamiento*
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos que contiene el volumen que desea reequilibrar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña Volúmenes, selecciona *Comprobar balance de FlexGroup* en la parte superior de la tabla.
. En la ventana Balance de FlexGroup, selecciona *Reequilibrio* para reequilibrar uno o más volúmenes desequilibrados.
. En el asistente para reequilibrar, seleccione el diseño de distribución de datos que prefiera.
+
** *Rendimiento optimizado* (recomendado): Aumenta el número de volúmenes miembros de FlexGroup y el tamaño aprovisionado del volumen. Sigue las prácticas recomendadas de NetApp.
** *Restringido*: Soporta volúmenes en una relación de replicación. La cantidad de volúmenes miembro FlexGroup y el tamaño de los volúmenes aprovisionados siguen siendo los mismos. Se selecciona de forma predeterminada si todos los volúmenes seleccionados participan en una relación de replicación.
** *Manual*: Seleccione la cantidad deseada de volúmenes miembro de FlexGroup por par de alta disponibilidad. Según la selección, la cantidad de volúmenes miembro FlexGroup y el tamaño aprovisionado del volumen pueden aumentar.


. *Desaceleración*: Opcional. Desactivado de forma predeterminada. Habilite la limitación para limitar el ancho de banda de un movimiento de volúmenes en el sistema de archivos y ralentizar el tráfico de replicación de volúmenes saliente.
+
Introduzca el valor del acelerador en MB/s.

. Seleccione una vista de comparación de diseño y luego seleccione *Siguiente*.
+
** Comparación de la distribución de volúmenes
** Comparación de diseños de FSx para ONTAP


. Opcionalmente, puede descargar una lista de movimientos de volúmenes antes de reequilibrar.
. Selecciona *Reequilibrio*.


.Resultado
Los volúmenes de los miembros de FlexGroup se mueven uno a la vez durante el reequilibrio. Una vez que finalice la operación, el sistema de archivos se acelerará de nuevo al valor original.

--
====


== Detener una operación de reequilibrio de volumen

Detenga una operación de reequilibrio en cualquier momento; no es disruptiva. Detener la operación cancela los movimientos de volumen activos.

Podrás iniciar otra operación de reequilibrio más tarde.

.Pasos
. Después de comenzar la operación de reequilibrio, desde la página de equilibrio de volumen, seleccione *Detener reequilibrio*.
. En el cuadro de diálogo Detener reequilibrio, seleccione *Detener*.


.Resultado
La operación de reequilibrio de volumen se detiene y los movimientos de volumen activos se cancelan.
