---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Cuando sea necesario, restablece la contraseña de una máquina virtual de almacenamiento en la fábrica de cargas de trabajo BlueXP . 
---
= Restablece la contraseña de la máquina virtual de almacenamiento en la fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cuando sea necesario, restablece la contraseña de una máquina virtual de almacenamiento en la fábrica de cargas de trabajo BlueXP .

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos FSX for ONTAP con la VM de almacenamiento para actualizar y luego selecciona *Administrar*.
. En la pestaña Overview del sistema de archivos, seleccione la pestaña *Storage VMs*.
. En la pestaña Storage VMs, seleccione el menú de tres puntos de la máquina virtual de almacenamiento para restablecer la contraseña.
. Seleccione *Restablecer contraseña*.
. En el cuadro de diálogo Reset password, proporcione lo siguiente:
+
.. *Nueva contraseña*: Introduzca una nueva contraseña para la VM de almacenamiento.
.. *Confirmar contraseña*: Ingrese la nueva contraseña de nuevo para confirmar.


. Seleccione *aplicar*.

