---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Restablezca la contraseña de la máquina virtual de almacenamiento cuando sea necesario. 
---
= Restablezca la contraseña para una máquina virtual de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Restablezca la contraseña de la máquina virtual de almacenamiento cuando sea necesario.

.Pasos
. Inicie sesión en link:https://console.workloads.netapp.com/["Consola de Workload Factory"^]
. En Almacenamiento, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos FSX for ONTAP con la VM de almacenamiento para actualizar y luego selecciona *Administrar*.
. En la pestaña Overview del sistema de archivos, seleccione la pestaña *Storage VMs*.
. En la pestaña Storage VMs, seleccione el menú de tres puntos de la máquina virtual de almacenamiento para restablecer la contraseña.
. Seleccione *Restablecer contraseña*.
. En el cuadro de diálogo Reset password, proporcione lo siguiente:
+
.. *Nueva contraseña*: Introduzca una nueva contraseña para la VM de almacenamiento.
.. *Confirmar contraseña*: Ingrese la nueva contraseña de nuevo para confirmar.


. Haga clic en *aplicar*.

