---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Restablezca la contraseña de una máquina virtual de almacenamiento en NetApp Workload Factory cuando sea necesario. 
---
= Restablecer la contraseña de la máquina virtual de almacenamiento en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Restablezca la contraseña de una máquina virtual de almacenamiento en NetApp Workload Factory cuando sea necesario.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. Desde Almacenamiento, seleccione *Ir a almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con la contraseña de la máquina virtual de almacenamiento que desea restablecer y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, en Máquinas virtuales de almacenamiento, seleccione *Administrar*.
. Desde la pantalla Administrar máquinas virtuales de almacenamiento, seleccione el menú de acciones de la máquina virtual de almacenamiento cuya contraseña desea restablecer y, luego, seleccione *Acciones básicas* > *Restablecer contraseña*.
. En el cuadro de diálogo Reset password, proporcione lo siguiente:
+
.. *Nueva contraseña*: Introduzca una nueva contraseña para la VM de almacenamiento.
.. *Confirmar contraseña*: Ingrese la nueva contraseña de nuevo para confirmar.


. Seleccione *aplicar*.

