---
sidebar: sidebar 
permalink: restore-volume-from-snapshot.html 
keywords: restore volume, snapshot 
summary: Restaura un volumen de FSx para ONTAP a partir de una instantánea cuando el volumen contenga archivos dañados o eliminados. 
---
= Restaurar un volumen a partir de una copia Snapshot en la fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
En la fábrica de cargas de trabajo de BlueXP , puede restaurar un volumen de FSx para ONTAP desde una instantánea cuando el volumen contiene archivos eliminados o dañados.

.Acerca de esta tarea
Esta operación restaura los datos de una copia de Snapshot a un volumen nuevo.

.Antes de empezar
Solo es posible restaurar un volumen a partir de una copia Snapshot si tiene una copia Snapshot existente del volumen.

Asegúrese de contar con capacidad suficiente para completar esta operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña *Volúmenes*, seleccione el menú de tres puntos para que el volumen se restaure desde una instantánea.
. Seleccione *Acciones de protección de datos*, *Snapshots*, luego *Restaurar volumen desde una instantánea*.
. En el cuadro de diálogo Restaurar volumen de una instantánea, en el campo *Nombre de la instantánea*, seleccione la instantánea que desea restaurar en el menú desplegable.
. En el campo *Nombre del volumen restaurado*, introduzca un nombre único para el volumen que desea restaurar.
. Seleccione *Restaurar*.

