---
sidebar: sidebar 
permalink: restore-volume-from-snapshot.html 
keywords: restore volume, snapshot 
summary: Restaura un volumen de FSx para ONTAP a partir de una instantánea cuando el volumen contenga archivos dañados o eliminados. 
---
= Restaurar un volumen desde una instantánea en la fábrica de carga de trabajo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
En la fábrica de carga de trabajo, puede restaurar datos desde una instantánea a un volumen existente o a un volumen nuevo.  La operación de restauración permite la recuperación en un punto determinado del tiempo cuando un volumen contiene archivos eliminados o dañados.

.Acerca de esta tarea
Tiene la opción de restaurar datos de una instantánea a un volumen existente o a un volumen nuevo.

La creación de un nuevo volumen a partir de una instantánea realiza una copia de un volumen completo en unos pocos segundos, independientemente del tamaño del volumen.  La copia recién creada representa un nuevo volumen.

.Antes de empezar
Tenga en cuenta las siguientes limitaciones antes de crear un volumen a partir de una copia de Snapshot:

* Solo es posible restaurar un volumen a partir de una copia Snapshot si tiene una copia Snapshot existente del volumen.
* Cambios en los modelos de permisos: Si utiliza esta operación para cambiar el tipo de protocolo de almacenamiento conectado a la red (NAS), también puede cambiar el modelo de permisos que proporciona el estilo de seguridad. Es posible que experimente problemas de permisos de acceso a archivos, que solo puede corregir manualmente con el acceso de administrador mediante la configuración de herramientas de cliente NAS para permisos.
* Mayor consumo de volumen: después de crear un volumen a partir de una instantánea, tiene dos volúmenes independientes y ambos consumen capacidad del sistema de archivos del host.  Asegúrese de tener suficiente capacidad para completar esta operación.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En *Almacenamiento*, selecciona *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos con el volumen y luego selecciona *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. En la pestaña *Volúmenes*, seleccione el menú de tres puntos para que el volumen se restaure desde una instantánea.
. Seleccione *Acciones de protección de datos* y luego *Administrar instantáneas*.
. Desde la página Administrar instantáneas, seleccione el menú de tres puntos correspondiente a la instantánea que desea restaurar y, luego, seleccione *Restaurar*.
. En el cuadro de diálogo Restaurar volumen desde una instantánea, seleccione una de las siguientes opciones:
+
** Cambie para seleccionar *Restaurar como un nuevo volumen*.
+
En el campo *Nombre del volumen restaurado*, introduzca un nombre único para el volumen que desea restaurar.

** Restaurar datos de una instantánea a un volumen existente.  Esta operación elimina de forma permanente cualquier dato que se haya modificado después del momento de creación de la instantánea.
+
Acepte la sentencia para continuar.



. Seleccione *Restaurar*.

