---
sidebar: sidebar 
permalink: restore-from-backup.html 
keywords: restore backup, new volume, volume restoration, backup 
summary: Restaura un volumen a partir de un backup a cualquier sistema de archivos de FSx para ONTAP en tu cuenta de AWS. 
---
= Restaurar un volumen desde una copia de seguridad en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
En NetApp Workload Factory, puede restaurar un volumen desde una copia de seguridad a cualquier sistema de archivos FSx para ONTAP en su cuenta de AWS.

La fábrica de cargas de trabajo determina si tiene suficiente capacidad para la restauración y puede añadir automáticamente capacidad del nivel de almacenamiento SSD en caso de que no lo haga.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos con el volumen y luego seleccione *Administrar*.
. En la descripción general del sistema de archivos, seleccione la pestaña *Volúmenes*.
. Desde la pestaña *Volúmenes*, seleccione el menú de acciones para el volumen que desea restaurar desde una copia de seguridad.
. Seleccione *Acciones de protección de datos*, *FSX para copia de seguridad de ONTAP* y luego *Restaurar desde una copia de seguridad*.
. En el cuadro de diálogo Restore from a backup, proporcione lo siguiente:
+
.. *Sistema de archivos de destino*: Seleccione el sistema de archivos de destino en el menú desplegable.
.. *Target storage VM*: Seleccione la VM de almacenamiento de destino en el menú desplegable.
.. *Nombre de la copia de seguridad*: Seleccione el nombre de la copia de seguridad en el menú desplegable.
.. *Nombre del volumen restaurado*: Introduzca el nombre del volumen restaurado.


. Verifique la capacidad del sistema de archivos para la operación de restauración.
+
Cuando la capacidad del sistema de archivos es limitada, se puede producir lo siguiente:

+
** La restauración puede aumentar la capacidad utilizada por encima del umbral especificado.  Puede completar la operación de restauración.  Considerarlink:increase-file-system-capacity.html["Adición manual de capacidad del nivel de almacenamiento SSD"] o seleccionar Workload Factory para agregar automáticamente capacidad de nivel de almacenamiento SSD.
** La restauración requiere capacidad SSD adicional.  Debe seleccionar que Workload Factory agregue automáticamente capacidad de nivel de almacenamiento SSD para continuar.


. Seleccione *Restaurar*.

