---
sidebar: sidebar 
permalink: reverse-replication.html 
keywords: reverse replication, change replication 
summary: Invierta una relación de replicación para que el volumen de destino se convierta en el volumen de origen. 
---
= Invierta una relación de replicación
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Invierta una relación de replicación para que el volumen de destino se convierta en el volumen de origen.

Después de detener la replicación y realizar cambios en el volumen objetivo, puede replicar esos cambios de nuevo en el volumen de origen. Este proceso es habitual en una situación de recuperación ante desastres en la que se opera en el volumen de destino durante un tiempo y se desean cambiar roles de los volúmenes.

.Acerca de esta tarea
Cuando se invierte y reanuda una replicación, se cambian los roles de origen y objetivo de los volúmenes; el volumen objetivo se convierte en el volumen de origen nuevo y el volumen de origen se convierte en el nuevo volumen objetivo. La operación inversa también sobrescribe el contenido del volumen objetivo nuevo con el contenido del volumen de origen nuevo. Si invierte una replicación dos veces, la dirección de replicación original se restablece.


NOTE: No se conserva ningún dato que se escriba en el volumen de origen original entre la última replicación de datos y la hora en la que se deshabilitó el volumen de origen.

.Antes de empezar
Asegúrese de conocer los roles actuales y futuros de los volúmenes de origen y objetivo, ya que los cambios en el nuevo volumen objetivo se sobrescribirán con el nuevo volumen de origen. Si se utiliza incorrectamente, puede experimentar una pérdida de datos involuntaria.

.Pasos
. Inicie sesión en link:https://console.workloads.netapp.com/["Consola de Workload Factory"^]
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, haz clic en el menú de tres puntos del sistema de archivos para actualizar y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, haga clic en el menú de tres puntos de la relación de replicación que desea revertir.
. Seleccione *Relación inversa*.
. En el cuadro de diálogo Relación inversa, haga clic en *Invertir*.

