---
sidebar: sidebar 
permalink: split-cloned-volume.html 
keywords: split clone volume, FlexVol volume 
summary: Divida un FlexVol volume de clones de su volumen principal para que el clon sea una FlexVol volume de lectura/escritura normal. 
---
= Divida un volumen clonado en la fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Divida un FlexVol volume clonado de su volumen principal para que el clon sea un FlexVol volume de lectura/escritura normal en la fábrica de cargas de trabajo BlueXP .

Se puede acceder a los datos en el clon y en el elemento principal durante la división. El proceso de división solo actualiza los metadatos y requiere una E/S mínima. No se copian bloques de datos.

.Acerca de esta tarea
La operación de división de clones implica lo siguiente:

* Durante la operación de división, no se pueden crear nuevas copias Snapshot del volumen FlexClone.
* Un volumen FlexClone no puede dividirse del volumen principal si pertenece a una relación de protección de datos.
* Si desconecta el volumen FlexClone mientras la separación está en curso, la operación de división se suspenderá; cuando el volumen FlexClone vuelva a estar en línea, se reanudará la operación de separación.
* Después de la división, tanto el volumen FlexVol principal como el clon requieren toda la asignación de espacio determinada por las garantías de volumen.
* Después de dividir un volumen FlexClone de su principal, no se pueden volver a unir dos.


.Antes de empezar
Tenga en cuenta lo siguiente antes de dividir un volumen clonado:

* Para dividir un volumen clonado, debe asociar un enlace. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda a asociar un enlace existente o a crear y asociar un nuevo enlace"]. Después de asociar el enlace, vuelva a esta operación.
* El volumen FlexClone debe estar en línea cuando comience la operación de división.
* El volumen primario debe estar en línea para que la división se complete correctamente.


.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. Seleccione la pestaña *Volúmenes*.
. En la pestaña Volumes, seleccione el menú de tres puntos del volumen con el volumen clonado que se va a dividir.
. Seleccione *Acciones de protección de datos*, luego *Dividir volumen clonado*.
. En el cuadro de diálogo Dividir volumen, seleccione *Eliminar*.


.Resultado
El clon de volumen se encuentra dividido y aparece en la pestaña Volumes.
