---
sidebar: sidebar 
permalink: stop-replication.html 
keywords: stop replication, break replication 
summary: Detener una relación de replicación entre los volúmenes de origen y destino en NetApp Workload Factory. 
---
= Detener una relación de replicación en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Detener una relación de replicación en NetApp Workload Factory.  Cuando se detiene una relación de replicación, se pausan las actualizaciones de replicación programadas desde el volumen de origen al volumen de destino.  El volumen de destino pasa de solo lectura a lectura/escritura.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Almacenamiento, seleccione *Ir a Almacenamiento*.
. En el menú Almacenamiento, seleccione *FSx para ONTAP*.
. Desde *FSx for ONTAP*, seleccione el menú de acciones del sistema de archivos a actualizar y luego seleccione *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, seleccione el menú de acciones de la relación de replicación que desea detener.
. Selecciona *Break*.
. En el cuadro de diálogo Break replication, seleccione *Break*.


.Resultado
El estado de replicación del volumen cambia a *roto*. El volumen objetivo pasa a ser editable.
