---
sidebar: sidebar 
permalink: update-snapshot-replication.html 
keywords: update snapshot data, replication 
summary: Actualizar manualmente los datos Snapshot que se transfieren entre los volúmenes de origen y objetivo en una relación de replicación en cualquier momento. 
---
= Actualizar los datos de snapshot en una relación de replicación
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Una relación de replicación tiene una programación de replicación establecida, pero puede actualizar manualmente los datos de Snapshot transferidos entre los volúmenes de origen y de destino en la fábrica de carga de trabajo de BlueXP  en cualquier momento.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, selecciona el menú de tres puntos del sistema de archivos para actualizar y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, seleccione el menú de tres puntos de la relación de replicación que desea actualizar.
. Selecciona *Actualizar ahora*.
. En el cuadro de diálogo Actualizar, seleccione *Actualizar ahora*.

