---
sidebar: sidebar 
permalink: update-snapshot-replication.html 
keywords: update snapshot data, replication 
summary: Actualizar manualmente los datos Snapshot que se transfieren entre los volúmenes de origen y objetivo en una relación de replicación en cualquier momento. 
---
= Actualizar los datos de snapshot en una relación de replicación
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Una relación de replicación tiene una programación de replicación establecida, pero puede actualizar manualmente los datos de instantánea transferidos entre los volúmenes de origen y de destino cuando sea necesario.

.Pasos
. Inicie sesión en link:https://console.workloads.netapp.com/["Consola de Workload Factory"^]
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña *FSX for ONTAP*, haz clic en el menú de tres puntos del sistema de archivos para actualizar y luego selecciona *Administrar*.
. Desde la descripción general del sistema de archivos, seleccione la pestaña *Relaciones de replicación*.
. En la pestaña Relaciones de replicación, haga clic en el menú de tres puntos de la relación de replicación que desea actualizar.
. Selecciona *Actualizar ahora*.
. En el cuadro de diálogo Actualizar, haga clic en *Actualizar ahora*.

