---
sidebar: sidebar 
permalink: view-volume-details.html 
keywords: volume details, volume information 
summary: Vea detalles de volumen, distribución, consumo, acceso y protección. 
---
= Ver detalles del volumen en la fábrica de cargas de trabajo BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vea detalles de volumen, distribución, consumo, acceso y protección.

Los detalles del volumen solo aparecen después de que se creó un volumen en un sistema de archivos.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En Almacenamiento, seleccione *Ir al inventario de almacenamiento*.
. En la pestaña Volumes, seleccione el menú de tres puntos para el volumen que desea modificar.
. Seleccione *Acciones básicas* y luego *Ver detalles del volumen*.
. En *Detalles del volumen*, seleccione las pestañas para ver los siguientes detalles del volumen:
+
.. *Detalles generales*: Incluye nombre del volumen, UUID del volumen, ID del volumen, hora de creación, estado, tipo de volumen (lectura/escritura/protección de datos (RW/DP) o solo lectura), nombre de la política de instantáneas, VM de almacenamiento de alojamiento (SVM) y etiquetas.
.. *Distribución*: Incluye agregados de alojamiento, estilo de volumen (FlexGroup o FlexVol), componentes (solo FlexGroup) y ratio de reequilibrio (solo FlexGroup -alto, medio o bajo).
.. *Consumo*: Incluye tamaño, SSD usado, pool de capacidad utilizado, ajuste de crecimiento automático, tamaño máximo de crecimiento, configuración de eficiencia del almacenamiento, ahorro de espacio de compresión, ahorro de espacio de deduplicación, política de organización en niveles y días de refrigeración.
.. *Acceso*: Incluye ruta de unión, estilo de seguridad, política de exportación y versión de NFS para NFS, y Active Directory, nombre de recurso compartido de CIFS, usuarios o grupos, y permisos para SMB/CIFS, y grupos de iniciadores y IQN de host para iSCSI.
.. *Protección*: Incluye instantánea local, nombre de la política de instantáneas, replicación remota y copia de seguridad de FSX para ONTAP.



