---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx for netapp ontap, fsx for ontap' 
summary: Descubra las novedades de Amazon FSx para NetApp ONTAP. 
---
= Lo nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de Amazon FSx para NetApp ONTAP.



== 1 de septiembre de 2024



=== Compatibilidad con modo lectura para la gestión del almacenamiento

El modo de lectura está disponible para la gestión del almacenamiento en Workload Factory. El modo de lectura mejora la experiencia del modo básico al agregar permisos de solo lectura para que las plantillas de infraestructura como código se rellenen con sus variables específicas. Las plantillas de infraestructura como código se pueden ejecutar directamente desde su cuenta de AWS sin tener que proporcionar permisos de modificación a Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Más información sobre el modo de lectura"^]



=== Realice backups antes de la eliminación de volúmenes

Ahora puede realizar un backup de un volumen antes de eliminarlo. La copia de seguridad permanecerá en el sistema de archivos hasta que se elimine.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["Eliminar un volumen"^]



== 4 de agosto de 2024



=== Soporte de terraform

Ahora puede utilizar Terraform desde CodeBox para implementar sistemas de archivos y equipos virtuales de almacenamiento.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Crear un sistema de archivos"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Cree una máquina virtual de almacenamiento"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilice Terraform de CodeBox"^]




=== Recomendaciones de rendimiento y IOPS en la calculadora de almacenamiento

La calculadora de almacenamiento hace recomendaciones para la configuración del sistema de archivos FSx para ONTAP para el rendimiento e IOPS basadas en las prácticas recomendadas de AWS, lo que proporciona una orientación óptima para sus selecciones.



== 7 de julio de 2024



=== Lanzamiento inicial de Workload Factory para Amazon FSx para NetApp ONTAP

Amazon FSx para NetApp ONTAP ya está disponible de forma general en Workload Factory.
