---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx' 
summary: Descubra las novedades de Amazon FSx para NetApp ONTAP. 
---
= Lo nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de Amazon FSx para NetApp ONTAP.



== 4 de agosto



=== Soporte de terraform

Ahora puede utilizar Terraform de CodeBox para implementar y gestionar sistemas de archivos y equipos virtuales de almacenamiento.

* link:create-file-system.html["Crear un sistema de archivos"]
* link:create-storage-vm.html["Cree una máquina virtual de almacenamiento"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilice Terraform de CodeBox"^]




=== Recomendaciones de rendimiento y IOPS en la calculadora de almacenamiento

La calculadora de almacenamiento hace recomendaciones para la configuración del sistema de archivos FSx para ONTAP para el rendimiento e IOPS basadas en las prácticas recomendadas de AWS, lo que proporciona una orientación óptima para sus selecciones.



== 7 de julio

Amazon FSx para NetApp ONTAP ya está disponible de forma general en BlueXP Workload Factory.

link:learn-fsx-ontap.html["Obtén más información sobre BlueXP Workload Factory para Amazon FSx para NetApp ONTAP"].
